swiftlang/swift-docc

Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json
Bug/issue #, if applicable: rdar://83667105, [SR-15354](https://bugs.swift.org/browse/SR-15354)
Update the render JSON spec for the changes introduced in #11.
None.
There should be no user-facing changes. Verify that the specification matches the JSON produced by Swift-DocC.
=> Update render JSON spec for variantOverrides

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Test Resources/Variant-render-node.json
Bug/issue #, if applicable: rdar://83398083
Adds support for the navigator index to process render JSON that contains variant overrides by applying patches for the languages in which the page is available.
Note: the first commit adds the support and second commit fixes a typo
None.
Verify that when building a navigator index that contains multi-language render JSON, the content gets curated under each language tree.
=> Navigator index multi-language render JSON support

Sources/SwiftDocC/DocumentationService/Convert/ConvertService+DataProvider.swift, Sources/SwiftDocC/DocumentationService/Convert/ConvertService.swift, Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Sources/SwiftDocC/Infrastructure/DocumentationBundle.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Infrastructure/Workspace/DataProviderBundleDiscovery.swift, Sources/SwiftDocC/Infrastructure/Workspace/DefaultAvailability.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationBundle+Info.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationWorkspaceDataProvider.swift, Sources/SwiftDocC/Infrastructure/Workspace/GeneratedDataProvider.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Utility/FoundationExtensions/Dictionary+TypedValues.swift, Sources/SwiftDocC/Utility/Version.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/DocumentationService/DocumentationServer+DefaultTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationWorkspaceTests.swift, Tests/SwiftDocCTests/Infrastructure/PresentationURLGeneratorTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift, Tests/SwiftDocCTests/Rendering/DefaultAvailabilityTests.swift, Tests/SwiftDocCTests/Rendering/DefaultCodeListingSyntaxTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystem.swift
This work refactors the existing logic for handling DocumentationBundle Info to make it easier to add new configuration options moving forward.
1. Use DocumentationBundle.Info to pass around bundle info. 
Currently we pass around DocumentationBundle Info as function parameters in a multitude of places. This means that when we add a new property to the `DocumentationBundle.Info` model, we have to add new function parameters in several places across the codebase. It's easy to miss some of these and I think likely to introduce bugs in the future.
We already have a model for handling documentation bundle info, so this just updates a number of calling sites to rely on passing around the DocumentationBundle.Info directly instead of its properties.
This change is isolated in this commit c357b35 …
=> Refactor DocumentationBundle.Info

Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
This patch disables the readonly fs indexing test due to the CI noise
and potential to leak resources on failures.
rdar://84986427
=> Disabling noisy readonly fs test

Tests/SwiftDocCUtilitiesTests/PreviewServer/PreviewServerTests.swift
We shouldn't be making network calls or accessing the temp directories
in CI tests.
rdar://85046362
=> Disabling PreviewServerTests due to networking

Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
This test has been failing frequently in Swift CI and is blocking other projects.
=> Disable 'testNavigationTreeLargeDumpAndReadAsync()'

Package.resolved, Package.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
=> Revert "Update swift-argument-parser"

Package.resolved, Package.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
This reverts commit bf9bdfb0abc6c6f74b5ed897d67e3e8b39e8395b.
=> [DO NOT MERGE] Revert "Revert "Update swift-argument-parser (#32)" (#34)"

Sources/DocCDocumentation/DocCDocumentation.docc/Info.plist, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationBundle+Info.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContextTests.swift, Tests/SwiftDocCTests/Test Bundles/BundleWithExecutableModuleKind.docc/ExampleDocumentedExecutable.symbols.json, Tests/SwiftDocCTests/Test Bundles/BundleWithExecutableModuleKind.docc/Info.plist
Bug/issue #, if applicable: [SR-15434](https://bugs.swift.org/browse/SR-15434) and <rdar://83448323>
Adds support for providing custom module kinds to Swift-DocC via a DocC Catalog's Info.plist or the command-line.
There is a detailed pitch for this feature on the [Swift Forums](https://forums.swift.org/t/improve-presentation-of-non-framework-documentation-sr-15434/53388).
This also updates Swift-DocC's user-facing documentation to be accurately described as a "Tool" instead of a "Framework".
| Before | After |
|--------|-------|
|   <img width="787" alt="Screen Shot 2021-11-03 at 3 06 08 PM" src="https://user-images.githubusercontent.com/6750147/141009934-01064745-4db0-46bd-83fc-9aa0b2f3be0b.png">    | <img width="818" alt="Screen Shot 2021-11-03 at 4 58 17 PM" …
=> [SR-15434] Add support for custom (non-framework) module kinds

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/ResolvedTopicReference+Symbol.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/SourceLanguage.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://84949759
Removes some hard-coding of swift language identifiers to allow for creation of an Objective-C navigator index from Objective-C symbol graph data.
Use the included Objective-C test fixture to build documentation and confirm that the generated RenderJSON contain Objective-C language identifiers and not Swift.
=> Support Objective-C navigator index creation

Tests/SwiftDocCTests/Converter/TopicRenderReferenceEncoderTests.swift
Bug/issue #, if applicable: rdar://85428149
This disables the concurrency encoding test for topic references due to failures in Swift CI for CentOS.
n/a
n/a
=> Disable concurrency encoding test

Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Sources/SwiftDocC/Model/Rendering/Variants/VariantCollection+Symbol.swift, Tests/SwiftDocCTests/Rendering/DocumentationContentRendererTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift
Bug/issue #, if applicable: rdar://84969308
Isolate the processing of subHeading and navigator fragments for rendering to Swift symbols.
This is cleanup work that should have no UX impact in practice. The code path that's been modified affects SGFs in languages other than Swift that use a declaration syntax that's similar to Swift's (e.g., `class MyClass {`), which there is no support known case of at the moment.
Also, added tests to cover existing subHeading and navigator fragments functionality for Swift symbols.
None.
For the reason described above, there should be no user-facing changes here.
=> Clean up fragment processing for non-Swift symbols

CONTRIBUTING.md, Dockerfile
Fixes test failures that were occurring when using the included Dockerfile to run Swift-DocC's tests for Linux. The test suite does not expect to be run on a root user account. This also better emulates the way tests will be run on Linux in the Swift.org CI system.
The changes to the Dockerfile are based on the Dockerfiles used in swift-ci here: https://github.com/apple/swift-docker/blob/main/swift-ci/master/ubuntu/20.04/Dockerfile.
None.
Follow the instructions in the CONTRIBUTING documentation [here](https://github.com/ethan-kusters/swift-docc/blob/update-dockerfile-for-linux-testing/CONTRIBUTING.md#using-docker-to-test-swift-docc-for-linux) and confirm that all tests pass.
=> Update Dockerfile to run tests without root permissions

Sources/SwiftDocC/Model/Rendering/RenderNode.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json
Increments the patch value of the render node schema to 0.2.0 to account
for addition of the top-level `variantOverrides` property introduced in #11. 
This is related to https://github.com/apple/swift-docc-render/pull/23.
N/A
=> Increment render node version for variantOverrides

build-script-helper.py
Bug/issue #, if applicable: rdar://85912344
This passes the `--verbose` flag to `swift build` for the "install" action to gather more information about a build failure in the CI.
It also fixes a build script error message to correctly name the action that failed.
n/a
n/a
=> Pass the verbose flag for "install" builds

Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Sources/SwiftDocC/Infrastructure/DocumentationBundle.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationBundle+Info.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/DocumentationService/DocumentationServer+DefaultTests.swift, Tests/SwiftDocCTests/Infrastructure/BundleDiscoveryTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationWorkspaceTests.swift, Tests/SwiftDocCTests/Infrastructure/PresentationURLGeneratorTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift, Tests/SwiftDocCTests/Rendering/DocumentationContentRendererTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystem.swift
Bug/issue #, if applicable: [SR-15372](https://bugs.swift.org/browse/SR-15372)
This removes the format requirements for the documentation bundle's version information and makes the version information optional.
n/a
- Convert a documentation catalog where the version in the Info.plist is an arbitrary string.
- Convert a documentation catalog where the version passed as fallback command line arguments an arbitrary string.
- Convert a documentation catalog where no version information is specified.
In all three cases the documentation should build without errors about the version information.
=> Remove the format requirements for the bundle's version information.

Sources/SwiftDocC/Infrastructure/Workspace/GeneratedDataProvider.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCTests/Infrastructure/GeneratedDataProvider.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: [SR-15408](https://bugs.swift.org/browse/SR-15408) rdar://84810134
This updates the `GeneratedDataProvider` to generate top level documentation extension files based on the module names from the available symbol graph files instead of the fallback display name. This means that:
- the documentation extension file will match one of the module symbols 
- if there are multiple modules there will be multiple generated documentation extension files
This PR also removes a small amount of ambiguity regarding the provider's use of `BundleDiscoveryOptions` by removing the options argument to the initializer. Previously, this value wasn't used when providing the bundles but it was used when providing their raw content. 
n/a
Call `docc convert` or `docc preview` with a …
=> Generate documentation content based on the symbol graph module names

Tests/SwiftDocCUtilitiesTests/StaticHostableTransformerTests.swift
Bug/issue #, if applicable: rdar://86300654
This updates `StaticHostableTransformerTests.testStaticHostableTransformerOutput` so that it doesn't rely on the order that the directory content is returned.
n/a
n/a
=> Sort output to avoid relying on the undefined order of directory content

Sources/SwiftDocC/Model/Identifier.swift, Tests/SwiftDocCTests/Model/IdentifierTests.swift
Bug/issue #, if applicable: rdar://86338175
Introduces a new API that restores the ability for clients to replace a topic reference's source languages value that was removed in e76ef474.
None.
No user-facing functionality modified- confirm that unit tests pass.
=> Add `ResolvedTopicReference.withSourceLanguages` API

Sources/DocCDocumentation/DocCDocumentation.docc/formatting-your-documentation-content.md
Bug/issue #, if applicable: 83398954
Adds documentation that lists the programming languages names (and aliases) that can be used in code listings for syntax highlighting purposes.
Steps:
1. Run `bin/preview-docs DocC`.
2. Verify that the documentation at http://localhost:8000/documentation/docc/formatting-your-documentation-content is updated with a new table showing all the supported options.
=> Document supported languages for syntax highlighting

Sources/SwiftDocC/SwiftDocC.docc/Resources/LinkableEntities.json
Bug/issue #, if applicable: rdar://87100087
This adds a missing `RenderContentMetadata` schema to LinkableEntities spec, making it a valid OpenAPI spec.
Note: like the RenderNode spec, this one is recursive because `RenderInlineContent` can be `Image` which has a `RenderContentMetadata` which has a `RenderInlineContent`. This is valid for OpenAPI specs.
n/a
n/a
=> Add missing `RenderContentMetadata` schema to Linkable Entities spec

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift
Bug/issue #, if applicable: rdar://86786641
Resolves an issue when running DocC within the SwiftPM plugin sandbox where LMDBs calls to `flock()`, which in turn calls `fsctl()`, are blocked by the SwiftPM plugin sandbox.
Running `docc convert` with the `--index` flag from within a SwiftPM plugin results in the following error:
```
[31m[1merror: [0m'docc convert' invocation failed with a nonzero exit code: '5'.
[plugin 'Swift-DocC Convert'] Swift/ErrorType.swift:200: Fatal error: Error raised at top level: PackagePlugin.PackageManagerProxyError.unspecified("ExitCode(rawValue: 1)")
[plugin 'Swift-DocC Convert'] 2021-12-17 10:47:27.747972-0800 Swift_DocC_Convert[93764:6330351] Swift/ErrorType.swift:200: Fatal error: Error raised at top level: …
```
=> Support indexing within the SwiftPM plugin sandbox

Sources/SwiftDocC/Infrastructure/Workspace/GeneratedDataProvider.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCTests/Infrastructure/GeneratedDataProvider.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Rationale: Fixes a bug where the built documentation would contain a broken looking article when the fallback display name doesn't match the module name in the symbol graph file.
Risk: Low.
Risk Detail: This is an isolated change that touches very little existing DocC code.
Reward: Low/Medium
Reward Details: For non-framework documentation it's not unusual to have spaces in a display name which wouldn't appear in the module name. The reward is somewhat small (avoiding an extra broken looking article) but the issue is somewhat common when building documentation for non-frameworks.
Original PR: Generate documentation content based on the symbol graph module names #52
Issue: rdar://84810134
Code Reviewed By: Ethan Kusters
Testing Details: New tests covering changes have been added. Existing …
=> [5.6] Generate documentation content based on the symbol graph module names

Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/LinkableEntities.json, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Rationale: This is an additive change to the LinkableEntities.json spec and `LinkDestinationSummary` implementation to support multi-language content. 
Risk: Low.
Risk Detail: This is an isolated change to an opt-in feature that's off by default.
Reward: Low/Medium
Reward Details: For documentation that export their "linkable entities" for other documentation to reference, this change enable that information in include multi-language content. 
Original PR: #54 
Issue: rdar://83716043
Code Reviewed By: Ethan Kusters
Testing Details: New tests covering changes have been added. Existing tests continue to pass.
=> [5.6] Update LinkDestinationSummary to support multi-language content

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift
- **Rationale:** Allows for docc to emit an index when generating documentation within a SwiftPM plugin.
- **Risk Detail:** This is an isolated change that touches very little existing DocC code. We had no need for LMDBs locking functionality so disabling it has no consequence for `docc`.
- **Reward Details:** Enables `docc` to be used within SwiftPM plugins.
- **Original PR:** #66
- **Issue:** rdar://86786641
- **Code Reviewed By:** @bontoJR
- **Testing Details:** Existing tests continue to pass. An integration test that confirms DocC is able to build a DocC archive that includes an index when run as part of a SwiftPM plugin will be included in the Swift-DocC-Plugin project and run as part of CI when the plugin is published.
=> [5.6] Support indexing within the SwiftPM plugin sandbox

Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
Bug/issue #, if applicable: rdar://87744339
This disables `testNavigationTreeLargeDumpAndReadAsync` which is creating some noise on the Swift CI for Linux:
https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/5230/
n/a
n/a
=> Disable testNavigationTreeLargeDumpAndReadAsync

Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
- **Rationale:** This disables a flaky test. The reason for wanting this on the 5.6 branch is to avoid disrupting other work with flaky tests in Swift CI.
- **Risk Detail:** This only disables a flaky test.
- **Reward Details:** Cherry-picking this change avoids potential test failures for other projects in Swift CI that build the full toolchain.
- **Original PR:** #70
- **Issue:**  rdar://87744339 
- **Testing Details:** This is only a test change.
=> [5.6] Disable testNavigationTreeLargeDumpAndReadAsync 

Sources/SwiftDocCUtilities/SwiftDocCUtilities.docc/SwiftDocCUtilities/Extensions/Docc.md
Very minor update - noticed a DocC warning building the internal documentation for DocC itself, so I dug around and it looks like a type was renamed but the update missed in the internal docs.
none
Steps:
1. open Package.swift in Xcode with commit prior to this
2. Build Documentation, note warning
3. Update code, repeat build process.
I didn't see any existing tests verifying that the internal docs build without warning, so I thought this minor change was likely appropriate without tests.
=> fixing symbol in internal docs

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://87552238
This fixed an incorrect warning when a tutorial references an article that's automatically curated. 
Because the article isn't registered yet when the tutorial resolves its references, this always raises a warning about the unresolved reference, but during rendering the reference may still resolve.
n/a
In a documentation catalog with som tutorial content and wit symbol graph files from a single module;
- Add a new article without curating it
- Reference that article from some tutorial content.
There shouldn't be a warning about the article reference failing to resolve (and when viewing that tutorial page.
> Note that these changes only affect the warning. Even without these changes the reference may still resolve during rendering and display the …
=> Fix incorrect warning when tutorial content references an article

Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
=> [Test] Disable a flaky test

Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Comments out code after an XCTSkip call in `OutOfProcessReferenceResolverTests.testForwardsErrorOutputProcess` to avoid an unreachable code warning.
None.
N/A, no functional changes.
=> Fix warning for unreachable code after XCTSkip

Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/PreviewServerTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/AsynchronousExpectationTests.swift
Fixes a small typo in the AsynchronousExpectation test API.
None.
N/A, no functional changes.
=> Fix typo in AsynchronousExpectation test API

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift
Bug/issue #, if applicable: rdar://88464797
Articles that document a module available in multiple languages now inherit that module's languages. This ensures that we generate multiple language variants for article pages.
While investigating the performance impact of this change, I found that the repeated accesses to the `DocumentationContext.rootModules` (a computed property that iterates over all topic graph nodes) was causing a large performance regression. To resolve this, in the second commit I made the property a stored property instead that's initialised once during bundle registration, right after symbols have been loaded in the symbol graph.
No statistically significant impact.
```
Size 10
+-------------------------------------------------------------------------------------------- …
```
=> Emit language variants for articles

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Sources/SwiftDocC/Semantics/Tutorial/Tutorial.swift, Sources/SwiftDocC/Semantics/TutorialArticle/TutorialArticle.swift, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/DocumentationContextGroup.md, Tests/SwiftDocCTests/Indexing/IndexingTests.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/Rendering/DefaultAvailabilityTests.swift, Tests/SwiftDocCTests/Rendering/DefaultCodeListingSyntaxTests.swift, Tests/SwiftDocCTests/Rendering/RenderMetadataTests.swift, Tests/SwiftDocCTests/Rendering/RoleTests.swift
Add `DocumentationContext.documentationExtensionURL(for:)` API to query
a symbol's documentation extension.
None.
No user-facing changes.
=> Add API to query documentation extension URLs

Sources/SwiftDocC/Indexing/IndexJSON/Index.swift, Sources/SwiftDocC/Indexing/Navigator/AvailabilityIndex+Ext.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
Bug/issue #, if applicable: rdar://89093219
Changes made in support of the RenderIndexJSON broke backwards compatibility with existing NavigatorIndex clients. This resolves the regression by adding custom decoding to AvailabilityIndex.InterfaceLanguage.
Confirm unit tests pass and a NavigatorIndex produced with a prior version of DocC is compatible.
=> Make RenderIndex changes backwards compatible

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://87228981
When loading a symbol graph that has no symbols with Objective-C support enabled, we cannot determine what language the module is meant to be used in. This resolves that by falling back to Swift in those cases.
Without this fix DocC crashes due to force-unwraps that assume the module has at least one available language.
None.
Verify that `docc` no longer crashes when building a DocC catalog that contains a symbol graph file with 0 symbols.
=> Fall back to Swift when module has no symbols

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphRelationshipsBuilder.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphRelationshipsBuilderTests.swift
Bug/issue #, if applicable: rdar://80090675
If the super class is in another framework, we can not get a
ResolvedTopicReference to create the inheritsFrom relationship. In this case we
use the targetFallback to populate the render node.
None
Build documentation for a symbol that inherits from a class in another framework and verify that the "Inherits From" section in the generated doccarchive contains the name of the super class.
=> Use targetFallback in inheritsFrom relationships

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex+Ext.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/symbol-graphs/clang/MixedLanguageFramework.symbols.json, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/Test Bundles/MixedLanguageFramework.docc/symbol-graphs/clang/MixedLanguageFramework.symbols.json
Bug/issue #, if applicable: rdar://89418043
For non-Swift languages, make the navigator index generator use `metadata.navigatorTitle`. I filed a separate [issue](https://bugs.swift.org/browse/SR-15947) to track doing this for Swift symbols as well.
None.
When building documentation with an Objective-C symbol graph file that contains symbols with a `names.navigator` entry, verify that the navigator index title reflects the data provided by the symbol graph.
=> Use navigator title for non-Swift languages

Sources/SwiftDocC/Indexing/IndexJSON/Index.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderIndex.spec.json, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift, Tests/SwiftDocCTests/Test Resources/Deprecated.symbols.json, Tests/SwiftDocCTests/Test Resources/TestBundle-RenderIndex.json
Bug/issue #, if applicable: rdar://89564513
Summary
Introduce/change 3 boolean node properties in RenderIndex JSON:
- Change `isExternal` to `external`
- Add `deprecated`. Data for this is generated for render index nodes associated with a symbol. The node is marked as deprecated if we have an explicit deprecated platform version for the associated symbol
- Add `beta` to the RenderIndex JSON OpenAPI spec but doesn't actually generate anything for it.
Dependencies
None
Testing
Build documentation for a project with an explicitly deprecated symbol, and check that the RenderIndex JSON contains a `"deprecated" : true` property for the relevant node.
Checklist
[X]  Added tests
[X]  Ran the ./bin/test …
=> Deprecated symbols sidenav

Sources/SwiftDocC/Converter/RenderNode+Coding.swift, Tests/SwiftDocCTests/Converter/RenderNodeCodableTests.swift, bin/check-source
Bug/issue #, if applicable: n/a
Update the availability check for sorting JSON keys to include all supported platforms.
n/a
Run `docc` with `DOCC_JSON_PRETTYPRINT` enabled on any platforms that supports `.sortedKeys` and observe that the JSON output is sorted.
=> Sort JSON output for any platform that supports it

Sources/SwiftDocC/Model/Identifier.swift, Tests/SwiftDocCTests/Infrastructure/ResolvedTopicReferenceTests.swift
Bug/issue #, if applicable: rdar://89155442
Makes `ResolvedTopicReference.Storage` eagerly initialised. There is a race condition, because `lazy var` is not thread safe.
=> Make ResolvedTopicReference eagerly initialized.

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Variants/VariantCollection+Coding.swift, Sources/SwiftDocC/Model/Rendering/Variants/VariantCollection+Variant.swift, Sources/SwiftDocC/Model/Rendering/Variants/VariantCollection.swift, Sources/SwiftDocC/Model/Rendering/Variants/VariantPatchOperation.swift, Sources/SwiftDocC/Semantics/Article/Article.swift, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift, Tests/SwiftDocCTests/Rendering/Variants/VariantCollection+VariantTests.swift, Tests/SwiftDocCTests/Rendering/Variants/VariantCollectionTests.swift, Tests/SwiftDocCTests/Rendering/Variants/VariantPatchOperationTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/APICollection.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/MixedLanguageFramework.md
Bug/issue #, if applicable: rdar://90159299
As a follow-up to #96, fixes an issue where variants of multi-language articles display APIs that are not available in the language variant. This fix makes DocC only display the APIs available in the language of the currently-selected language. For example, this fix makes DocC omit a Swift-only API from the Objective-C variant of an article that curates it.
I've broken up the changes in three commits:
1. The first commit adds `map` APIs to the `VariantCollection` family of types, to make it easier to update values in variant collections. This functionality is required for the next commit.
2. The actual fix which encodes topics sections on a per-variant basis, and fixes an issue where non-default variants of empty topic sections are encoded as …
=> Filter topics languages in articles

Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/symbol-graphs/clang/MixedLanguageFramework.symbols.json, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/symbol-graphs/swift/MixedLanguageFramework.symbols.json
Bug/issue #, if applicable: rdar://89779283
Automatically curates generated API collections ("Default Implementations" collections) in the language variants the symbol is available in. For API collections that only contain APIs available in a single language, curates the API collection in that language variant of the symbol.
Note: the first commit just removes the `location` field from the fixture clang symbol graph to work around [this](https://bugs.swift.org/browse/SR-15982) SymbolKit bug. This allows to manipulate the symbol graph for testing purposes in the next commit.
None.
Build documentation for a class that conforms to a protocol with default implementations. Verify that the default generated implementations API collection is curated in Swift and Objective-C when the protocol has …
=> Make generated collections multi-language

Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/MixedLanguageFramework.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/symbol-graphs/swift/MixedLanguageFramework.symbols.json
Bug/issue #, if applicable: rdar://90168171
As a follow-up to #103, filters out topics in automatically-generated See Also sections that are not available in the parent's current language.
None.
Build documentation for a mixed-language framework and verify that automatically-generated See Also sections only contain topics that are available in the current language of the parent page.
=> Filter topics languages for automatically-curated See Alsos

README.md, Sources/SwiftDocCUtilities/SwiftDocCUtilities.docc/SwiftDocCUtilities.md, bin/update-gh-pages-documentation-site
This sets the foundation for deploying Swift-DocC's technical documentation to GitHub pages.
After merging this PR, we should be able to prepare a `gh-pages` branch on the main `swift-docc` repo with no content on it, run the `bin/update-gh-pages-documentation-site` script and have docs available.
I've used the included `bin/update-gh-pages-documentation-site` script to deploy to GitHub pages on my fork. Verify the output looks correct here:
- https://ethan-kusters.github.io/swift-docc/documentation/swiftdocc/
- https://ethan-kusters.github.io/swift-docc/documentation/swiftdoccutilities/
=> Publish SwiftDocC's framework documentation to GitHub pages

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/References/ImageReference.swift, Sources/SwiftDocC/Model/Rendering/References/VideoReference.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift, Sources/SwiftDocC/Utility/FoundationExtensions/URL+IsAbsoluteWebURL.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertFileWritingConsumer.swift, Sources/SwiftDocCUtilities/Utility/FoundationExtensions/URL+IsAbsoluteWebURL.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContextTests.swift, Tests/SwiftDocCTests/Utility/URL+IsAbsoluteWebURLTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/URL+IsAbsoluteWebURLTests.swift
Bug/issue #, if applicable: [SR-15839](https://bugs.swift.org/browse/SR-15839)
Forum discussion: https://forums.swift.org/t/can-we-link-and-render-external-images-that-is-from-urls
Add a new ExternalMediaResolver to support external media reference.
None
Test external image and video support in docs and articles.
=> Add external media support in documentation

Sources/SwiftDocC/Indexing/IndexingRecord.swift, Sources/SwiftDocC/Indexing/RenderNode+Indexable.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/IndexingRecords.spec.json, Tests/SwiftDocCTests/Indexing/IndexingTests.swift
Bug/issue #, if applicable: rdar://71214411
This updates the indexing records and their OpenAPI spec to add optional platform availability information to each record.
Doing so enabled consumers of the indexing-records.json digest file to implement for example filtering based on platform availability. Note that the platform information is a type of metadata about the indexing record and not indexable content. 
n/a
For a documentation catalog with symbol graphs files with availability information:
1. Convert the documentation passing `--emit-index`
2. Inspect the indexing-records.json file inside the output documentation archive. 
Any symbol that has platform availability in its page should also contain this information in its indexing record.
Make sure you check off the following items. If …
=> Include platform availability info in indexing records

Sources/SwiftDocCUtilities/Action/Actions/CoverageAction.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift
Bug/issue #, if applicable: rdar://87784021
The test `LogHandleTests.testFlushesStandardOutput()` fails when run outside of Xcode because `stdout` is written to by other tests and types. This was breaking the assumption that `stdout` would be empty when it was written to by the test. This PR removes several print statements from the tests that have no effect on the tests, and changes the `CoverageAction` type to write to a provided log handle rather than print directly to `stdout`. 
None.
Steps:
1. Download the latest [5.6 toolchain snapshot from swift.org](https://www.swift.org/download/#swift-56-development-main).
2. Install the toolchain and `cd </path/to/swift-docc>`
3. Run `xcrun --toolchain org.swift.<toolchain ID> swift test` (i.e. `xcrun --toolchain org.swift.56202203021a  swift …
=> Remove unneeded print statements

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Semantics/SnippetTests.swift
Move the check for a symbol being "snippet-only" to later in the
bundle loading process so that symbol edges are established fully.
rdar://90506525
=> Don't show snippet symbol graph modules as top-level preview sites

Sources/SwiftDocC/Model/SourceLanguage.swift, Sources/SwiftDocC/Semantics/Symbol/DocumentationDataVariants+SymbolGraphSymbol.swift, Sources/SwiftDocC/Semantics/Symbol/DocumentationDataVariants.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Model/SourceLanguageTests.swift, Tests/SwiftDocCTests/Semantics/DocumentationDataVariantsTests.swift
Bug/issue #, if applicable: rdar://90361614
Accept "objective-c" and "c" as interface language identifiers in symbol
graph files emitted by clang.
None.
Build documentation with symbol graph files that use the `objective-c` and `c` interface language identifiers.
=> Accept more Objective-C symbol graph identifiers

Sources/SwiftDocCUtilities/PreviewServer/RequestHandler/FileRequestHandler.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/FileRequestHandlerTests.swift
Bug/issue #, if applicable: rdar://90377550
Updates the `docc preview` CLI tool to support previewing DocC archives that include a RenderIndex JSON.
1. Clone a recent copy of Swift-DocC-Render:
```shell
git clone https://github.com/apple/swift-docc-render-artifact.git
```
2. Enable the Swift-DocC-Render navigator feature flag:
1. Open the [`theme-settings.json`](https://github.com/apple/swift-docc-render-artifact/blob/38aca7c/dist/theme-settings.json#L61) file:
```shell
open /path/to/swift-docc-render-artifact/dist/theme-settings.json
```
2. Set `features.navigator.enable` to `true`.
```json
"features": {
"docs": {
"navigator": {
"enable": true
}
}
```
3. Preview DocC's documentation with your copy of Swift-DocC-Render:
1. Navigate to this repo:
```shell
cd …
```
=> Add support for RenderIndex JSON in `docc preview`

Tests/SwiftDocCUtilitiesTests/PreviewActionIntegrationTests.swift
Bug/issue #, if applicable: rdar://91013719
Disables `SwiftDocCUtilitiesTests.PreviewActionIntegrationTests.testWatchRecoversAfterConversionErrors()`.
=> [Test] Disable testWatchRecoversAfterConversionErrors

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/ArticleCuratedInASingleLanguagePage.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/SwiftOnlyStruct.md
Bug/issue #, if applicable: rdar://90703852
When a Swift+Objective-C page is curated in a Swift-only page, there is nowhere to place the Objective-C version of the page in the Objective-C navigator tree. Rather than arbitrarily curating the Objective-C page right under the "Objective-C" language node, do not curate at all. If the documentation author wants the Objective-C node to be displayed in the Objective-C navigator tree, they can curate the page in a page that is available in Objective-C.
None.
Build documentation for a mixed-language framework that contains an article curated only in a Swift-only node. When building an navigator index, verify that the article doesn't appear in the Objective-C navigator tree.
=> Fix navigator tree curation of multi-language nodes

Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://91106310
This changes how linkable entities are created for landmarks so that the `path` property is encoded like a URL.
n/a
1. In a documentation catalog with tutorial content, add unicode characters to one or more of the tutorial's section's titles.
2. Convert the documentation catalog passing the `--emit-digest` flag
3. Inspect the linkable-entities.json content. 
The entities with unicode characters in their sections should encode the `path` values the same as that portion of the `referenceURL` values.
=> Escape unicode characters in the path values of linkable entities

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolReference.swift, Sources/SwiftDocC/Model/SourceLanguage.swift, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFramework.docc/symbol-graphs/clang/MixedLanguageFramework.symbols.json, Tests/SwiftDocCUtilitiesTests/Test Bundles/MixedLanguageFramework.docc/symbol-graphs/clang/MixedLanguageFramework.symbols.json
Bug/issue #, if applicable: rdar://90143115
For kind-based disambiguation suffixes of links to Objective-C APIs, use the "c" identifier rather than "occ". The "c" identifier is used to represent all C-family languages.
None.
When compiling documentation for a framework that contains link collisions in Objective-C APIs (e.g., a struct called `foo` and a type alias called `Foo`), verify that DocC resolves links to these APIs that a disambiguation suffix that use the `c` identifier (e.g., ` ``Foo-c.typealias`` ` rather than ` ``Foo-occ.typealias`` `)
=> Use "c" rather than "occ" in kind disambiguation suffixes

Sources/SwiftDocC/Model/DocumentationNode.swift
Bug/issue #: [SR-16072](https://bugs.swift.org/browse/SR-16072)
This PR removes the placeholder abstract from `DocumentationNode`. Since the `DocumentationNode` is always overwritten with symbol information the placeholder is unnecessary.
None.
This is just a type change. Functionality remains unchanged. The build & test script both succeeded. There were no additional tests added for this reason as well.
- [N/A] Added tests
- [N/A] Updated documentation if necessary
=> remove placeholder abstract from DocumentationNode

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift, bin/test-data-external-resolver
Bug/issue #, if applicable: rdar://91179282
This preserved the all the source language information that's passed from an external resolver.
n/a
1. Setup docc to run with the test-data-external-resolver
```
export DOCC_LINK_RESOLVER_EXECUTABLE=/path/to/swift-docc/bin/test-data-external-resolver
```
2. Add a couple of external links to some documentation. For example, add this content to a topic section for an existing page:
```
- <doc://com.test.bundle/first-test> 
- <doc://com.test.bundle/second-test>
```
3. Convert the documentation catalog with the external references.
The external references should resolve.
There shouldn't be any errors raised about invalid JSON from the external link resolver script.
Make sure you check off the following items. If they cannot be completed, provide a …
=> Avoid dropping source language information for external content

Sources/DocCDocumentation/DocCDocumentation.docc/footer.html, Sources/SwiftDocC/SwiftDocC.docc/footer.html, Sources/SwiftDocCUtilities/SwiftDocCUtilities.docc/footer.html
Updates the copyright year in the DocC documentation footers.
None.
When building documentation for DocC, verify that the footer contains '2022' as the copyright year.
=> Update copyright year in DocC docs

Sources/DocCDocumentation/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/Shared Directives/Intro.md
Fix a missing space character in the DocC docs.
None.
Build DocC documentation and verify that missing space is no longer present.
=> Fix missing space character in DocC docs

Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json
Bug/issue #, if applicable: rdar://88356862
Remove the `variants` key of render node from the `required` array, since the `variants` key is optional in the Swift model.
None.
N/A
=> Fix Render Node OpenAPI spec for variants key

Sources/SwiftDocC/Benchmark/Metrics/OutputSize.swift, Sources/SwiftDocC/Infrastructure/NodeURLGenerator.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCTests/Benchmark/OutputSizeTests.swift, bin/benchmark-diff.swift
With the introduction of RenderIndex JSON and the prevalence of `--transform-for-static-hosting` it no longer makes sense to only consider the `data` directory when looking for regressions in DocC Archive output size.
I ran into this when attempting to benchmark #121 and noticing that the output size didn't change despite introducing many new files to the archive.
Run the benchmark script and confirm that the output size considers the HTML template and Index.json file.
I'll provide benchmarks here vs the main branch shortly.
=> Consider entire output size when benchmarking

Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json
Bug/issue #, if applicable: rdar://88357075
Allow null values for the TypeDetails keys. This reflects the properties
being optional in the Swift model.
None.
N/A
=> Allow null for TypeDetails keys in OpenAPI spec

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Test Resources/one-symbol-top-level.symbols.json
- **Rationale:** Resolves an issue when using `ConvertService` where link resolution fails in doc comments of top-level symbols.
- **Risk Detail:** This only affects `ConvertService`-based compilation.
- **Reward Details:** This aligns the `docc`-based and `ConvertService`-based compilations.
- **Original PR:** #135
- **Issue:** rdar://91545038
- **Code Reviewed By:** @d-ronnqvist 
- **Testing Details:** Existing tests continue to pass. A test that confirms that links can be resolved in top-level symbol documentation has been added.
=> [5.7] Register references resolved by fallback resolvers

Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
- **Rationale:** Skips a flaky test.
- **Risk Detail:** No user-facing changes.
- **Reward Details:** Reduces spurious test failures
- **Original PR:** #140
- **Issue:** N/A
- **Code Reviewed By:** @daniel-grumberg
- **Testing Details:** Test has been skipped.
=> [5.7] Disable flaky testResolvingTopicLinkProcess test

Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Out of 1000 runs, the `OutOfProcessReferenceResolverTests.testResolvingTopicLinkProcess ` test failed 3 times with:
```
error: -[SwiftDocCUtilitiesTests.OutOfProcessReferenceResolverTests testResolvingTopicLinkProcess] : failed - Unexpectedly failed to resolve reference
```
It also failed here: https://ci.swift.org/job/pr-swift-docc-macos/134/console
N/A
N/A
=> Disable flaky testResolvingTopicLinkProcess test

Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
- **Rationale:** Comments out code after an XCTSkip that I forget to comment out as part of #141, otherwise we get an unreachable code warning.
- **Risk Detail:** Non-functional change.
- **Reward:** Low
- **Reward Details:** Removes a unreachable code warning.
- **Original PR:** #142
- **Issue:** N/A
- **Code Reviewed By:** @daniel-grumberg
- **Testing Details:** Existing tests continue to pass.
=> [5.7] Comment out code after test skip to avoid warning

Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Comments out code after an XCTSkip that I forget to comment out as part of #140, otherwise we get an unreachable code warning.
None.
N/A
=> Comment out code after test skip to avoid warning

Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Sources/SwiftDocC/Model/DocumentationNode.swift
This is a cherry-pick of https://github.com/apple/swift-docc/pull/132 onto `release/5.7`.
**Explanation**: In preparation for updating the way symbol kinds are stored in the symbol graph, this PR changes the way swift-docc matches on that type to use a `default` branch instead of an explicit `case .unknown`.
**Scope**: No effect on user experience.
**Radar**: None, though this is a prerequisite for landing rdar://84276085
**Risk**: Low. This should offer no change to the behavior or test outcomes of Swift-DocC.
**Testing**: Ensure that the behavior of Swift-DocC does not change compared to beforehand.
=> [5.7] use `default` branches for unknown symbol kinds

Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
This adds a fallback value for `ReferenceResolver.title(forNode:)` for externally resolved symbols.
Documentation nodes for external symbols are created with a `.symbol()` style node `Name`, a minimal `Symbol` semantic, but without a `SymbolGraph.Symbol?`. 
See [`OutOfProcessReferenceResolver.entity(with:)`](https://github.com/apple/swift-docc/blob/main/Sources/SwiftDocC/Infrastructure/External%20Data/OutOfProcessReferenceResolver.swift#L158-L184)
Because the node has a symbol name but no SymbolGraph symbol, getting the title via `ReferenceResolver.title(forNode:)` result in `""`. 
If the external content originated from DocC, then its title—which is used to create the externally resolved node's name—is based on the SymbolGraph symbol's name, since the local …
=> Add fallback title for externally resolved symbols

Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
- **Rationale:** Adds logic for providing a fallback title for externally resolved symbols.
- **Risk Detail:** Minor, additive change that's only applicable to externally resoled symbols.
- **Reward:** Low
- **Reward Details:** Node's that represent externally resolved symbols won't resolve to having empty titles.
- **Original PR:** https://github.com/apple/swift-docc/pull/145
- **Issue:** rdar://91714948
- **Testing Details:** Updated unit tests to assert that nodes representing externally resolved symbols don't have empty titles.
=> [5.7] Add fallback title for externally resolved symbols 

Sources/SwiftDocC/Model/Rendering/Symbol/PropertiesRenderSection.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Rendering/RESTSymbolsTests.swift, Tests/SwiftDocCTests/Rendering/Rendering Fixtures/rest-object.json
- **Rationale:** Adds support for a new, additive boolean property in the Render JSON specification.
- **Risk Detail:** Minor, additive change to Swift model and JSON spec
- **Reward Details:** Allows additional clarifying data to be represented for REST object properties
- **Original PR:** https://github.com/apple/swift-docc/pull/134
- **Issue:** rdar://91505904
- **Code Reviewed By:** @franklinsch 
- **Testing Details:** Updated unit tests
=> [5.7] Allow `readOnly` attribute in `TypedProperty` OpenAPI spec

Sources/SwiftDocC/Infrastructure/Diagnostics/Diagnostic.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
This reverts commit ce886e568360d0dfcf649107e01e4a3d8fb88fea.
SwiftCI integration tests have started failing on the 5.7 branch since this landed. Reverting appears to resolve the issue. We should be able to re-merge this after resolving the testing issue.
Radar: rdar://91638258
=> Revert "Transform DocC archives for static hosting by default (#121)

Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://91790147
Removes a confusing error that started being emitted when `docc convert` failed to actually produce documentation for an otherwise valid DocC catalog.
This regression was introduced by the enablement of transform for static hosting by default (https://github.com/apple/swift-docc/pull/121) since that command relies on a `data` subdirectory existing in the produced documentation archive.
This started causing failures in the SwiftCI integration tests because we were building a DocC catalog that didn't produce documentation there. Those integration tests are being updated to be more complete with https://github.com/apple/swift-integration-tests/pull/101 but this will fix the actual cause of the regression there.
Steps:
1. Run `docc convert` on a …
=> Remove confusing error when no docs are produced

Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
- **Rationale:** Addressed a regression where `docc convert` would throw an error upon failing to actually produce documentation for an otherwise valid DocC catalog.
- **Risk Detail:** Minor, targeted change that is covered by a test.
- **Reward Details:** Resolves a regression and avoids potential breakage with DocC's integration into other clients. Unblocks the enablement of `transform-for-static-hosting` by default for the 5.7 release.
- **Original PR:** https://github.com/apple/swift-docc/pull/148
- **Issue:** rdar://91790147
- **Code Reviewed By:** @d-ronnqvist and @talzag 
- **Testing Details:** Added unit tests to ensure that the default behavior of `docc convert` on the command-line does not throw an error in this scenario.
=> [5.7] Remove confusing error when no docs are produced

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/MixedLanguageFramework.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/OriginalSource.h, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/symbol-graph/clang/MixedLanguageFramework.symbols.json, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/symbol-graph/swift/MixedLanguageFramework.symbols.json
- **Rationale:** Fixes an issue where multi-language children of single-language pages are considered as single-language as well, causing them to not be curated in the render node when manually curating them.
- **Risk Detail:** Minor, targeted change that is covered by a test.
- **Reward Details:** This only impacts rare cases where a symbol that's only available in one language has sub-symbols that are available in multiple symbols.
- **Original PR:** https://github.com/apple/swift-docc/pull/139
- **Issue:** rdar://91484878
- **Code Reviewed By:** @ethan-kusters
- **Testing Details:** Added unit tests to ensure that the affected links now resolve, existing tests still pass.
=> [5.7] Fix curation of children of single-language topics

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/MixedLanguageFramework.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/OriginalSource.h, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/symbol-graph/clang/MixedLanguageFramework.symbols.json, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/symbol-graph/swift/MixedLanguageFramework.symbols.json
Bug/issue #, if applicable: rdar://91484878
Fixes an issue where multi-language children of single-language pages are considered as single-language as well, causing them to not be curated in the render node when manually curating them.
This also introduces the `DocumentationContext.sourceLanguages(for:)` API and adds documentation indicating that it should be used to query the available languages of a node instead of checking the reference's source languages. The existing usages of `ResolvedTopicReference.sourceLanguages` have been removed, except when copying `ResolvedTopicReference` values.
None.
Build documentation for an Swift+Objective-C framework that declares an `NS_ERROR_ENUM` type. Curate the error code type into a mixed-language page, and verify that it appears in both the Swift …
=> Fix curation of children of single-language topics

Sources/SwiftDocC/Infrastructure/Diagnostics/Diagnostic.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
Re-nominating #121 for `release/5.7` after this change had to be reverted due to an integration test failure. This change was originially landed on `release/5.7` with #136 and reverted on `release/5.7` with #147.
Original nomination is as follows:
> - **Rationale:** Updates `docc convert` to transform for static hosting by default. Forums discussion [here](https://forums.swift.org/t/supporting-hosting-docc-archives-in-static-environments-like-github-pages-by-default/56524).
> - **Risk:** Low.
> - **Risk Detail:** This enables a feature that has already shipped in Swift 5.6 and is being widely used by default.
> - **Reward:** High
> - **Reward Details:** This change would mean that, by default, a DocC archive can essentially be copied into the root of most server hosts and "just work". 
> …
=> [5.7] Unrevert "Transform DocC archives for static hosting by default"

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Test Resources/Whatsit-Objective-C.symbols.json
This is a cherry-pick of https://github.com/apple/swift-docc/pull/152 onto `release/5.7`.
**Explanation**: A change in SymbolKit (https://github.com/apple/swift-docc-symbolkit/pull/31) is adding new symbol kinds: ivar and macro. This change updates DocC to handle these new symbols and curate them within rendered documentation.
**Scope**: Adds new behavior to load and curate new symbol types. Existing documentation should render with no change in behavior.
**Radar**: rdar://92124246
**Risk**: Low. This is a small enhancement without changing existing behavior for loading and curating symbols.
**Testing**: A new automated test has been added to ensure that the new symbol kinds can be loaded and organized into the documentation hierarchy correctly.
=> [5.7] use new ivar/macro symbol kinds

Package.resolved
Updates cmark-gfm and swift-markdown to their latest versions on the `release/5.7` branch.
This is effectively a non-functional change since SwiftCI ignores the Package.resolved file when building a toolchain but it’s important to keep these up-to-date for local development of Swift-DocC.
=> Update cmark-gfm and swift-markdown to latest versions

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolDisambiguationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/MixedLanguageFramework.md
Bug/issue #, if applicable: rdar://91505520
This fixes a few different issues where disambiguation suffixes for symbol links behave non-deterministically.
- In some cases for symbols with multiple paths it was not fully deterministic which reference would be considered the canonical reference.
- In some cases for collisions between multiple symbols with multiple paths the undisambiguated path would be considered a valid alias for one of the symbols (but it was not deterministic which symbol it applied to).
- In some cases for symbols with parents with multiple paths it would be non-deterministic if the child symbol needed a disambiguation suffix or not.
- Always for symbols with multiple paths each symbol would have _num<sub>paths</sub><sup>2</sup>_ reference aliases instead of …
=> Fix a few issues where disambiguation suffixes for symbol links behave non-deterministically

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolDisambiguationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/MixedLanguageFramework.md
- **Rationale:** Resolves issues where disambiguation suffixes for symbol links would be applied non-deterministically in some cases. This meant that some local symbol links for symbols with name collisions or overloads would sometimes break without making any changes to the documentation content.
- **Risk:** Low - Medium
- **Risk Detail:** This is a targeted fix for symbols with name collisions or overloads. Any change in behavior related to disambiguation suffixes has the risk of breaking links that used to work. This risk is mitigated by adding tests that ensure that previous behaviors remain. Any link that break because of these changes would have previously relied on non-deterministic behavior.
- **Reward Details:** Resolves non-deterministically behavior where …
=> [5.7] Fix a few issues where disambiguation suffixes for symbol links behave non-deterministically 

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md, README.md, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex+Ext.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolReference.swift, Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Sources/SwiftDocC/Model/SourceLanguage.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/DocumentationService/DocumentationServer+DefaultTests.swift, Tests/SwiftDocCTests/Rendering/RoundTripCoding.swift
Bug/issue #, if applicable: https://github.com/apple/swift-docc/issues/231
Updates the README and CONTRIBUTING documents to reflect that Swift-DocC has migrated from bugs.swift.org to GitHub Issues.
Also adds issue templates for bug reports and feature requests.
I think we should migrate to the new [GitHub Issues Forms syntax](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) in the near-future but thought it made sense to get _some_ templates up initially and learned about the new format a little too late. I've filed https://github.com/apple/swift-docc/issues/232 to track this as a future enhancement.
=> Update contributor documentation for GitHub Issues migration

Sources/SwiftDocC/Benchmark/Metrics/Duration.swift, Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/Indexer.swift
Bug/issue #, if applicable: rdar://92584930
This adds a few more benchmark duration metrics to measure the tasks that happen after `DocumentationConverter.convert(outputConsumer:)`.
n/a
This is done separately from https://github.com/apple/swift-docc/pull/159 so that it can be cherry-picked into the 5.7 branch. The other benchmark tool improvements are only intended for the main branch and forward.
Run the benchmark.swift file with convert flags that include `--index`. 
There benchmark output should list the new duration metrics.
- ~Added tests~
- ~Updated documentation if necessary~
=> Add more benchmark duration metrics

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolDisambiguationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkSingleLanguageParent.docc/MixedLanguageFramework.md
- **Rationale:** Resolves issues where disambiguation suffixes for symbol links would be applied non-deterministically in some cases. This meant that some local symbol links for symbols with name collisions or overloads would sometimes break without making any changes to the documentation content.
- **Risk:** Low - Medium
- **Risk Detail:** This is a targeted fix for symbols with name collisions or overloads. Any change in behavior related to disambiguation suffixes has the risk of breaking links that used to work. This risk is mitigated by adding tests that ensure that previous behaviors remain. Any link that break because of these changes would have previously relied on non-deterministic behavior.
- **Reward Details:** Resolves non-deterministically behavior where …
=> [5.7-04252022] Fix a few issues where disambiguation suffixes for symbol links behave non-deterministically

Sources/SwiftDocC/Benchmark/Metrics/Duration.swift, Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/Indexer.swift
- **Rationale:** This adds additional benchmark metrics for the total convert time. Having these on the 5.7-04252022 branch makes it more straight forward to asses the performance improvements of #166 if we want to cherry-pick that into the 5.7-04252022 branch as well. If we don't, then we can skip this cherry-pick. 
- **Risk Detail:** This is a targeted change that only apply when benchmark metrics is gathered.
- **Reward:** Low
- **Reward Details:** Having these metrics on the release/5.7-04252022 branch makes it easier to asses the performance improvements of cherry-picking the #166 changes into the release/5.7-04252022 branch
- **Original PR:** https://github.com/apple/swift-docc/pull/165
- **Issue:** rdar://92584930
- **Testing …
=> [5.7-04252022] Add more benchmark duration metrics (#165)

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/DefaultAvailabilityTests.swift
Bug/issue #, if applicable: rdar://92197472
This fixes a small issue where availability render items was created based on the module's display name instead of the module's symbol name. This resulted in missed default availability items not being rendered after customizing the module's display name.
n/a
With a documentation catalog with default availability specified in the Into.plist (using the `CDAppleDefaultAvailability` key)
- Customize the module's display name with a `@DisplayName` directive in the module's documentation extension file.
- Build documentation for the project and navigate to the module page.
The default availability should be rendered on the module page.
=> Avoid using the module's customized display name when creating availability render items

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeArticleOnlyCatalogTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/TestRenderNodeOutputConsumer.swift
- **Rationale:** Do not emit language variants information for article-only catalogs, so that renderers don't advertise these as being available in "Swift", which not accurate.
- **Risk Detail:** This is a targeted change that only apply when building article-only catalogs.
- **Reward Details:** This only applies to article-only catalogs.
- **Original PR:** #241
- **Issue:** rdar://92758192
- **Testing Details:** Added an automated test to cover the new behavior.
=> [5.7] Do not emit variants for pages in article-only catalogs

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/DefaultAvailabilityTests.swift
- **Rationale:** This fixes a small issue where default availability items wasn't being rendered after customizing the module's display name.
- **Risk Detail:** This is a targeted change that only apply when the developer has customized the module's display name provided default availability for that module.
- **Reward:** Low
- **Reward Details:** The bug only happens when two relatively niche features are used together.
- **Original PR:** #161
- **Issue:** rdar://92197472
- **Testing Details:** Updated existing tests to verify that customizing the display name doesn't impact the availability items
=> [5.7] Avoid using the module's customized display name when creating availability render items (#161)

Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Utility/MarkupExtensions/BlockDirectiveExtensions.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
Rationale: Fixes the issue where diagnostic were added for Doxygen at-commands like @param and @returns, limiting diagnostics to know directives 
Risk: Low
Risk Detail: Minor, targeted change that is covered by a test.
Reward: Medium
Reward Details: This avoid confusing the Doxygen at-commands like @param and @return with DocC-style directives which throws a warning. Limiting this diagnostic so it only throws when it detects a specific directive that is not supported. 
Original PR: https://github.com/apple/swift-docc/pull/154
Issue: rdar://90953916 
Code Reviewed By: @ethan-kusters, @d-ronnqvist 
Testing Details: Added unit tests to ensure that the affected links now resolve, existing tests are pass.
=> [5.7]changes to have diagnostics only for known directives (#154)

Package.resolved, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex+Ext.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorTree.swift, Sources/SwiftDocC/Infrastructure/Bundle Assets/DataAssetManager.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/NodeURLGenerator.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Model/Rendering/References/RenderReference.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertFileWritingConsumer.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/Indexer.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/JSONEncodingRenderNodeWriter.swift, Sources/SwiftDocCUtilities/Action/Actions/CoverageAction.swift, Sources/SwiftDocCUtilities/Action/Actions/TransformForStaticHostingAction.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Options/DirectoryPathOption.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Options/OutOfProcessLinkResolverOption.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Index.swift, Sources/SwiftDocCUtilities/Transformers/StaticHostableTransformer.swift, Sources/SwiftDocCUtilities/Utility/FileManagerProtocol.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/NodeURLGeneratorTests.swift, Tests/SwiftDocCUtilitiesTests/JSONEncodingRenderNodeWriterTests.swift, Tests/SwiftDocCUtilitiesTests/StaticHostableTransformerTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystem.swift
- **Rationale:** Resolves a ~40% performance regression in `docc convert` that was introduced by #121.
- **Risk:** Low/Med
- **Risk Detail:** Touches a large part of the codebase but each change individually is low risk.
- **Reward Details:** Addressees a significant performance regression in Swift-DocC.
- **Original PR:** #166
- **Code Reviewed By:** @d-ronnqvist 
- **Testing Details:** The majority of these changes are intended to be non-functional and covered by existing tests. For the couple of new functions that were added, new unit tests were added. Performance CI was used to confirm the performance regression was fully addressed. Significant manual regression testing was also performed.
=> [5.7] Improve performance of static hosting transformation during conversion

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/DocumentationCurator.swift, Sources/SwiftDocC/Infrastructure/Symbol Link Resolution/AbsoluteSymbolLink.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/ExternalLinks/ExternalMarkupReferenceWalker.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Utility/ValidatedURL.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/PresentationURLGeneratorTests.swift, Tests/SwiftDocCTests/Infrastructure/ResolvedTopicReferenceTests.swift, Tests/SwiftDocCTests/Model/IdentifierTests.swift, Tests/SwiftDocCTests/Semantics/TutorialReferenceTests.swift, Tests/SwiftDocCTests/Utility/ValidatedURLTests.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://93458581
This makes two changes related to doc links to subsections (doc links with fragments):
- Developers can now write links to subsections using characters that aren't allowed in URL fragments without needing to percent escape those characters in the link.
- Punctuation characters in doc links to subsections are now removed from the resolved topic reference fragment. This means that links to subsections written both with and without punctuation will resolve.
None.
In a DocC catalog with at least one article or documentation extension file:
- Add a few headings that contain punctuation characters
- Write links to those articles as `<doc:article-file-name#Heading-name-with-punctuation>`
The doc links to those subsections should resolve both with and …
=> Allow writing doc links to subsections using special characters

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/DocumentationCurator.swift, Sources/SwiftDocC/Infrastructure/Symbol Link Resolution/AbsoluteSymbolLink.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/ExternalLinks/ExternalMarkupReferenceWalker.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Utility/ValidatedURL.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/PresentationURLGeneratorTests.swift, Tests/SwiftDocCTests/Infrastructure/ResolvedTopicReferenceTests.swift, Tests/SwiftDocCTests/Model/IdentifierTests.swift, Tests/SwiftDocCTests/Semantics/TutorialReferenceTests.swift, Tests/SwiftDocCTests/Utility/ValidatedURLTests.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
- **Rationale:** This improves the UX of writing links to on-page subsections when those on-page headings contains apostrophes, punctuation, or special characters. 
- **Risk Detail:** This is a targeted change to how links to on-page headings are written and the URLs those headings get. The heading URL could have a collision if the titles for two or more headings on the same page only differ by punctuation characters but the odds of that are low.
- **Reward Details:** Developers no longer need to write percent encoded links when headings contain punctuation or other special characters that are not allowed in the fragment of a URL. 
- **Original PR:** #262
- **Issue:** rdar://93458581
- **Code Reviewed By:** @franklinsch 
- **Testing Details:** Added …
=> [5.7] Allow writing doc links to subsections using special characters (#262)

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorTree.swift, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/NavigatorIndex/NavigatorIndex.md, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/IndexActionTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/258
This stores a handle to the attributes in the index, the tree, and the
individual nodes. Attributes are stored in a `[String: Any]` and the client is
expected to provided extensions with computed properties as needed.
Additionaly this commits refactors the API for reading a NavigatorIndex from an
on-disk LMDB database. The prveious API used a designated initializer to do
this. However, this initializer was complex as it opened database connections
etc...  Using a static function enables clients to be more resilient to API
changes, by letting them define protocols that specify the new API and providing
a no-op default implementation that delegates to old API. This is not currently
possible with the initializer base API as the …
=> [5.7] Add the ability to add arbitrary attributes to a NavigatorIndex

build-script-helper.py
Bug/issue #, if applicable: #272
Python 2 is no longer supported by the Swift project. This updates the build script helper to use python3.
Confirm that toolchains continue to build on all platforms with the change.
=> Update build script helper to use python3

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeArticleOnlyCatalogTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/TestRenderNodeOutputConsumer.swift
Bug/issue #, if applicable: rdar://92758192
Don't emit variants for article-only catalogs
For article-only catalogs, i.e., catalogs that use `@TechnologyRoot`, don't emit the variants array in the render node, so that renderers don't display the page's language, since it doesn't have a language.
A longer-term fix here would be to not consider articles in article-only catalogs to be "Swift", and implement logic in RenderNodeTranslator to not emit variants information for language-less pages (#240).
> Note: The first commit just moves a test utility so that it can be used in a test introduced by the second commit.
None.
Build documentation for an article-only catalog, and verify that the "Language: Swift" label doesn't appear for any of its pages.
=> Do not emit variants for pages in article-only catalogs

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Identifier.swift, Tests/SwiftDocCTests/Converter/RenderNodeCodableTests.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Model/IdentifierTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://92131596
The caching mechanism in `ResolvedTopicReference` never releases references to the `ResolvedTopicReference`s it holds.
This has likely always been a problem since the introduction of the cache, but is just now appearing as a memory leak when profiling SwiftDocC because we recently added copy-on-write functionality to `ResolvedTopicReference`.
The current solution proposed here is to selectively enable ResolvedTopicReference caching for specific bundle IDs _only_ when running a conversion. This disables the caching by default when (for example) just using SwiftDocC as a library to load RenderNode’s in memory.
There’s more work to do here- but this resolves the immediate issue of caching (and never releasing) every reference when using SwiftDocC …
=> Fix `ResolvedTopicReference` memory leak when not converting

Tests/SwiftDocCTests/Converter/Rewriter/RenderNodeVariantOverridesApplierTests.swift
- **Rationale:** Removes spaces from the bundle identifiers using in Swift-DocC tests to work around a bug in macOS Ventura Beta 1 (94747378).
- **Risk Detail:** Not a user-facing change.
- **Reward Details:** Unblocks test development on macOS Ventura Beta 1 for the affected tests.
- **Original PR:** #288
- **Code Reviewed By:** TBD
- **Testing Details:** N/A, not a user facing change.
=> [5.7] Remove spaces from test bundle identifiers

Tests/SwiftDocCTests/Converter/Rewriter/RenderNodeVariantOverridesApplierTests.swift
Bug/issue #, if applicable: rdar://94811638
Removes spaces from the bundle identifiers using in Swift-DocC tests to work around a bug in macOS Ventura Beta 1 (94747378).
None.
N/A, not a user facing change.
=> Remove spaces from test bundle identifiers

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/FirstCurationRoot.md, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/MultiCuratedSubtree.md, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/MultiCuratedSubtree.symbols.json, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/SecondCurationRoot.md
This performs a BFS traversal of multicurated pages to properly add references
to them in all the copied parents.
rdar://94798570
=> Ensure that children of multicurated pages get properly multicurated as well

Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/JSONEncodingRenderNodeWriter.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://94311195
Addresses a regression introduced by #166 where `docc convert` would throw an error when writing multiple `index.html` files to the same location on disk.
This can occur if docc is writing to an output directory that already contains built documentation or when docc is given bad input such that multiple documentation pages have the same path on the filesystem.
There's some additional changes here ([ecc2774](https://github.com/apple/swift-docc/pull/277/commits/ecc2774c9f13526db2c315db2613244d7812061c)) to fix an issue with the diagnostic that was thrown when we found this issue:
```
DocC.symbols.json: error: “index.html” couldn’t be copied to “docc” because an item with the same name already exists.
```
The diagnostic was incorrectly associated …
=> Fix error when writing multiple index.html files to the same location

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphRelationshipsBuilder.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphRelationshipsBuilderTests.swift
Cherry pick of #280 for swift-5.7 release.
Rationale: Swift-Docc currently does not deal with `optionalRequirementOf` for edge-kind.
Risk: Low
Risk Detail: Add optionalRequirementOf builder.
Reward: Medium
Reward Details: Fix a known bug about optional protocol requirement in swift-5.7 toolchain.
Original PR: #280 
Code Reviewed By:@franklinsch
Testing Details: Add unit test to test isRequired property when building optionalRequirementOf builder.
=> [5.7] Add optionalRequirementOf builder

Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Test Resources/FancyProtocol.symbols.json
Bug/issue #, if applicable: rdar://93203894
Symbols for operator functions that include multiple dots (e.g. the
ClosedRange `...` operator) are currently curated into an unnamed
"Implementations" section due to improper string splitting behavior.
This enhances the detection two ways:
1. For symbols where the "source origin" is available in our given
symbol graphs, it loads the name information from the parent symbol.
2. For symbols where the "source origin" is not available, it improved
the string splitting behavior by dropping empty-string components
before reading names from it.
This allows Comparable and Equatable implementations to curate their
inherited operators properly.
None
Steps:
1. Generate documentation for a module which includes a conformance to Comparable.
2. Ensure that …
=> improve detection for inherited symbol references

Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Test Resources/FancyProtocol.symbols.json
Cherry-pick of https://github.com/apple/swift-docc/pull/257
Explanation: Symbols from ellipsis-style operators (e.g. the `...` operator from `Equatable`) are currently improperly sorted into an unnamed "Implementations" page. This PR enhances the default implementations curation by attempting to look up a symbol's `sourceOrigin` information, or discarding empty-string components in the symbol name if it fails to look up.
Scope: Affects rendering documentation for Swift symbols with Equatable conformances. The fix should allow affected symbols both in the same module and from other modules to get correct default-implementation pages.
Radar: rdar://93203894
Risk: Low. The curation of "default implementations" sections will fall back to organizing the symbols directly into the parent's page …
=> [5.7] improve detection for inherited symbol references

Sources/SwiftDocCUtilities/Action/Actions/Convert/JSONEncodingRenderNodeWriter.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
- **Bug/issue:** rdar://94311195
- **Rationale:** Addresses a regression where `docc convert` would throw an error when writing multiple `index.html` files to the same location on disk. This can occur if docc is writing to an output directory that already contains built documentation or because when docc is given bad input such that multiple documentation pages have the same path on the filesystem.
- **Risk Detail:** Isolated and targeted fix to correctly handle the error that's thrown when an `index.html` file is written to a location that already contains one.
- **Reward:** Med/High
- **Reward Details:** Resolves a regression.
- **Original PR:** #277
- **Code Reviewed By:** @franklinsch 
- **Testing Details:** Unit test added that creates a DocC catalog with multiple …
=> [5.7] Fix error when writing multiple `index.html` files to the same location

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Test Bundles/TestBundleWithDupMD.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/TestBundleWithDupMD.docc/documentation/overview.md, Tests/SwiftDocCTests/Test Bundles/TestBundleWithDupMD.docc/documentation1/overview.md, Tests/SwiftDocCTests/Test Bundles/TestBundleWithDupMD.docc/overview.md
rdar: //81691423
Currently the behavior is not deterministic when we have multiple files with same names, whether it be tutorial or markdown files having same names. Whenever there are two or more files with same name for a type in catalog only one is picked up and rest gets Diagnostics information that its content is being dropped. The diagnostic information existed but it was always picking one of the files not in a specific order, i.e everytime it was picking a random file. The change addresses the issue by adding a sort to the url of the document, so that the behavior is deterministic, i.e the order in which a file is picked, as well as the rest who's content is ignored. 
No Known dependencies 
Steps:
1. Create a project in Xcode, it can be a swift project
2.  Create .docc folder in …
=> Deterministic behaviour when a catalog has colliding filename

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Test Bundles/TestBundleWithDupMD.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/TestBundleWithDupMD.docc/documentation/overview.md, Tests/SwiftDocCTests/Test Bundles/TestBundleWithDupMD.docc/documentation1/overview.md, Tests/SwiftDocCTests/Test Bundles/TestBundleWithDupMD.docc/overview.md
Rationale: Whenever there are two or more files with same name for a type in catalog only one is picked up randomly and rest gets Diagnostics information that its content is being dropped. The change addresses the issue by adding a sort to the url of the document, so that the behavior is deterministic, i.e the order in which a file is picked, as well as the rest who's content is ignored.
Risk: Low
Risk Detail: Minor, targeted change that is covered by a test.
Reward: Medium
Reward Details: This avoid the uncertainty regarding which file's content would be dropped when there is colliding filename. 
Original PR: https://github.com/apple/swift-docc/pull/286
Issue: rdar: //81691423
Code Reviewed By: @ethan-kusters, @franklinsch 
Testing Details: Added unit tests to ensure the behavior is …
=> [5.7] Deterministic behaviour when a catalog has colliding filename (#286)

Sources/SwiftDocC/Checker/Checkers/NonInclusiveLanguageChecker.swift, Tests/SwiftDocCTests/Checker/Checkers/NonInclusiveLanguageCheckerTests.swift
Rationale: Whenever there are multiple spaces in inclusive language diagnostic were missing, the fix here addresses that by updating the regex to catch multiple spaces. .
Risk: Low
Risk Detail: Minor, targeted change that is covered by a test.
Reward: Medium
Reward Details: Highlight non inclusive language even when are spaces in them. 
Original PR: https://github.com/apple/swift-docc/pull/302
Issue: rdar://75552499
Code Reviewed By: @ethan-kusters, @franklinsch
Testing Details: Added unit tests to ensure diagnostic information is added when there are multiple spaces in non inclusive language.
=> [5.7] NonInclusiveLanguageChecker to flag words with multiple spaces (#302)

Sources/SwiftDocC/Checker/Checkers/AbstractContainsFormattedTextOnly.swift, Sources/SwiftDocC/Checker/Checkers/MissingAbstract.swift, Sources/SwiftDocC/Infrastructure/Diagnostics/Diagnostic.swift, Tests/SwiftDocCTests/Checker/Checkers/AbstractContainsFormattedTextOnlyTests.swift
Rationale: At some places usage of the term abstract was not clear in the diagnostic. The change addresses this issue by making it consistent to use 'summary' everywhere .
Risk: Low
Risk Detail: Minor, targeted change that is covered by a test.
Reward: Medium
Reward Details: 
Original PR: https://github.com/apple/swift-docc/pull/310
Issue: rdar://78015631
Code Reviewed By: @franklinsch
Testing Details: Updated unit tests to ensure diagnostic information contains the term 'summary' and not 'abstract'
=> [5.7] fix for replacing the term abstract with summary in diagnostic (#310)

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphRelationshipsBuilder.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
- **Rationale:** This is—together with the two other parts—fix an issue where documentation comments that are inherited from other modules may raise non-actionable warnings if the original documentation comment linked to other symbols in that module.
- **Risk Detail:** This uses the new API from https://github.com/apple/swift-docc-symbolkit/pull/43 to more reliably determine if inherited documentation comments originate from another module or from the current module.
- **Reward Details:** Documentation builds successfully but documentation for protocol conformance symbols from other modules may render with broken links to symbols.
- **Original PR:** #314 
- **Issue:** rdar://92185538
- **Code Reviewed By:** @QuietMisdreavus 
- **Testing Details:** See …
=> [5.7] Check the module name to know when to skip inherited doc comments.

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Test Resources/InheritedDefaultImplementations.symbols.json, Tests/SwiftDocCTests/Test Resources/InheritedDefaultImplementations@Swift.symbols.json, Tests/SwiftDocCTests/Test Resources/InheritedDefaultImplementationsFromExternalModule.symbols.json
Bug/issue #, if applicable: rdar://95808950
With the recent fix for supporting generated implementation sections for
symbols that include periods (like `Comparable...<`) (#257), we introduced a
regression where it's possible to end up with a duplicate default
implementation section.
This can happen when a protocol has a mix of documentation coverage. For example
```swift
public protocol Foo {
/// This is my great doc.
func fooMemberWithDocComment()
func fooMemberWithoutDocComment()
}
public extension Foo {
func fooMemberWithDocComment() { }
func fooMemberWithoutDocComment() { }
}
public struct Bar: Foo {}
```
Here `Bar` would end up with two "Foo Implementations" sections.
This is because we're able to access the original parent symbol for
`fooMemberWithDocComment()` but not for …
=> Fix regression with duplicated generated implementation sections

Tests/signal-test-app/main.swift
Bug/issue #: rdar://90715477
Thread sanitizer doesn't handle `SIGINT` properly, and this causes the
signal-test-app to hang when tests are run under TSan. Sending `SIGABRT`
causes signal-test-app to exit under all circumstances.
None
Steps:
1. Open the package in Xcode
2. Select the SwiftDocC-Package scheme
3. Select Product > Scheme > Edit Scheme...
4. Select the Test row on the left side of the scheme editor window
5. Select the Diagnostics tab
6. Turn on the Thread Santizier
7. Select Product > Test
8. Verify that the tests complete, specifically that `SignalTests.testTrappingSignal()` doesn't hang.
Alternatively, run `xcrun swift test --sanitize thread` and verify that the test run completes.
=> Send SIGABRT to signal-test-app

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Test Resources/InheritedDefaultImplementations.symbols.json, Tests/SwiftDocCTests/Test Resources/InheritedDefaultImplementations@Swift.symbols.json, Tests/SwiftDocCTests/Test Resources/InheritedDefaultImplementationsFromExternalModule.symbols.json
- **Explanation**: Resolves a regression where auto-generated "Protocol Implementations" API collections could be duplicated on a page.
- **Scope**: Affects documentation for symbols that conform to protocls with mixed documentation coverage (some documented members and some undocumented)
- **Bug**: rdar://95808950
- **Original PR**: #321 
- **Risk**: Low. Targeted fix.
- **Testing**: Regression testing and specific testing for auto-generated protocol conformance has been performed.
- **Reviewers**: @d-ronnqvist @QuietMisdreavus
=> [5.7] Fix regression with duplicated generated implementation sections

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift
Bug/issue #, if applicable: rdar://95882462
Resolves a regression introduced by #304 where auto-generated "Protocol Implementations" collections were being duplicated per platform.
The immediate fix is to call the `createInheritedSymbolsAPICollection` method a single time with all of the relevant relationships, instead of once per platform. It tracks internal state while building up the API collections so it's important to provide all possible relationships when calling the method.
I think there's a likely a longer-term fix we should make here in the way we're handling multi-platform symbol graph information since currently we're handling it similarly to multi-language symbol graph information but don't actually emit variants for it.
Build documentation for multiple platforms, save the …
=> Stop duplicating auto-generated collections per-platform

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift
- **Explanation**: Resolves a regression where auto-generated "Protocol Implementations"
collections were being duplicated per platform.
- **Scope**: Affects documentation builds that include symbol graphs from multiple platforms.
- **Bug/issue #**: rdar://95882462
- **Original PR**: #325 
- **Risk**: Low. Targeted fix.
- **Testing**: A test has been added to confirm auto-generated protocol implementations sections are correct for multi-platform builds.
- **Reviewer**: @QuietMisdreavus
=> [5.7] Stop duplicating auto-generated collections per-platform

Package.resolved, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Utility/MarkupExtensions/ListItemExtractor.swift, Tests/SwiftDocCTests/Indexing/IndexingTests.swift, Tests/SwiftDocCTests/Model/RenderNodeSerializationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/RenderBlockContent+AsideStyleTests.swift
Bug/issue #, if applicable: rdar://65856948
Adds support for emitting custom aside titles in render json.
https://github.com/apple/swift-markdown/pull/60
```markdown
> Custom: This is a custom aside title.
```
Steps:
1. Build documentation for a DocC catalog that contains the above markdown.
2. Verify that the rendered output displays the custom title.
=> Add support for custom aside titles

Package.resolved, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Utility/MarkupExtensions/ListItemExtractor.swift, Tests/SwiftDocCTests/Indexing/IndexingTests.swift, Tests/SwiftDocCTests/Model/RenderNodeSerializationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/RenderBlockContent+AsideStyleTests.swift
- **Explanation**: Fixes a bug where custom aside titles aren't recognized by `swift-docc`.
- **Scope**: API breaking change, but doesn't break markdown parsing.
- **Radar Issue**: rdar://65856948
- **Risk**: Low
- **Testing**: Updated existing test suite and added additional tests. Tested manually that custom aside titles are parsed by `swift-docc`.
- **Reviewer**: @franklinsch
=> [5.7] Add support for custom aside titles

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift
Bug/issue #, if applicable: rdar://92127060
When a symbol that's available in Swift and Objective-C whose Objective-C variant doesn't have topics, relationships, or See Also sections, the Objective-C documentation page inherits the topics, relationships, and See Also information of the Swift symbol, which is incorrect. This PR resolves the issue by not emitting Topics, Relationships, and See Also sections for those cases.
The work is split into three commits:
1. Do not emit relationship sections for variants with no relationships: when an Objective-C symbol has no relationships, do not emit relationships, instead of defaulting to the Swift variant's relationships.
2. Do not emit topics section for variants that don't have topics: if the Objective-C version of a symbol doesn't have topics, …
=> Fix Topics, Relationships, and See Also sections of multi-language symbols that don't have them

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift
- **Explanation**: Fixes an issue where Objective-C variants of symbol pages are showing information specific to the Swift variant. See #318 for more details.
- **Scope**: DocC multi-language render JSON generation
- **Radar**: rdar://92127060
- **Risk**: Low
- **Testing**: Automated testing, manual testing
=> [5.7] Fix Topics, Relationships, and See Also sections of multi-language symbols that don't have them

Package.resolved, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
Bug/issue #, if applicable: rdar://96216773
When https://github.com/apple/swift-docc/pull/314 was added, it didn't include all the relevant changes to SymbolKit. Specifically, it didn't include https://github.com/apple/swift-docc-symbolkit/pull/44, which handles decoding ill-formatted URLs that include unescaped spaces. This caused a failure when building documentation for swift-argument-parser, which uses spaces in its source directories.
I've also added tests that ensure that doc comment file paths that include spaces in the JSON properly decode without error.
None (the relevant change has already been merged)
Build documentation with symbol graphs that use spaces in their file names, e.g. [swift-argument-parser](https://github.com/apple/swift-argument-parser).
Steps:
1. Clone …
=> update SymbolKit to include apple/swift-docc-symbolkit#44

Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
- **Explanation**: Adds tests to ensure that doc comments whose filename include spaces can still properly parse.
- **Scope**: No change to behavior (this already worked on the release branch)
- **Radar**: rdar://96216773 (the commit is not tagged with it since the issue was wholly on the `main` branch)
- **Risk**: None. This is only an update to tests.
- **Testing**: Ensure that automated tests pass.
- **Original PR**: https://github.com/apple/swift-docc/pull/326 (This only includes the tests from that PR; the SymbolKit change is already present on this branch)
- **Reviewer**: @franklinsch (He hasn't reviewed the original PR, but we chatted offline while i was working on it)
=> update doc-comment file-path tests to include paths with spaces

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Tests/SwiftDocCTests/Rendering/RenderMetadataTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift, Tests/SwiftDocCTests/Test Resources/BaseKit.symbols.json, Tests/SwiftDocCTests/Test Resources/_OverlayTest_BaseKit@BaseKit.symbols.json
Bug/issue #, if applicable: rdar://94736726
Swift symbol graphs format the file names of cross-import overlays as if they were extension symbol graphs: `_OverlayModule@DeclaringModule.symbols.json`. However, if that overlay *also* declares some extensions, an extension symbol graph is also emitted: `_OverlayModule@SomeOtherModule.symbols.json`. In both cases, SymbolKit and Swift-DocC overwrite the symbol graph's module name with the name after the `@` in the file name. This creates a situation for cross-import overlays which declare extensions where the rendered module name is incorrect.
This PR changes how module information is loaded to preserve the parsed module name in the symbol graph if it indicates that it is from a cross-import overlay (i.e. it declares a "bystander" module). It …
=> load cross-import overlay module data, even for extensions

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Tests/SwiftDocCTests/Rendering/RenderMetadataTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift, Tests/SwiftDocCTests/Test Resources/BaseKit.symbols.json, Tests/SwiftDocCTests/Test Resources/_OverlayTest_BaseKit@BaseKit.symbols.json
- **Explanation**: Swift-DocC doesn't properly handle symbols from cross-import overlay modules which are also extensions of a different module. This change provides some special-casing for cross-import overlay modules to preserve their original module information.
- **Scope**: Module API has been kept stable, and features have been enhanced for cross-import overlay documentation.
- **Issue**: rdar://94736726
- **Risk**: Low. Documentation for regular modules should be unaffected; any changes will only affect cross-import overlays.
- **Testing**: See instructions on https://github.com/apple/swift-docc/pull/332
- **Reviewer**: @franklinsch 
Note that this PR requires https://github.com/apple/swift-docc-symbolkit/pull/47, and should be updated once that PR is merged.
=> [5.7] load cross-import overlay module data, even for extensions

Sources/SwiftDocC/Infrastructure/DocumentationBundle.swift, Sources/SwiftDocC/Infrastructure/DocumentationBundleFileTypes.swift, Sources/SwiftDocC/Infrastructure/Workspace/DataProviderBundleDiscovery.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertFileWritingConsumer.swift, Tests/SwiftDocCTests/Infrastructure/BundleDiscoveryTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationBundleFileTypesTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: #336 
If a documentation catalog contains a `theme-settings.json` file, DocC will now include this file in the compiled output, alongside the JSON data and static renderer assets.
If a default `theme-settings.json` file is already provided by the renderer, the file provided by the catalog will take precedence.
This is the minimal DocC implementation work needed to support the proposal described in the [Customizing the look and feel of Swift-DocC-Render](https://forums.swift.org/t/customizing-the-look-and-feel-of-swift-docc-render/58858) forum post.
There are no explicit dependencies for this PR since DocC-Render already has some (minimal) support for the presence of this file in the output, however future PRs for DocC-Render will enhance these capabilities and …
=> Include user provided `theme-settings.json` file in compiled output

Sources/SwiftDocC/Model/DocumentationMarkup.swift, Sources/SwiftDocC/Semantics/Article/Article.swift, Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift
Bug/issue #, if applicable:
Close #344  
Steps:
1. Create a Swift Package and add documentation2. 
2. In a Article file, add the following text: 
```
Line b
Test
```
3. Compile the package and get the symbol-graph path. 
4. Run `swift-docc preview xx/DemoKit.docc --additional-symbol-graph-dir xx/DemoKit.build/symbol-graph` to see the effect
=> Fix article abstract section issue

Package.resolved, Package.swift
Accidentally committed temporary branch point on SymbolKit in the manifest. This PR moves it back to `release/5.7`.
=> Restore SymbolKit branch to release/5.7

Tests/SwiftDocCUtilitiesTests/PreviewServer/PreviewHTTPHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/DefaultRequestHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/ErrorRequestHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/FileRequestHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/ServerTestUtils.swift
Bug/issue #, if applicable: rdar://95878818
The `testMalformedPath` used a URL that wasn't actually invalid per the URL specification. This made the test incorrectly fail when running using macOS Ventura Beta. This updates the test to make it use a URL that's actually invalid, and updates the `makeRequestHead`'s `path` parameter to `uri`, since that's what it represents.
None.
N/A
=> Update testMalformedPath to make it use an actually invalid URL

Sources/SwiftDocC/Converter/DocumentationContextConverter.swift, Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/RenderMetadata.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/SourceRepository/SourceRepository.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Sources/SwiftDocC/Utility/FoundationExtensions/String+Path.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Options/Source Repository/SourceRepositoryArguments.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeSourceRepositoryTests.swift, Tests/SwiftDocCTests/SourceRepository/SourceRepositoryTests.swift, Tests/SwiftDocCTests/Test Bundles/SourceLocations.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/SourceLocations.docc/symbol-graph/swift/TestFrameworkWithSourceLocations.symbols.json, Tests/SwiftDocCTests/TestRenderNodeOutputConsumer.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandSourceRepositoryTests.swift
Bug/issue #, if applicable: #186, rdar://88537303
Adds command-line arguments to configure a repo URL so that documentation websites can display a link to the symbol's declaration in the repo.
Example invocation:
```
swift package generate-documentation \
--source-service github \
--source-service-base-url https://github.com/<org>/<repo>/blob/main \
--checkout-path <path to local checkout>
```
https://github.com/apple/swift-docc-render/pull/366
Set the `DOCC_EXEC` environment variable to a local build of DocC from this branch and run with the flags described above. Verify that documentation pages for Swift symbols contains a `.metadata.source` field that links to the symbol's declaration in the git service.
=> Emit symbol URL to link to declaration in repo

build-script-helper.py
* Use `python3` in build-script-helper
Python2 is no longer supported by the Swift project.
* Remove unused variable from build script
`output_dir` is written to but never used.
(cherry picked from commit 41f116f72cd3cf6392c2f82d7b72ed3c5ccb735a)
=> [5.7] Update build script helper to use python3

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolReference.swift, Tests/SwiftDocCTests/Infrastructure/SymbolReferenceTests.swift
DocC currently has a set of 'known' programming languages for which it has display names, and loading symbol graphs currently requires the symbols' language to be known by DocC. There's no reason to not process allow processing symbols of unknown language though, and this fix makes DocC more flexible in that respect. The end-to-end compilation flow works fine with the change.
N/A
Build documentation for a symbol graph with an unknown language, e.g., by taking an existing Swift compiler symbol graph and replacing the 'swift' language with 'unknown-language'.
=> Allow processing symbol graphs of unknown languages

README.md, Sources/SwiftDocCUtilities/ArgumentParsing/Options/PreviewOptions.swift, Tests/SwiftDocCUtilitiesTests/PreviewActionIntegrationTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/LogHandleTests.swift
Close #371 
Source: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http
Thanks @amartini51 for providing the source explanation
Update default preview server port
=> Update default preview server port

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://91678333 rdar://88498898
This fixes two flaky OutOfProcessReferenceResolver tests. 
59a4e20dfb694560fd062c618fdb07aa9eeaecea fixes a bug where the resolver would fail to decode the response if it hadn't received the full response yet (since the JSON would be incomplete and therefore not decodable).
With these changes `testForwardsErrorOutputProcess` got less flaky but still consistently failed after about 3100-3200 iterations. I think this failure new failure could be because of a leaked file descriptor. e68b809c05ef23d38c1cb7f0f455cb0e9d6824a9 updates the error output pipe to be processed on the main thread and updates the test to 
- Use the built in XCTestExpectation (since this is a macOS only test)
- Create the resolver inline in the test without …
=> Fix two flakyOutOfProcessReferenceResolver tests

Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift
Bug/issue #, if applicable: none
This removes the deprecated `path` properties on `LinkDestinationSummary` and `LinkDestinationSummary/Variant`. 
Doing this gets rid of a handful of deprecation warnings that add noise when running the tests. 
n/a
n/a
=> Remove deprecated path properties

Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticEngine.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticEngineTests.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Close #363 
Add a new flag "--warnings-as-errors" for "docc convert" Command.
If this flag is set, the engine will treat the warning severity level as an error severity level
Forum discussion post: https://forums.swift.org/t/add-support-for-warnings-as-errors/59832
None
1. `git clone https://github.com/apple/swift-markdown.git`
2. Generate `swift-markdown`'s symbol-graph
3. Run 
```
docc convert swift-markdown/Sources/Markdown/Markdown.docc`
--fallback-display-name SwiftDocC
--fallback-bundle-identifier org.swift.SwiftDocC 
--fallback-bundle-version 1.0.0
--additional-symbol-graph-dir xx/swift-markdown.build/Debug/Markdown.build/symbol-graph
```
and see a list of warnings.
4. Run 
```
docc convert swift-markdown/Sources/Markdown/Markdown.docc` …
```
=> Add support for "warnings as errors"

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Indexing/IndexingTests.swift
[rdar://93177278](rdar://93177278)
This PR updates the symbol page layout so that the **Return Value** section always follows the **Parameters** section (if there is one), which results in a more logical and ergonomic flow for the reader (declaration ~> parameters ~> return value ~> discussion).
N/A.
The existing test suite has been updated to account for this change.
=> Changes to the symbol page content layout

Sources/SwiftDocC/Indexing/RenderBlockContent+TextIndexing.swift, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveIndex.swift, Sources/SwiftDocC/Semantics/Reference/Small.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/Reference/RowTests.swift, Tests/SwiftDocCTests/Semantics/Reference/SmallTests.swift, Tests/SwiftDocCTests/Test Bundles/BookLikeContent.docc/MyArticle.md, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
Bug/issue #, if applicable: rdar://97744845
Adds support for the `@Small` directive as described here: https://forums.swift.org/t/supporting-more-dynamic-content-in-swift-docc-reference-documentation/59527#small-18
A new `@Small` directive based on HTML’s small tag. This directive can be used to specify small print like legal, license, or copyright text that should be rendered in a smaller font size.
`@Small` accepts no parameters and accepts arbitrary DocC markup body content.
Example:
You can create a sloth using the ``init(name:color:power:)``
initializer, or create randomly generated sloth using a
``SlothGenerator``:
let slothGenerator = MySlothGenerator(seed: randomSeed())
let habitat = Habitat(isHumid: false, isWarm: true)
// ...
@Small {
Licensed under Apache License v2.0 with …
=> Add support for @Small directive

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/NodeURLGenerator.swift
Cleans up all references to the `”documentation”` and `”tutorial`”’ subpaths to be driven by the property in `NodeURLGenerator`.
This is a pure refactor and a non-functional change. Confirm that DocC continues to behave as it did before.
=> chore: /documentation subpath should be driven by property

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Extensions/KindIdentifier+Curation.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Test Resources/TypeSubscript.symbols.json
Bug/issue #, if applicable: rdar://99921042
Currently, we don't curate static subscript symbols in the automatic curation logic. In Xcode, this causes the symbol to "fall out" of curation, appearing at the top level alongside the package itself. This PR adds "type subscripts" to the automatic curation listing, so that these symbols can be properly displayed.
None
The following Swift code will trigger this bug:
```swift
public struct SomeStruct {
public static subscript(_ idx: Int) -> Int {
idx
}
}
```
Steps:
1. Build documentation for a package containing the above code.
2. Ensure that the `static subscript(Int) -> Int` symbol is correctly organized underneath `SomeStruct`.
- [ n/a ] Updated …
=> curate type-subscript symbols in automatic curation

Package.resolved, Package.swift, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Model/RenderContentMetadataTests.swift
Bug/issue #, if applicable: rdar://98017880
This PR loads the new Markdown support for row- and column- span in tables and emits it in Render JSON. For more information about the Markdown syntax, see the swift-cmark PR linked below.
- https://github.com/apple/swift-cmark/pull/46 (already merged)
- https://github.com/apple/swift-markdown/pull/74
- https://github.com/apple/swift-docc-render/pull/420
Use the following sample Markdown to test the new feature:
```markdown
| one | two | three |
| --- | --- | ----- |
| big      || small |
| ^        || small |
```
Steps:
1. Add the above Markdown to Swift-DocC's top-level article.
2. Build the above-linked Swift-DocC-Render PR and add the resulting `dist` directory to the `DOCC_HTML_DIR` environment variable.
3. `swift run docc preview …
=> Add support for row- and column-span in tables

Sources/SwiftDocC/Indexing/RenderBlockContent+TextIndexing.swift, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveIndex.swift, Sources/SwiftDocC/Semantics/Reference/TabNavigator.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/Reference/TabNavigatorTests.swift, Tests/SwiftDocCTests/Test Bundles/BookLikeContent.docc/MyBook.md, Tests/SwiftDocCTests/Test Bundles/BookLikeContent.docc/TabNavigatorArticle.md, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
Bug/issue #, if applicable: rdar://97739641
Add support for the tab navigator directive as described here: https://forums.swift.org/t/supporting-more-dynamic-content-in-swift-docc-reference-documentation/59527#tabnavigator-14
- https://github.com/apple/swift-docc-render/pull/403
=> Add authoring support for @TabNavigator directive

Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift
Close #377 
Skip comment block link resolution
This will reduce the warning number of swift-book's build documentation from 63 to less than 20.
The remaining issues are:
- https://github.com/apple/swift-book/issues/1
- Actually misused links https://github.com/apple/swift-book/issues/36
eg.
swift-book try to reference `#### Switching Over Future Enumeration Cases` in Statements.md but swift-docc will only create anchor section for H2 and H3 not for H4.
https://github.com/apple/swift-docc/blob/5fe2d1331eba2243163366e4d25259b86a44e5db/Sources/SwiftDocC/Model/DocumentationNode.swift#L113-L124
> Note: If we enable to use hierarchy based link resolver, the warning will also emit the available children for we to look up.
``` …
```
=> Skip comment block link resolution

Sources/SwiftDocC/Infrastructure/Workspace/DataProviderBundleDiscovery.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationBundle+Info.swift, Sources/SwiftDocC/Infrastructure/Workspace/GeneratedDataProvider.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable:  https://github.com/apple/swift-docc/issues/194
We can remove the need to pass `--fallback-...` CLI arguments in most cases. 
A suitable documentation identifier can almost always be derived from the documentation's display name and a suitable documentation display name can almost always be derived from other information in the documentation "bundle".
If a documentation bundle has no specified identifier, derive the identifier from the bundle's display name.
If a documentation bundle has no specified display name:
- and it has symbol graph files about a single module, derive the display name from the module's name
- and it has a DocC catalog, derive the display name from the catalog's filename (without the file extension)
otherwise (if the bundle has no DocC …
=> Remove need to pass --fallback-... CLI arguments in most cases

Sources/SwiftDocC/Indexing/RenderBlockContent+TextIndexing.swift, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/TaskGroup.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveIndex.swift, Sources/SwiftDocC/Semantics/General Purpose Analyses/HasExactlyOne.swift, Sources/SwiftDocC/Semantics/Reference/Links.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/Reference/LinksTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
Bug/issue #, if applicable: rdar://99870352
Adds a new `@Links` directive that allows for authoring embedded previews of documentation links (similar to how links are currently rendered in Topics sections) anywhere on the page without affecting page curation behavior.
`@Links` gives authors flexibility in choosing how they want to highlight documentation on the page itself versus in the navigation sidebar. It also allows for mixing and matching different visual styles of topics.
...
@Links(visualStyle: compactGrid) {
- <doc:get-started-preparing-sloth-food>
- <doc:feeding-your-sloth-in-winter>
- <doc:ordering-food-delivery>
}
...
`@Links` accepts a single `visualStyle` parameter and supports a list of Swift-DocC links as its child content:
- visualStyle: The visual style of the topic …
=> Add authoring support for `@Links` directive

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Sources/SwiftDocC/Model/Section/Sections/GroupedSection.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Test Bundles/AnonymousTopicGroups.docc/AnonymousTopicGroups.md, Tests/SwiftDocCTests/Test Bundles/AnonymousTopicGroups.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/AnonymousTopicGroups.docc/article.md
Bug/issue #, if applicable: rdar://97739538
Forums post: https://forums.swift.org/t/relaxing-structure-requirements-for-topics-sections/60534
Adds support for defining Topics sections without h3 headings, like so:
```md
- ``MySymbol``
```
It's also possible to define subsequent topic groups:
```md
- ``MySymbol``
- ``Another Symbol``
```
- https://github.com/apple/swift-docc-render/pull/443
Define a Topics section without topic groups like shown above. Verify that the links still render on the page, with the appropriate topic group headings if they were specified.
=> Add support for defining Topics sections without topic group headings

Sources/SwiftDocC/Indexing/RenderBlockContent+TextIndexing.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveIndex.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Semantics/Media/ImageMedia.swift, Sources/SwiftDocC/Semantics/Media/VideoMedia.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Sources/SwiftDocC/Semantics/Technology/Volume/Volume.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/ImageMediaTests.swift, Tests/SwiftDocCTests/Semantics/VideoMediaTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
Bug/issue #, if applicable: rdar://97739628
Adds support for using the `@Image` and `@Video` directives from Tutorials
in regular reference documentation. This allows authors to
insert videos into documentation and to create images that have
attached captions.
To that point, the `@Image` and `@Video` directives can now contain
inline text to form a caption.
The final change here is that the `@Video` directive now supports
alt text.
Examples:
@Image(source: "overview-hero.png",
alt: "An illustration of a sleeping sloth.") {
This is a caption adding additional context for the image.
}
@Video(source: "sloth-smiling.mp4",
poster: "happy-sloth-frame.png",
alt: "A short video of a sloth jumping down from a branch.") {
A *happy* sloth. 🦥
}
This change is described on the Swift forums here: …
=> Add @Image and @Video directives to reference documentation with caption support

Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Model/RenderContentMetadataTests.swift
Bug/issue #, if applicable: rdar://77749746
This PR takes the table alignment info from Swift-Markdown and emits it into Render JSON, so that Markdown tables' column alignment information can be reflected in the final rendering.
https://github.com/apple/swift-docc-render/pull/441
Use the following table as test information:
```markdown
| Column One | Column Two | Column Three | Column Four |
| :--------- | ---------: | :----------: | ----------- |
| one        | two        | three        | four        |
```
Steps:
1. Add the above Markdown to `Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC.md`.
2. Clone and build the Swift-DocC-Render PR.
3. `DOCC_HTML_DIR=/path/to/swift-docc-render/dist bin/preview-docs`
4. Ensure that the table's columns have the proper alignment when rendered.
Make sure …
=> emit table column alignments into Render JSON

Package.resolved, Package.swift, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Indexing/IndexingTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Test Bundles/TestBundle.docc/documentation/myprotocol.md
Bug/issue #, if applicable: rdar://73847907
While cmark-gfm saves the starting index for an ordered list, swift-markdown currently discards this information. This PR is part of a set to preserve this starting index when rendering documentation.
https://github.com/apple/swift-markdown/pull/22
Add the following markdown to `Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC.md`:
```markdown
2. this is a test
3. this is a test
```
Steps:
1. Build the associated swift-docc-render branch (https://github.com/apple/swift-docc-render/pull/30) and set `$DOCC_HTML_DIR` to the resulting `dist` directory.
2. `bin/preview-docs`
3. Ensure that the added list correctly starts with the index 2.
=> save custom ordered list start index in render JSON

Sources/SwiftDocC/Model/Rendering/Content/RenderInlineContent.swift, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/RenderingModel/RenderInlineContent.md
This PR contains the following changes:
- Adds the `public` modifier to `plainText` in RenderInlineContent.swift (and the related extension on `Sequence`).
- Adds a markdown extension file that organizes the symbols in `RenderInlineContent`.
=> Make `plainText` publicly accessible

Sources/SwiftDocC/Model/DocumentationNode.swift, Tests/SwiftDocCTests/Model/DocumentationNodeTests.swift
Bug/issue #, if applicable:
Close https://github.com/apple/swift-book/issues/36
Relaxing requirement of anchorSection for headings.
Swift DocC originally only support H2 and H3 for anchor section.
After this MR, it will expand into all non-H1 headings.
See discussion at https://github.com/apple/swift-book/issues/36#issuecomment-1272955489
None
1. See DocumentationNodeTests.swift
2. Screenshots
Before this PR:
After this PR:
=> [Bugfix] Relaxing requirement of anchorSection for headings

build-script-helper.py
Bug/issue #, if applicable: closes #433
Updates the build script used in SwiftCI for building the `docc` executable as part of Swift.org toolchains to support cross compilation.
Currently the `docc` executable included in the otherwise universal macOS toolchain only supports x86_64. This resolves the issue.
=> Support cross compilation in macOS toolchain builds

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift
Bug/issue #, if applicable: rdar://103602701
In https://github.com/apple/swift-docc/pull/435 i made the `sha512Checksum` property of `DownloadReference` optional, since Swift-DocC-Render currently doesn't use that property. However, this caused an API breakage due to the requirement for optional-unwrapping. This PR restores the original non-optional property, but continues to store and encode an optional String in the data structure and in the output JSON.
None
Ensure that no functionality changes.
=> change sha512Checksum back into a non-optional property

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/443
**Explanation**: This PR updates the `sha512Checksum` property of `DownloadReference` back to a non-optional String, since https://github.com/apple/swift-docc/pull/435 introduced a public-API-breaking change.
**Scope**: Affects any users of Swift-DocC as a library, especially those who use the RenderNode model in their own projects.
**Issue**: rdar://103602701
**Risk**: Low. The change is limited to making an optional property non-optional.
**Testing**: Automated tests continue to pass.
=> [5.8] change sha512Checksum back into a non-optional property

Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/LinkableEntities.json, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift
Bug/issue #, if applicable: rdar://103916556
This fixes two bugs in the encoding and decoding of variant values for link destination summaries. 
n/a
It's a bit cumbersome to test this end-to-end to verify that DocC can correctly decode the linkable entities that it encodes. The updated unit tests cover this. 
If we wanted to test it manually we would need to:
- Build multi-source-language documentation and export the linkable entities.
- Create a custom external resolver and use it to return the data from the first build
- Build other documentation which uses the above custom external resolver to return the data from the first build.
=> Fix encoding & decoding inconsistencies for link destination summary variant values

Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/LinkableEntities.json, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/451
- **Explanation**: This fixes two bugs in the encoding and decoding of variant values for link destination summaries (the linkable entities file).
- **Scope**: Multi source-language builds that emit linkable entities (off by default).
- **Radar**: rdar://103279313 (Structure suggestions for link resolution warnings as fixits)
- **Risk**: Low. The linkable entities data is only created when the `--emit-digest` flag is passed and variant values are only created in multi source-language builds.
- **Testing**: New test assertions have been added to ensure that encoded linkable entities with variant values can be decoded. Existing automated tests pass.
=> [5.8] Fix encoding & decoding inconsistencies for link destination summary variant values

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Symbol/AvailabilityRenderMetadataItem.swift, Sources/SwiftDocC/Semantics/Metadata/Availability.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Symbol/PlatformName.swift, Tests/SwiftDocCTests/Rendering/PlatformAvailabilityTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Semantics/MetadataAvailabilityTests.swift, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/AvailableArticle.md, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/ComplexAvailable.md, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/MyClass.md, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/mykit-iOS.symbols.json
Cherry-pick of https://github.com/apple/swift-docc/pull/440
- **Explanation**: This PR adds a new metadata directive, `@Available`, for articles and symbol extensions to specify platform availability information
- **Scope**: New directive for articles and extensions.
- **Radar**: rdar://57847232
- **Risk**: Low. Existing documentation should not be affected.
- **Testing**: New tests have been added to ensure that expected permutations of this attribute provide expected results. Existing automated tests pass.
=> [5.8] add `@Available` directive for setting platform availability

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Symbol/AvailabilityRenderMetadataItem.swift, Sources/SwiftDocC/Semantics/Metadata/Availability.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Symbol/PlatformName.swift, Tests/SwiftDocCTests/Rendering/PlatformAvailabilityTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Semantics/MetadataAvailabilityTests.swift, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/AvailableArticle.md, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/ComplexAvailable.md, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/MyClass.md, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/mykit-iOS.symbols.json
Bug/issue #, if applicable: rdar://57847232
This PR adds a new metadata directive: `@Available`. This can be used in articles and extension files to set platform availability for a documentation page. (When used in an extension, it overrides any information that came from the symbol itself.)
This directive was proposed in this forums thread: https://forums.swift.org/t/setting-a-documentation-article-s-platform-availability/61144
Note that while the thread proposed `isBeta` and `isDeprecated` arguments (and this PR parses them), they are currently not usable because of work that needs to happen in Swift-DocC-Render to support the behavior. The work in Swift-DocC is being tracked in https://github.com/apple/swift-docc/issues/441.
None
Use the following Markdown as a test article: …
=> add `@Available` directive for setting platform availability

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Metadata/PageKind.swift, Tests/SwiftDocCTests/Rendering/PageKindTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MyLocalSample.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MySample.md, bin/check-source
Cherry-pick of https://github.com/apple/swift-docc/pull/457
- **Explanation**: Adds a new metadata directive so that articles can override their "page kind" for the purposes of affecting their navigator icon and title heading. It also includes a change to `bin/check-sources` to allow license headers to reference the year 2023.
- **Scope**: New metadata directive for articles.
- **Issue**: rdar://69902322
- **Risk**: Low. Existing documentation should be unaffected.
- **Testing**: Tests have been added to ensure the directive works as expected. Existing automated tests continue to pass.
=> [5.8] Add `@PageKind` directive to force a page's role/title heading

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Metadata/PageKind.swift, Tests/SwiftDocCTests/Rendering/PageKindTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MyLocalSample.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MySample.md, bin/check-source
Bug/issue #, if applicable: rdar://69902322
This PR adds a new metadata directive, `@PageKind`, which sets a page's role and title heading. Right now this allows articles to force an "Article" title heading or to use the "Sample Code" heading instead.
This directive was originally proposed in this forums thread: https://forums.swift.org/t/supporting-sample-code-pages-in-swift-docc/61143
None
Use the following directive to test:
```markdown
@Metadata {
@PageKind(sampleCode)
}
```
Steps:
1. Add the above directive to an article in the `SwiftDocC.docc` catalog. (For example, i added it to `Concurrency.md`.)
2. `bin/preview-docs`
3. Ensure that the page you edited is marked as "Sample Code" in its page header and in the sidebar navigator:
Make sure you check off the following items. If they …
=> Add `@PageKind` directive to force a page's role/title heading

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/SourceLanguage.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Metadata/SupportedLanguage.swift, Sources/SwiftDocC/Utility/MarkupExtensions/BlockDirectiveExtensions.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Model/SourceLanguageTests.swift, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkWithArticlesUsingSupportedLanguages.docc/ArticleWithoutSupportedLanguages.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkWithArticlesUsingSupportedLanguages.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkWithArticlesUsingSupportedLanguages.docc/MixedLanguageFramework.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkWithArticlesUsingSupportedLanguages.docc/ObjCArticle.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkWithArticlesUsingSupportedLanguages.docc/SwiftAndObjCArticle.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkWithArticlesUsingSupportedLanguages.docc/SwiftArticle.md, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkWithArticlesUsingSupportedLanguages.docc/symbol-graph/clang/MixedLanguageFramework.symbols.json, Tests/SwiftDocCTests/Test Bundles/MixedLanguageFrameworkWithArticlesUsingSupportedLanguages.docc/symbol-graph/swift/MixedLanguageFramework.symbols.json
Bug/issue #, if applicable: rdar://102091191
Pitch: https://forums.swift.org/t/setting-programming-language-availability-for-articles-in-swift-docc/61435
Adds support for the `@SupportedLanguage` directive, which can be used in article files to indicate what languages an article is available in, rather than using the languages that the module being documented is available in.
Note that this feature is not available for symbol documentation. I think it makes sense to bring it to symbols as well as part of a future PR. The `@SupportedLanguage` data would override data from symbol graphs, similar to how the `@Available` directive overrides the symbol graph information. I've filed https://github.com/apple/swift-docc/issues/465 to track this.
None.
Build documentation with articles that use …
=> Add @SupportedLanguage directive for articles

Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Options/AutomaticArticleSubheading.swift, Sources/SwiftDocC/Semantics/Options/AutomaticSeeAlso.swift, Sources/SwiftDocC/Semantics/Options/AutomaticTitleHeading.swift, Sources/SwiftDocC/Semantics/Options/Options.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Semantics/ArticleTests.swift, Tests/SwiftDocCTests/Semantics/Options/OptionsTests.swift
Squash of https://github.com/apple/swift-docc/pull/448
- **Explanation**: This updates the naming convention of "option directives" to match the Forum discussions.
- **Scope**: Documentation using `@Option` directives to disabled various default behaviors. 
- **Radar**: rdar://104437275 
- **Risk**: Low. The syntax to disable default behaviors remain the same. Only redundantly writing out the directives to enable the behavior that's already on by default changed.
- **Testing**: Updated tests to use new directive argument names. Existing automated tests pass.
=> [5.8] Update option directive naming

Sources/SwiftDocC/Model/Rendering/Symbol/AvailabilitySortOrder.swift, Sources/SwiftDocC/Semantics/Metadata/Availability.swift, Sources/SwiftDocC/Semantics/Symbol/PlatformName.swift, Tests/SwiftDocCTests/Rendering/PlatformAvailabilityTests.swift, Tests/SwiftDocCTests/Semantics/MetadataAvailabilityTests.swift, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/ArbitraryPlatforms.md, Tests/SwiftDocCTests/Test Bundles/AvailabilityBundle.docc/AvailableArticle.md
Bug/issue #, if applicable: rdar://104224866
In https://github.com/apple/swift-docc/pull/440, the `@Available` directive was limited to four platforms: `iOS`, `macOS`, `watchOS`, `tvOS`. This PR opens up that directive to take arbitrary platform strings, which will be passed along to the rendered page.
None
Use the following metadata for testing:
```markdown
@Metadata {
@Available("Swift DocC", introduced: "1.0")
}
```
Steps:
1. Add the above metadata to `Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/Directives.md`.
2. `bin/preview-docs`
3. Ensure that the "Directives" page is printed with an availability callout for "Swift DocC" (with the space - i'm specifically testing platforms with spaces here):
=> allow arbitrary platform strings in the `@Available` directive

Package.resolved, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Test Resources/Asides.symbols.json
Bug/issue #, if applicable: rdar://55141543
There’s a lot of existing Swift documentation content that uses
the legacy `- seealso:` style aside:
```md
- SeeAlso: This other content.
```
While Swift-DocC has always supported a number of these legacy asides
like:
```md
- Experiment: Lorem ipsum.
- Tip: Lorem ipsum
```
it doesn’t currently support `SeeAlso` which causes breakage
when migrating existing Swift doc comments over to Swift-DocC.
This resolves the issue.
- https://github.com/apple/swift-markdown/pull/96
Create documentation content with a SeeAlso aside and confirm it renders as expected:
```md
Hi there!
- SeeAlso: <https://swift.org/documentation/docc>
```
=> Support legacy `- SeeAlso:` callout asides 

Sources/SwiftDocC/Model/Rendering/References/CallToActionReference.swift, Sources/SwiftDocC/Model/Rendering/References/ExternalLocationReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/RelativeURLSample.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/SomeSample.md
Bug/issue #, if applicable: rdar://104558809
The `url` argument of the `@CallToAction` directive was meant to be copied in verbatim as the `href` attribute of the resulting button. However, due to using the `DownloadReference` type to store this information, URLs that did not include a protocol and domain (i.e. those meant to reference items outside the documentation catalog/archive but ultimately stored on the same server) would be rewritten to be `/downloads/<filename>`. This PR introduces a `CallToActionReference`, compatible with `DownloadReference`, that bypasses the latter's `renderURL` logic, so that the path written into the `url` argument will be copied verbatim.
None
Use the following directive to test:
```markdown
@Metadata {
@CallToAction(url: "/files/Sample.zip", purpose: …
```
=> make CallToAction `url` arguments encode verbatim in Render JSON

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift
Bug/issue #, if applicable: rdar://105148636
This adds default values for the optional arguments to the public `OutOfProcessReferenceResolver.ResolvedInformation` initializer to avoid breaking the public API.
n/a
n/a
=> Add default values for optional parameters to ResolvedInformation init

Sources/SwiftDocC/Model/Rendering/Content/RenderContentMetadata.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveArgumentWrapper.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveMirror.swift, Sources/SwiftDocC/Semantics/Media/ImageMedia.swift, Sources/SwiftDocC/Semantics/Media/VideoMedia.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/LinkableEntities.json, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Sources/SwiftDocC/SwiftDocC.docc/Resources/ThemeSettings.spec.json, Sources/SwiftDocC/Utility/FeatureFlags.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Sources/generate-symbol-graph/main.swift, Tests/SwiftDocCTests/Semantics/ImageMediaTests.swift, Tests/SwiftDocCTests/Semantics/VideoMediaTests.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
Bug/issue #, if applicable: rdar://102183073
When developing UI libraries or apps,
it can be useful to show previews of how things look
when rendered on a device, like a phone or a tablet.
This new experimental feature is designed to allow authors to wrap
images and videos in a frame, making it easier to create complex assets
and maintain them overtime.
Both `@Image` and `@Video` gain a `deviceFrame` parameter that
associates them with a device frame defined in the DocC catalog’s
`theme-settings.json` file.
This change is described on the Swift forums here:
https://forums.swift.org/t/support-for-device-frames/62151
DocC-Render PR TBD
1. Add an `@Image` or `@Video` directive to a DocC article:
```md
This is a great one!
With a lot of great content.
@Image(source: "sloth", deviceFrame: …
```
=> Support `deviceFrame:` parameter in `@Image` and `@Video` directives

Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Tests/SwiftDocCTests/Rendering/PageKindTests.swift
Bug/issue #, if applicable: rdar://104980714
When the `@PageKind` directive was added, it set the page's `role` on the page itself, but not for any references to that page. That led to situations where a page marked as `@PageKind(sampleCode)` would still get an article's icon in a page that curated it. This PR addresses this by setting the `TopicRenderReference`'s `role` with the role for the selected page kind.
None
Use the following markdown for testing:
```markdown
@Metadata {
@PageKind(sampleCode)
}
```
Steps:
1. Add the above directive to `Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/Directives.md`
2. `bin/preview-docs`
3. Ensure that the reference to the "Directives" page in the Swift-DocC top-level page uses the sample code icon (a pair of curly braces in Swift-DocC-Render) instead …
=> set reference roles with PageKind directive

Sources/SwiftDocC/Model/Rendering/References/AssetReferences.swift, Sources/SwiftDocC/Model/Rendering/References/ExternalLocationReference.swift, Sources/SwiftDocC/Model/Rendering/References/RenderReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/CodableRenderReference.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertFileWritingConsumer.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://105226975
The implementation of `ExternalLocationReference` in #467 meant that there were now two types sourcing `download` references: Both that and the original `DownloadReference`. This broke the code that emitted the `assets.json` digest, since it expected to be able to cast the list of references directly to `[DownloadReference]`. This PR provides some wrapper code in the assets digest to allow both `DownloadReference` and `ExternalLocationReference` to be encoded to the assets digest.
None
Steps:
1. Use a doc catalog where an article uses the `@CallToAction(url:)` directive to link to an externally-located resource. (The Swift-DocC catalog can be used by adding such a directive to any article.)
2. Run `docc convert MyCatalog.docc --emit-digest`.
3. …
=> emit ExternalLocationReferences into assets digest

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift
Bug/issue #, if applicable: <rdar://105599431>
This adds public member-wise initializers to `LinkDestinationSummary`, `LinkDestinationSummary.Variant`, and `OutOfProcessReferenceResolver.ResolvedInformation`.
These types are related to passing information about content between DocC and other sources. Having public initializers for these types enable other sources who import SwiftDocC to use these types to pass information about its content to DocC.
Note: this PR also fixes a minor encoding bug in `LinkDestinationSummary.Variant` where the `title` was unintentionally a double optional. It's intended to be optional compared to the `LinkDestinationSummary` which is a non-optional `String` to the expected type is `String?`. This also matches the OpenAPI spec.
n/a
n/a
Make sure you check off …
=> Add public member-wise initializer to 3 types 

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://101212257
This fixes an issue in the hierarchy based link resolver where articles with file names that resemble a disambiguated symbol name—for a symbol that exist in the local context—would fail to resolve.
n/a
In any documentation project a DocC catalog and at least one symbol. 
1. Enable the hierarchy based link resolver
```
defaults write -g DocCUseHierarchyBasedLinkResolver -bool true
```
2. Add an article with a file name that's follows this pattern: `NameOfSymbol-abcd.md`
3. Add a link to `<doc:NameOfSymbol-abcd>`
The link should resolve to the added article
=> Try finding full path component before the parsed path component name

Sources/docc/DocCDocumentation.docc/distributing-documentation-to-other-developers.md
- related to https://github.com/apple/swift-docc/issues/490, updates the documentation to identify that --checkout-path requires an absolute oath, not a relative path.
Bug/issue #, if applicable: https://github.com/apple/swift-docc/issues/490
Updates DocC documentation to make it more explicit how to use `--checkout-path` when linking source to hosted git repositories.
none.
Visual inspection only.
Steps:
1. Render updated DocC documentation
2. View article update for Distributing Documentation to Other Developers
=> documentation update to clarify CLI option

Sources/SwiftDocC/DocumentationService/Convert/ConvertService+DataProvider.swift, Sources/SwiftDocC/DocumentationService/Convert/ConvertService.swift, Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Sources/SwiftDocC/Infrastructure/DocumentationBundleFileTypes.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Workspace/DefaultAvailability.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationBundle+Info.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Test Resources/StandaloneArticle.md, Tests/SwiftDocCTests/Test Resources/StandaloneTutorial.tutorial, Tests/SwiftDocCTests/Test Resources/StandaloneTutorialOverview.tutorial
Bug/issue #, if applicable: rdar://105374582
Adds baseline support for ConvertService to generate documentation for single articles without a top-level root page and for un-curated tutorials.
None.
In a client that uses `ConvertService`, verify that passing a standalone article or a tutorial results in DocC returning a render node.
=> [ConvertService] Add baseline support for standalone articles and tutorials

Sources/SwiftDocC/Infrastructure/Diagnostics/Diagnostic.swift, Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift, Sources/SwiftDocC/Infrastructure/Diagnostics/Problem.swift, Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/DocumentationCacheBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticConsoleWriterTests.swift, Tests/SwiftDocCTests/Diagnostics/ProblemTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Bug/issue #, if applicable: https://github.com/apple/swift-docc/issues/478 <rdar://105985393>
This works around a limitation that the messages of suggested solutions aren't written to console by including them in the main diagnostic message. It also updates the new link resolution suggestions to describe their replacement so that a reader can identify which described solution corresponds to which "fixit".
I will make more changes in this area but wanted to open this PR first so that we don't regress — by displaying less information to the developer — with the more structured diagnostics.
None
This can be tested with any diagnostic with solutions. This describes how to test it with a link resolution diagnostic.
In any documentation project with some symbols requiring disambiguation. 
1. …
=> Include suggested solution messages in main diagnostic message when writing diagnostics to console

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/SourceRepository/SourceRepository.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/SourceRepository/SourceRepositoryTests.swift
Bug/issue #, if applicable: rdar://104049149
When using ConvertService to generate documentation, makes DocC set the symbol's declaration file path and line to the `metadata.remoteSource` property.
None.
Generate documentation for a symbol using the `ConvertService` API and verify that the `metadata.remoteSource` property is set to the symbol declaration's local path and line number.
=> [ConvertService] Set metadata.remoteSource

Package.resolved, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Semantics/Parameter.swift, Sources/SwiftDocC/Model/Semantics/Return.swift, Sources/SwiftDocC/Utility/FeatureFlags.swift, Sources/SwiftDocC/Utility/MarkupExtensions/ListItemExtractor.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCTests/Test Resources/DeckKit-Objective-C.symbols.json, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
Bug/issue #, if applicable: rdar://105848459
This PR takes the Doxygen support added to Swift-Markdown in https://github.com/apple/swift-markdown/pull/107 and adds it to Swift-DocC behind an experimental flag. By passing `--experimental-parse-doxygen-commands` to `docc convert` or `docc preview`, `\param` and `\returns` commands will be handled as if they were `- Parameter` and `- Returns` list items. This allows users transitioning from a different documentation system that handles Doxygen or HeaderDoc commands to transition to Swift-DocC without needing to change these commands immediately.
None (the Swift-Markdown PR is already merged and is being used in this PR)
Steps:
1. Add the symbol graph from `Tests/SwiftDocCTests/Test Resources/DeckKit-Objective-C.symbols.json` to a …
=> add experimental Doxygen support

Sources/SwiftDocC/Coverage/DocumentationCoverageOptions.swift, Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolutionMigration.swift, Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Sources/SwiftDocC/Model/Rendering/RenderNode.swift, Sources/SwiftDocC/Semantics/Metadata/CallToAction.swift, Sources/SwiftDocC/Semantics/Metadata/DisplayName.swift, Sources/SwiftDocC/Semantics/Metadata/DocumentationExtension.swift, Sources/SwiftDocC/Semantics/Symbol/PlatformName.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/StaticAnalysis.md, Sources/SwiftDocCUtilities/SwiftDocCUtilities.docc/SwiftDocCUtilities/Extensions/Docc.md
Bug/issue #, if applicable: rdar://98692937 
This enabled the hierarchy-based link resolver by default. It also updates a handful of symbol links to remove disambiguation that's now redundant.
None
1. Unset the feature flag if you have it locally set: `defaults remove -g DocCUseHierarchyBasedLinkResolver`
2. Build the TestBundle.docc: `swift run docc convert ./Tests/SwiftDocCTests/Test\ Bundles/TestBundle.docc`
You should see error messages from the new link resolver—meaning that the feature is enabled by default—for example:
> Reference at '/Test-Bundle/article2' can't resolve 'badlink'. No similar pages.
=> [Hold] Enable hierarchy-based link resolver implementation by default

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Test Bundles/BundleWithSameNameForSymbolAndContainer.docc/symbol-graph/SameName.symbols.json
Bug/issue #, if applicable: rdar://106509292
This makes an adjustment to the way the new link resolver implementation to preserve a behavior from the previous implementation. 
If a symbol has a child with the same name, links in the outer's symbol's context should resolve to the inner symbol
```swift
/// ``Something`` ◀︎─ This link should
///                  resolve to this symbol
public struct Something {    //   │
public enum Something {} // ◀︎─╯
}
```
None
- Create a public type with an inner symbol with the same name (for example the above)
- Write a link in the documentation comment for the outer symbol
The link should resolve to the inner symbols
- Curate the relative name of the inner symbol
There shouldn't be a warning about a symbol curating itself.
Make sure you check off the …
=> Prefer resolving link to inner symbol when container has same name

Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/generate-symbol-graph/main.swift
Bug/issue #, if applicable: rdar://106651935
This fixes a crash when running generate-symbol-graph that's caused by two `Row` directive symbol entires.
It also sorts the symbols in the generated output to make it easier to diff the file over time as we add new directives are or update their documentation.
None
Running `swift run generate-symbol-graph` no longer crashes.
=> Fix crash when running generate-symbol-graph

Package.resolved, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Tests/SwiftDocCTests/Rendering/RenderContentCompilerTests.swift
Close #271 
```
Hello
Check out [Hi](https://hi.com)
Check out [this great function](doc:Sloth/eat(_:quantity:))
Check out [this great function ![random image](https://picsum.photos/200)](doc:Sloth/eat(_:quantity:))
- <doc:Sloth/eat(_:quantity:)>
```
Before the PR (current behavior)
After the PR (expected behavior)
~apple/swift-markdown#82~
apple/swift-markdown#110
See RenderContentCompilerTests.swift
https://github.com/apple/swift/pull/61506
=> Fix custom doc link title issue

Sources/SwiftDocC/Semantics/Metadata/CallToAction.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift
Bug/issue #, if applicable: rdar://106365392
Thread Sanitizer emitted some warnings during the CallToAction tests, due to some racy access to the resolved assets. This is because directive parsing is done in parallel alongside asset registration, which could cause some spurious failures if accesses weren't aligned correctly. This PR changes the location that `@CallToAction(file:)` assets are validated so that they don't conflict with the initial asset registration.
None
Steps:
1. `swift test --sanitize thread --filter SwiftDocCTests.CallToActionTests`
2. Ensure that no warnings are emitted by Thread Sanitizer during the tests.
=> don't perform asset lookup during CallToAction validation, fixing TSan in CallToActionTests

Sources/SwiftDocC/Infrastructure/Bundle Assets/SVGIDExtractor.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Sources/SwiftDocC/Utility/NearMiss.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
Bug/issue #, if applicable: rdar://99990978
This PR does 4 things related to link diagnostics:
- It adds a new diagnostic when a known name but an unknown disambiguation
- It leverages the authored disambiguation to narrow down the suggestions (for example to only make suggestions of the matching symbol type)
- It rephrases the link diagnostic error messages to be more to the point and surface the most relevant and specific information first. 
- It shrinks the diagnostic range to the path component with the issue
For example, instead of highlighting the full link range and using this error message
```
- ``MyKit/MyClas/myFunction()``
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
>Topic reference 'MyKit/MyClas/myFunction()' couldn't be resolved. Reference at '/MyKit' can't resolve …
=> Rephrase link diagnostic error messages to provide more specific information first

Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/Top-Level Directives/Tutorial/TutorialArticle.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/tutorial-syntax.md, Sources/generate-symbol-graph/main.swift
Bug/issue #, if applicable: rdar://106652019
This adds the tutorial article directive to the generated documentation and updates generate-symbol-graph to warn about missing directives.
It also adds basic documentation for the tutorial article directive that's based on the documentation for the tutorial directive.
None.
- Preview the documentation with 
```
swift run docc preview Sources/docc/DocCDocumentation.docc 
```
Verify that there is a `Article` directive page 
- ~ [ ] Added tests~
=> Include tutorial article directive in generated documentation

Sources/SwiftDocC/DocumentationService/Convert/ConvertService.swift, Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift
Bug/issue #, if applicable: rdar://106549009
Adds an API in `ConvertRequest` that allows overriding the documentation comment of symbols in the symbol graphs provided by the client.
None.
Use the new `ConvertRequest` API to include an overriding documentation comment and verify that the render nodes you get back contain its contents.
=> [ConvertService] Allow overriding doc comments

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/HTTPBodySectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/HTTPParametersSectionTranslator.swift, Sources/SwiftDocC/Model/Section/Sections/DictionaryKeysSection.swift, Sources/SwiftDocC/Model/Section/Sections/HTTPBodySection.swift, Sources/SwiftDocC/Model/Section/Sections/HTTPParametersSection.swift, Sources/SwiftDocC/Model/Section/Sections/HTTPResponsesSection.swift, Sources/SwiftDocC/Model/Semantics/HTTPBody.swift, Sources/SwiftDocC/Model/Semantics/HTTPParameter.swift, Sources/SwiftDocC/Model/Semantics/HTTPResponse.swift, Sources/SwiftDocC/Utility/ListItemUpdatable.swift, Sources/SwiftDocC/Utility/MarkupExtensions/ListItemExtractor.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeHTTPRequestTests.swift, Tests/SwiftDocCTests/Test Bundles/HTTPRequests.docc/GetArtist.md, Tests/SwiftDocCTests/Test Bundles/HTTPRequests.docc/requests.symbols.json, Tests/SwiftDocCTests/XCTestCase+AssertingTestData.swift
Bug/issue #, if applicable: rdar://106389558
Adds support for documenting HTTP parameters, body, and responses in Markdown. Updated ListItemExtractor to pull documentation to HTTPParameters, HTTPBody, and HTTPResponses from markdown content and updated associated section types to merge those docs with data extracted from the symbol graph files.
None.
Build documentation using HTTP symbol graphs and verify that documentation from documentation extensions is present in their render nodes.
=> Add support for documenting HTTP endpoints

Sources/SwiftDocC/SourceRepository/SourceRepository.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/SourceRepository/SourceRepositoryTests.swift
Bug/issue #, if applicable: rdar://106667647
This updates the `SourceRepository` for local files so that clients can customize the handling of local "Declared In" source file URLs while still using the default handling for other files. 
None
applicable._
Steps:
=> Use a custom scheme for local "Declared In" source file URLs

Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Utility/FeatureFlags.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
Bug/issue #, if applicable: rdar://107002535
This PR turns on the Doxygen support added in https://github.com/apple/swift-docc/pull/497 for all doc builds.
None
See test instructions in https://github.com/apple/swift-docc/pull/497. Also ensure that existing functionality is not impacted.
=> enable Doxygen support by default

Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Utility/FeatureFlags.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/497
- **Explanation**: To make migration to Swift-DocC easier from alternate documentation engines, we have decided to enable the basic Doxygen support by default.
- **Scope**: Enhancement for users who have `@param` and `@returns` Doxygen commands in their documentation.
- **Issue**: rdar://107002535
- **Risk**: Low. The implementation is tightly focused for just the above-mentioned commands, and should not affect other documentation content.
- **Testing**: Automated tests pass without needing to pass the "experimental" flag.
=> [5.9] enable Doxygen support by default

Sources/SwiftDocC/DocumentationService/Convert/ConvertService.swift, Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift
Bug/issue #, if applicable: rdar://107075861
This adds an argument to ConvertRequest to allow opting out of source file URI information for requests that don't need or want that information. 
None
Generate documentation for a symbol using the ConvertService API and configure `emitSymbolSourceFileURIs` to `false` in the request.
The render node in the response should not have its metadata.remoteSource property set.
=> Add request argument to opt-out of source file path information

Sources/SwiftDocC/DocumentationService/Convert/ConvertService.swift, Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/526
- **Explanation**: Add an argument to the ConvertService request to allow for opting out of source file path information in the response
- **Scope**: ConvertService
- **Radar**: rdar://107075861
- **Testing**: New tests verify that the source file path information is omitted when the new request argument it passed
=> [5.9] Add request argument to opt-out of source file path information

Package.resolved, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeDictionaryDataTests.swift, Tests/SwiftDocCTests/Test Bundles/DictionaryData.docc/dictionary.symbols.json, Tests/SwiftDocCTests/XCTestCase+AssertingTestData.swift
Bug/issue #, if applicable: rdar://107432025
Converts new `typeDetails` information in symbol graph into base-type details and allowed type declarations for `RenderProperty` entities, such as dictionary keys and HTTP parameters. This data is rendered on the page as part of the key or parameter documentation as a "Possible types" attribute, listing the individual types.
Requires changes on `type_details` branch of pdwilson12/swift-docc-symbolkit tracked in https://github.com/apple/swift-docc-symbolkit/pull/56
Build docc and preview the DictionaryData.docc fixture bundle.
Steps:
1. Run `docc preview` on the `DictionaryData.docc` fixture
2. View the `Artist` page and confirm "Possible types" entry of `monthOfBirth` key.
3. Modify the symbol graph for monthOfBirth key, adding/modifying the …
=> Process `typeDetails` information from symbol graphs.

Package.resolved, Package.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeDictionaryDataTests.swift, Tests/SwiftDocCTests/Test Bundles/DictionaryData.docc/dictionary.symbols.json, Tests/SwiftDocCTests/XCTestCase+AssertingTestData.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/529
Explanation: HTTP/REST requests and JSON dictionaries can define parameters and keys that are weakly typed, allowing for multiple possible value types, such as integer or string. This extends symbol graphs to call out those individual allowed types and show up on the rendered page.
Scope: Adds a new optional key to symbol graphs and converts that data to existing page structures used when rendering HTTP parameters and dictionary keys.
Radar: rdar://107432025
Risk: Low. Added key is optional.
Testing: Changes are covered by unit tests.
Reviewer: @QuietMisdreavus
=> [5.9] Process `typeDetails` information from symbol graphs

Package.resolved, Package.swift
- **Explanation**: This PR updates the branch dependencies of Swift-Markdown and swift-lmdb to their respective `release/5.9` branches.
- **Scope**: Ensures that the 5.9 release of Swift-DocC doesn't accidentally integrate with unintended code from these projects' `main` branches.
- **GitHub Issue**: None
- **Risk**: Low. These repos should be very close in code content with each other, if not identical.
- **Testing**: `bin/test` passes.
=> update branch dependencies to release/5.9

CONTRIBUTING.md, README.md, Sources/docc/DocCDocumentation.docc/documenting-a-swift-framework-or-package.md
Updates the instructions to get started with DocC to mention that using the Swift-DocC plugin is the preferred way of using DocC.
None.
N/A
=> Update DocC setup instructions

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Test Bundles/DefaultImplementationsWithExportedImport.docc/DefaultImplementationsWithExportedImport.symbols.json, Tests/SwiftDocCTests/Test Bundles/TestBundle.docc/sidekit.symbols.json, Tests/SwiftDocCUtilitiesTests/Test Bundles/TestBundle.docc/sidekit.symbols.json
Bug/issue #, if applicable: rdar://107623749 
Fix a crash (from a `fatalError` in `DocumentationContext`) when a protocol with a default implementation in one module is both `@_export` imported and type aliased in another module.
None
- Create a project two targets—for example named "Outer" and "Inner"—where one target depend on the other
- In the "Inner" target, define a protocol with some requirement and provide a default implementation for that requirement
```
// Inner.swift
public protocol Something {
func doSomething()
}
public extension Something {
func doSomething() {}
}
```
- In the "Outer" target, use `@_exported import` to bring the symbols of the "Inner" target into the "Outer" target and also create a typealias with the same name as protocol from the "Inner" target
```
// …
```
=> Fix a crash when a protocol with a default implementation is aliased with the same name

Sources/SwiftDocC/Model/Rendering/References/TopicColor.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/RenderMetadata.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Metadata/PageColor.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Sources/SwiftDocC/SwiftDocC.docc/Resources/ThemeSettings.spec.json, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Semantics/MetadataTests.swift, Tests/SwiftDocCTests/Test Bundles/BookLikeContent.docc/MyArticle.md, bin/preview-docs
Bug/issue #, if applicable: rdar://106153042
Adds a new `@PageColor` metadata directive that allows for customizing the color used to represent a given page.
`@PageColor` gives authors control over the color used when rendering a page – initially this will affect the background color Swift-DocC-Render uses in the page's introduction (hero) section.
@Metadata {
@PageColor(blue)
}
Let's check out what's new in SlothCreator!
...
```swift
@PageColor(_ color: Color)
```
Use the `PageColor` directive to provide a hint to the Swift-DocC renderer as to what color should represent this page. The renderer will use this color, depending on the context, as a foundation for the other accent colors used in the page. For example, Swift-DocC-Render will use this color as the primary background color of a …
=> Add authoring support for a `@PageColor` directive

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://98781530
This adds basic handling of collisions to deprioritize synthesized symbols and default implementations of protocol requirements. 
It's more likely that the developer intended to link to the other symbol so the hierarchy based resolver will resolve the ambiguous link the to that symbol. 
None.
- Create a public protocol with some protocol requirements and also add a public default implementation of it. 
- Write a symbol link to without disambiguation to the protocol requirement. For example:
```
/// These two links should resolve:
///
/// - ``Something/doSomething()``
/// - ``doSomething()``
public protocol Something {
func doSomething()
}
public extension Something {
func doSomething() {}
}
```
Make sure you check off the following items. If …
=> Disfavor default implementations and synthesized symbols in link collisions

Sources/SwiftDocC/Model/Rendering/References/TopicColor.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/RenderMetadata.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Metadata/PageColor.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Sources/SwiftDocC/SwiftDocC.docc/Resources/ThemeSettings.spec.json, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Semantics/MetadataTests.swift, Tests/SwiftDocCTests/Test Bundles/BookLikeContent.docc/MyArticle.md, bin/preview-docs
- **Explanation**: Adds a new `@PageColor` metadata directive that allows for customizing the color used to represent a given page.
- **Scope**: Small in scope. Targeted change that adds a new directive without breaking backwards compatibility.
- **Issue**: rdar://106153042
- **Risk**: Low risk.
- **Testing**: End to end testing with Swift-DocC-Render. Additional unit tests have been added.
- **Original PR:** #525
- **Related Forums Post**: [Support for customizing a page’s accent color in Swift-DocC](https://forums.swift.org/t/support-for-customizing-a-page-s-accent-color-in-swift-docc/64093) 
- **Reviewers**: @d-ronnqvist @daniel-grumberg @mportiz08
=> [5.9] Add authoring support for the `@PageColor` directive

Sources/SwiftDocC/Infrastructure/CoverageDataEntry.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/DocumentationCacheBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphRelationshipsBuilder.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/DeclarationsSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/HTTPBodySectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/HTTPResponsesSectionTranslator.swift, Tests/SwiftDocCTests/Converter/DocumentationContextConverterTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/InheritIntroducedAvailabilityTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/AbsoluteSymbolLinkTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/DocCSymbolRepresentableTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphRelationshipsBuilderTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
Bug/issue #, if applicable: rdar://106654403
This changes `DocumentationContext.symbolIndex` from a lookup that return `DocumentationNode` values to a lookup that return `ResolvedTopicReference` values. 
Storing all nodes both in the documentation cache and in the symbol index makes it easy to accidentally hold on to old versions of nodes if the value in the documentation cache is updated without also updating the value in the symbol index. By instead only storing the node's resolved reference in the symbol cache and using it to find the node in the documentation cache, various places in the code that modify documentation nodes only need to update the value in one place.
This makes up for the previous peak memory usage increase from …
=> Store only the resolved reference in DocumentationContext.symbolIndex

Sources/SwiftDocC/Infrastructure/CoverageDataEntry.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/DocumentationCacheBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphRelationshipsBuilder.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/DeclarationsSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/HTTPBodySectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/HTTPResponsesSectionTranslator.swift, Tests/SwiftDocCTests/Converter/DocumentationContextConverterTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/InheritIntroducedAvailabilityTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/AbsoluteSymbolLinkTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/DocCSymbolRepresentableTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphRelationshipsBuilderTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/543
- **Explanation**: Reduce peak memory usage by ~1.5% by looking up documentation nodes in the context instead of storing them directly in the symbol index. 
- **Scope**: Peak memory usage
- **Radar**: rdar://106654403
- **Testing**: Automated testing and some manual testing verify that output and other behavior is unchanged.
- **Reviewer**: @franklinsch 
My main reason for suggesting we cherry pick this change is to have similar code on main and release/5.9 to minimize conflicts when cherry picking other changes from main.
=> [5.9] Store only the resolved reference in DocumentationContext.symbolIndex

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/DocumentationCurator.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Utility/ValidatedURL.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://85531439
Fix an issue where symbol links or documentation links containing special characters resolved successfully but didn't render as expected on the page.
There are two parts to this fix:
- Allow any previously resolved reference to be looked up without resolving it again. I do this because `MarkupReferenceResolver` replaces the links original destination with the absolute string of the resolves reference but the resolved reference replaces non-path characters with "-" resulting in potential ambiguity when re-resolving the link.
- Preserve the `isAutolink` attribute of `Link` values when updating their destination with a new resolved `destination`
None.
- Use one or more special characters—for example `π` or 😃—in an element that can be linked to. …
=> Fix rendering issue for links with special characters

Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolutionMigration.swift
This fixes an issue where the opt-logic for the new link resolver was inverted. 
None.
- Run `swift run docc convert /path/to/SomeBundle.docc` with `DOCC_USE_HIERARCHY_BASED_LINK_RESOLVER=YES`.
DocC should use the hierarchy based resolver.
- Run `swift run docc convert /path/to/SomeBundle.docc` without `DOCC_USE_HIERARCHY_BASED_LINK_RESOLVER` set.
DocC should use the hierarchy based resolver.
- Run `swift run docc convert /path/to/SomeBundle.docc` with `DOCC_USE_HIERARCHY_BASED_LINK_RESOLVER=NO`.
DocC shouldn't use the hierarchy based resolver.
=> Fix inverse logic in hierarchy based link resolver environment opt-out

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/DocumentationService/Models/DocumentationServerTests.swift
Bug/issue #, if applicable: rdar://107531364
This enables convert service requests to resolve assets that are references in the content. This required two changes:
- Allow the fallback asset resolve to look for an asset identifier when the local asset manager didn't find one.
- When rendering the image, get the file extension from the asset's url instead of from the asset identifier.
This PR also removes unnecessary empty media references when an asset didn't render anything.
None
In a client that uses` ConvertService`:
- Verify that passing an article with image references (either using `![]()`, `@Image`, or `@PageImage`) result in DocC returning a render node with image references for those images. 
- Add another article with `@PageImage` images and link it with `@Links(visualStyle: …
=> [ConvertService] Support resolving images referenced in content

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedManualAutomaticCuration.docc/TestBed.md
- **Explanation**: Fixes a bug with the new `@PageColor` metadata directive where the directive was ignored when used on symbols page.
- **Scope**: Small in scope. Targeted change fixes render node conversion for symbol pages.
- **Issue**: rdar://107962126
- **Risk**: Low risk.
- **Testing**: End to end testing with Swift-DocC-Render. Additional unit tests have been added.
- **Original PR:** #549
- **Reviewers**: @franklinsch
=> [5.9] Correctly set page color for symbol pages

Package.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandSourceRepositoryTests.swift
Bug/issue #, if applicable: rdar://107960794
This fixes an issue where one expression in a test was very slow to type check. It also opts in to a warning in debug builds if expressions take too long to type check.
None.
Run `swift test`. There shouldn't be warnings about a test taking seconds to type check. 
=> Fix test that took seconds to type check

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Test Bundles/MixedManualAutomaticCuration.docc/TestBed.md
Bug/issue #, if applicable: rdar://107962126
Fixes a bug where the `@PageColor` metadata directive was ignored when used on symbol pages.
Add:
```
@Metadata {
@PageColor(purple)
}
```
to a symbol page and confirm that the page renders as expected.
=> Correctly set page color metadata for symbol pages

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/TopicGraph.swift, Sources/SwiftDocC/Model/Kind.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Test Bundles/ModuleWithConformanceAndExtension.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/ModuleWithConformanceAndExtension.docc/ModuleWithConformanceAndExtension.md, Tests/SwiftDocCTests/Test Bundles/ModuleWithConformanceAndExtension.docc/ModuleWithConformanceAndExtension.symbols.json, Tests/SwiftDocCTests/Test Bundles/ModuleWithConformanceAndExtension.docc/ModuleWithConformanceAndExtension@Swift.symbols.json, Tests/SwiftDocCTests/Test Bundles/ModuleWithSingleExtension.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/ModuleWithSingleExtension.docc/ModuleWithSingleExtension.md, Tests/SwiftDocCTests/Test Bundles/ModuleWithSingleExtension.docc/ModuleWithSingleExtension.symbols.json, Tests/SwiftDocCTests/Test Bundles/ModuleWithSingleExtension.docc/ModuleWithSingleExtension@Swift.symbols.json
Bug/issue #, if applicable: rdar://107729630
When Swift-DocC gets symbol graphs with extension block symbols, it creates "Extended Module/Class/Structure/etc" symbols to automatically curate the extension symbols into. However, if the extension symbols are then curated in the rest of the documentation hierarchy, these extra symbols are left in the topic graph and create empty pages that don't need to be there. This PR adds a pass to `DocumentationContext.register(_:)` to drop these symbols if all their children have been curated elsewhere. (This pass is done recursively, so "Extended Module" pages will drop if all their child "Extended Class/Structure/etc" pages are also dropped.)
None
The following code was used to test this functionality:
```swift
/// a namespace for organization.
/// …
```
=> drop an "Extended Symbol" page when its children are curated elsewhere

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/TopicGraph.swift, Sources/SwiftDocC/Model/Kind.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Test Bundles/ModuleWithConformanceAndExtension.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/ModuleWithConformanceAndExtension.docc/ModuleWithConformanceAndExtension.md, Tests/SwiftDocCTests/Test Bundles/ModuleWithConformanceAndExtension.docc/ModuleWithConformanceAndExtension.symbols.json, Tests/SwiftDocCTests/Test Bundles/ModuleWithConformanceAndExtension.docc/ModuleWithConformanceAndExtension@Swift.symbols.json, Tests/SwiftDocCTests/Test Bundles/ModuleWithSingleExtension.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/ModuleWithSingleExtension.docc/ModuleWithSingleExtension.md, Tests/SwiftDocCTests/Test Bundles/ModuleWithSingleExtension.docc/ModuleWithSingleExtension.symbols.json, Tests/SwiftDocCTests/Test Bundles/ModuleWithSingleExtension.docc/ModuleWithSingleExtension@Swift.symbols.json
Cherry-pick of #541
- **Explanation**: When a documentation bundle makes use of extension block symbols, we create "Extended Symbol" pages to automatically curate the extensions. However, if the extensions are then curated elsewhere, these pages are left empty. This PR drops these "Extended Symbol" pages when they have no child pages and also have no documentation extension file.
- **Scope**: Enhancement for users of extension-block symbols.
- **GitHub Issue**: rdar://107729630
- **Risk**: Low. This only affects the new extension-block symbol feature.
- **Testing**: Tests have been added to ensure the new functionality. Existing tests still pass.
- **Reviewer**: @d-ronnqvist
=> [5.9] drop an "Extended Symbol" page when its children are curated elsewhere

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/DocumentationCurator.swift, Sources/SwiftDocC/Model/Identifier.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Utility/ValidatedURL.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/532
- **Explanation**: Fix an issue where symbol links and documentation links containing characters not allowed in URL paths or URL fragments resolved successfully but didn't render as expected on the page.
- **Scope**: Links with special characters.
- **Radar**: rdar://85531439
- **Testing**: New tests verify that links with symbol links and documentation links with special characters in path and fragment components render as expected.
- **Reviewer**: @daniel-grumberg
=> [5.9] Fix rendering issue for links with special characters

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/DocumentationService/Models/DocumentationServerTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/539
- **Explanation**: Enable convert service requests to resolve assets that are referenced in content. 
- **Scope**: Convert Service requests for content with media references.
- **Radar**: rdar://107531364
- **Testing**: New tests verify that ConvertService request for content with various kinds of image references (`![]()`, `@Image`, and `@PageImage`) result in DocC resolving those image references and returning a render node with the resolved image information.
- **Reviewer**: @franklinsch
=> [5.9] [ConvertService] Support resolving images referenced in content

Package.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandSourceRepositoryTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/547
- **Explanation**: This fixed an issue where one expression in a test was very slow to type check. In some cases this resulted in an error about the compiler being unable to type check this expression in a reasonable time.
- **Scope**: _Possible_ error about slow type checking during builds of test targets.
- **Radar**: rdar://107960794
- **Testing**: This change was verified manually. Debug builds opt in to warnings about slow type checking to avoid similar issues in the future.
- **Reviewer**: @franklinsch 
Note: the only reason for suggesting that we cherry pick this is to avoid _potential_ compiler errors about type checking taking unreasonably long.
=> [5.9] Fix test that took seconds to type check

Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/Top-Level Directives/Tutorial/Section.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/Top-Level Directives/Tutorial/Section/ContentAndMedia.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/Top-Level Directives/Tutorial/Section/Stack.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/Top-Level Directives/Tutorial/Section/Steps/Step/Step.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/Top-Level Directives/Tutorial/Section/Steps/Steps.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/Top-Level Directives/Tutorial/Tutorial.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/building-an-interactive-tutorial.md, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift
Bug/issue #, if applicable: None.
_Provide a description of what your PR addresses, explaining the expected user experience. 
Also, provide an overview of your implementation._
Since 'layout' init parameter of 'ContentAndMedia' is deprecated by https://github.com/apple/swift-docc/blob/f7cc54ab64eeebe06d4ca721cc7ac78c2da6f545/Sources/SwiftDocC/Semantics/ContentAndMedia.swift#L86
We should remove the usages of this parameter in our documents and tests
_Describe any dependencies this PR might have, such as an associated branch in another repository._
None.
applicable._
Steps:
None.
Make sure you check …
=> Remove deprecated usages of 'layout' API of 'ContentAndMedia' in docs

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderMetadataTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/557
- **Explanation**: Reduces ambiguity of extension symbols by ensuring that both the containing module and the extended module's names are included on the rendered pages of these symbols.
- **Scope**: Affects documentation bundles with extension block symbols.
- **Issue**: rdar://107729534
- **Risk**: Very low. The change only adds additional metadata for extension symbols; other documentation builds are unaffected.
- **Testing**: Automated tests have been added; the change was also manually tested by running on ArgumentParser.
=> add the extending module as a related module for extension symbols

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderMetadataTests.swift
Issue: rdar://107729534
For bundles with extension block symbols, it can be a bit confusing to understand which module is actually needed to use an extension symbol. This PR adds context to these symbols by adding the extended module as a "related module" to the RenderNode, which renders both the owning module and the extended module to be shown in the rendered page.
(Note that this doesn't work for bundles without extension block symbols, due to inconsistencies in the Swift symbol graph. This is noted in the symbol graph loader as being connected to rdar://63200368. An interim fix will likely need to land in SymbolKit, since the module name processing code mainly happens there now.)
None
Steps:
1. Convert docs for the `Tests/SwiftDocCTests/Test …
=> Render extended symbol pages with their extended module

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Metadata/CallToAction.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift, Tests/SwiftDocCTests/Semantics/CallToActionTests.swift, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MyArticle.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MyExternalSample.md
Bug/issue #, if applicable: rdar://108013602
Updates the logic for `@CallToAction` buttons that are attached to `sampleCode` pages and use the `link` purpose to render with a more specific “View Source” title instead of the more generic “Visit” title.
This makes the intent of the button more clear. Regular article pages should continue to have the same behavior.
Create an article with `@CallToAction` directive using that provides a `url` and `link` purpose and a `@PageKind(sampleCode)` directive. Confirm that the call to action button is labeled "View Source".
```swift
@Metadata {
@PageKind(sampleCode)
@CallToAction(url: "https://github.com/apple/swift-docc", purpose: link)
}
```
=> Label Sample-Code Call-to-Action buttons with "View Source"

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Metadata/CallToAction.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift, Tests/SwiftDocCTests/Semantics/CallToActionTests.swift, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MyArticle.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MyExternalSample.md
- **Explanation**: Updates `@CallToAction` buttons that are attached to sample code pages to render with a more specific “View Source” title instead of the current, generic “Visit” title.
- **Scope**: Small in scope. Targeted change to make the intent of the button more clear.
- **Issue**: rdar://108013602
- **Risk**: Low risk.
- **Testing**: End to end testing with Swift-DocC-Render. Additional unit tests have been added.
- **Original PR:** #566
- **Reviewers**: @franklinsch
=> [5.9] Label Sample-Code Call-to-Action buttons with "View Source"

Sources/SwiftDocC/DocumentationService/Convert/ConvertService.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContext+RootPageTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
- **Explanation**: Use link resolution to match documentation extensions with symbols. This allows for all link resolutions features to work in documentation extension title links.
- **Scope**: Matching of documentation extension files with symbols.
- **Issue**: rdar://76252171
- **Risk**: Low risk.
- **Testing**: New tests verify that various link resolution features work in documentation extension titles.
- **Original PR:** #565
- **Reviewers**: @franklinsch
=> [5.9] Match documentation extensions to symbols using link resolver (#565)

Sources/SwiftDocC/Converter/DocumentationContextConverter.swift, Sources/SwiftDocC/DocumentationService/Convert/ConvertService.swift, Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/AccessControl+Comparable.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/RenderMetadata.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/RenderNode+Codable.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Rendering/RenderMetadataTests.swift
Provide ConvertService with mapping of USRs to minimal access level required for extended documentation to be available
rdar://105460209
Provide a way for the convert service to add information in the render node to say if there is available additional documentation for a given symbol. This information is provided by the client on a per symbol access control level basis.
=> Provide ConvertService with mapping of USRs to minimal access level required for extended documentation to be available

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://108666088
This reverts the support for resolving documentation extensions links relative to modules since it caused a regression when a module and a top-level symbol had the same name.
None.
=> Revert support for module-relative documentation extension links

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
- **Explanation**: Revert the support for resolving documentation extensions links relative to modules since it caused a regression when a module and a top-level symbol had the same name.features to work in documentation extension title links.
- **Scope**: Regression with matching documentation extension files with symbols.
- **Issue**: rdar://108666088
- **Risk**: Low.
- **Testing**:  Manually verified that reverting this change fixes the regression. Existing automated tests continue to pass. 
- **Original PR:** #575
- **Reviewers**: @QuietMisdreavus and @ethan-kusters
=> Revert support for module-relative documentation extension links (#574)

Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveIndex.swift, Sources/SwiftDocC/Semantics/Metadata/PageImage.swift, Sources/SwiftDocC/Semantics/Options/AutomaticTitleHeading.swift, Sources/SwiftDocC/Semantics/Options/Options.swift, Sources/SwiftDocC/Semantics/Reference/Row.swift, Sources/SwiftDocC/Semantics/Reference/TabNavigator.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/generate-symbol-graph/main.swift
Includes a fix for generate-symbol-graph doc comment fetching for directives implemented by a class with a different name.
rdar://108207445
=> Expand documentation for new layout directives

Sources/SwiftDocC/Model/Rendering/References/FileReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/LineHighlighter.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Model/LineHighlighterTests.swift
Bug/issue #, if applicable: rdar://107965493
This enables convert service requests to resolve file assets that are references in the tutorial steps. This is done by asking the context to resolve the file asset if its data doesn't already exist.
None
In a client that uses` ConvertService`:
- Verify that passing an tutorial file with steps using `@Code` references result in DocC returning a render node with file references for those code files with line highlights for the differences between the files' content. 
=> Support resolving code file references in ConvertService

Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveIndex.swift, Sources/SwiftDocC/Semantics/Metadata/PageImage.swift, Sources/SwiftDocC/Semantics/Options/AutomaticTitleHeading.swift, Sources/SwiftDocC/Semantics/Options/Options.swift, Sources/SwiftDocC/Semantics/Reference/Row.swift, Sources/SwiftDocC/Semantics/Reference/TabNavigator.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/generate-symbol-graph/main.swift
Cherry-pick for https://github.com/apple/swift-docc/pull/576
Includes a fix for generate-symbol-graph doc comment fetching for directives implemented by a class with a different name.
rdar://108207445
=> 🍒[5.9] expanded documentation for new directives

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Model/Rendering/Symbol/ConformanceSection.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Test Bundles/SymbolsWithSameNameAsModule.docc/Something.symbols.json, Tests/SwiftDocCUtilitiesTests/JSONEncodingRenderNodeWriterTests.swift
Bug/issue #, if applicable:
- rdar://76252171 #516 
- rdar://108672152 #572
This implements much better support for relative symbol links when multiple symbols in the hierarchy have the same name (or have the same name as the module). This also unblocks—and reenables—support for omitting the module name in documentation extensions.
This change is smaller than the diff makes it appear. 867 of the additions are tests and test data and much of the implementation changes are moved or updated code (153 added, 143 removed).
To describe these changes in detail it's easiest to look at an example. If we consider this Swift code:
```swift
/* in a module named "Something" */
public struct Something {
/// Example 1: ``Something/second``
/// Example 2: ``Something/fourth``
public enum Something {
case …
```
=> Better support for relative links when multiple symbols in the hierarchy have the same name

Sources/SwiftDocC/Model/Rendering/References/FileReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/LineHighlighter.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Model/LineHighlighterTests.swift
- **Explanation**: Support resolving tutorial code file references in ConvertService requests.
- **Scope**: Tutorial content in ConvertService requests
- **Issue**: rdar://107965493
- **Risk**: Low risk. Isolated and limited scope
- **Testing**: New tests verify that file references are resolved and that the Tutorial Render JSON include the code file's content and their line differences.
- **Original PR:** #570
- **Reviewers**: @ethan-kusters
=> [5.9] Support resolving code file references in ConvertService

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Model/Rendering/Symbol/ConformanceSection.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Test Bundles/SymbolsWithSameNameAsModule.docc/Something.symbols.json, Tests/SwiftDocCUtilitiesTests/JSONEncodingRenderNodeWriterTests.swift
- **Explanation**: Better support for resolving symbol links when multiple symbols in the hierarchy (incl. the module symbol) have the same name. The original PR has detailed examples.
- **Scope**: Link resolution for local symbol links and documentation links.
- **Issue**: rdar://76252171&108672152
- **Risk**: Low. Changes to link resolution has broad impact but are also very well tested.
- **Testing**: New tests verify that links that previously failed now succeed, that still failing links have the same error messages, and that the previous regression that led to a revert isn't reintroduced by this. I also manually tested the project where that regression previously occurred.
- **Original PR:** #578 
- **Reviewers**: @daniel-grumberg
=> [5.9] Better support for relative links when multiple symbols in the hierarchy have the same name

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://108974747
This change tracks successfully resolved external references the same as successfully resolved local references, enabling them to be looked up in the reference index without going through the link resolution code path again.
None.
=> Add successfully resolved external references to reference index

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift
- **Explanation**: Tracks successfully resolved external references the same as successfully resolved local references, allowing the same code path to be used during rendering.
- **Scope**: Externally resolved content.
- **Issue**: rdar://108974747
- **Risk**: Low. Isolated and limited scope.
- **Testing**: New test verify that the external topic reference and its resolved content exist in the Render JSON for the page that linked to it.
- **Original PR:** #582
- **Reviewers**: @ethan-kusters
=> [5.9] Add successfully resolved external references to reference index

Sources/SwiftDocC/Model/Rendering/References/FileReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/LineHighlighter.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Model/LineHighlighterTests.swift
- **Explanation**: Support resolving tutorial code file references in ConvertService requests.
- **Scope**: Tutorial content in ConvertService requests.
- **Issue**: rdar://107965493
- **Risk**: Low risk. Isolated and limited scope
- **Testing**: New tests verify that file references are resolved and that the Tutorial Render JSON include the code file's content and their line differences.
- **Original PR:** #570
- **Reviewers**: @ethan-kusters
=> [5.9 05-01-2023] Support resolving code file references in ConvertService 

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation**: Restore previous behavior where "doc" links prioritize non-symbol results without needing disambiguation.
- **Scope**: Documentation links with collisions between symbols and non-symbols
- **Issue**: rdar://109583745
- **Risk**: Low.
- **Testing**: Added unit tests verify the behavior of symbol and non-symbol collisions for both symbol links and general documentation links.
- **Original PR:** #594 
- **Reviewers**: @ethan-kusters
=> [5.9] Prefer non-symbols in general documentation links

Sources/SwiftDocC/Utility/FoundationExtensions/AutoreleasepoolShim.swift
The `autoreleasepool` is technically required on all non-ObjC runtimes. It is likely better to use the unstable `_runtime(_ObjC)` check but for now simply extend the OS list with Windows.
=> FoundationExtensions: enable autoreleasepool on Windows

Sources/SwiftDocC/Utility/Synchronization.swift
Use a `SRWLOCK` on Windows to support locking.  Slim Reader-Writer locks are lightweight mutexes that closely resemble `pthread_mutex_t` in functionality.  While possible to use `WaitOnAddress` to implement `os_unfair_lock`, that would be more complex and a slightly heavier mutex as a starting point seems reasonable.  If it turns out that the performance really requires an even lighter weight locking primitive, we can refine this to `WaitOnAddress` subsequently.
=> Utility: add a Windows path to the synchronisation support

Package.swift, Sources/SwiftDocCUtilities/Docc.swift
This is the critical change to enable Windows support in DocC.  The dependency on NIO is restricted to the PreviewServer and as NIO is incapable of supporting non-POSIX models (or emulation of POSIX models), we cannot use this dependency on Windows.  As a temporary solution, remove the NIO dependency on Windows by removing the PreviewServer.
=> build: remove the PreviewServer on Windows

Sources/docc/DocCDocumentation.docc/distributing-documentation-to-other-developers.md
This update the documentation for [the Distributing Documentation to Other Developers article][docs] to include additional information about [the enhancements to hosting documentation archives in static environments][forums].
[docs]: https://www.swift.org/documentation/docc/distributing-documentation-to-other-developers
[forums]: https://forums.swift.org/t/supporting-hosting-docc-archives-in-static-environments-like-github-pages-by-default/56524
None
None
=> Update distribution documentation static environment enhancements

Sources/docc/DocCDocumentation.docc/adding-structure-to-your-documentation-pages.md, Sources/docc/DocCDocumentation.docc/adding-supplemental-content-to-a-documentation-catalog.md, Sources/docc/DocCDocumentation.docc/documenting-a-swift-framework-or-package.md, Sources/docc/DocCDocumentation.docc/writing-symbol-documentation-in-your-source-files.md
This makes various small phrasing updates to documentation articles.
It also notes small changes to symbol links in documentation extensions and points the reader to use the Swift DocC plugin to build documentation.
None
N/a
=> Various small documentation phrasing updates

Sources/docc/DocCDocumentation.docc/formatting-your-documentation-content.md
This update the documentation for [Formatting Your Documentation Content][docs] to include additional information about the enhancements to symbol links.
[docs]: https://www.swift.org/documentation/docc/formatting-your-documentation-content
None
None
=> Update content formatting documentation with symbol link enhancements

Sources/SwiftDocCUtilities/Utility/DirectoryMonitor.swift
This temporarily disables the functionality on Windows to match the Linux port.  We should be able to reimplement this functionality as already done in clang and swift-tools-support-core on Windows.
=> Utility: disable `DirectoryMonitor` on Windows temporarily

Package.swift
We need to replicate the target definition to exclude some files when building for Windows as they depend on NIO to create the PreviewServer. Rather than adding the files and conditionally removing the content, remove the files from being built.
=> build: split the SwiftDocCUtilitiesTest for Windows

Sources/docc/main.swift
Allow list Windows execution.  Without this change, we would fail to run the CLI tool.
=> docc: indicate Windows as being supported

Package.resolved
A follow-up PR for #607 
The original PR only updates Package.swift and does not update the corresponding Package.resolved file.
It will cause a git diff every time we open the package locally.
=> Fix Package.resolved syncing issue with Package.swift

Tests/SwiftDocCTests/Utility/SynchronizationTests.swift
Windows does not support pthreads.  Adjust the tests to use the Windows APIs for locking where the primitive being used is the `SRWLOCK`.
=> Tests: adjust synchronization tests for Windows

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://110177531
This fixes a crash when writing a symbol link to a symbol that doesn't have a page.
The hierarchy based link resolver used to assume that every symbol from the symbol graph files could be linked to but that isn't true. Some default implementation symbols don't have pages in the documentation build and aren't available for linking.
With this change, the link resolver detects that there is no page for the found symbol and raises a specific error message.
None
In a project where extension symbols are disabled (`DOCC_EXTRACT_EXTENSION_SYMBOLS = NO` in Xcode, ` --exclude-extended-types` with the Swift-DocC plugin
- Extend an external protocol with a new public symbol. For example
```swift
extension Identifiable {
public func something() {}
}
```
- …
=> Fix a crash when linking to a symbol that doesn't have a page

Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Failure to unwrap would trigger an assertion failure whereas the use of `XCTUnwrap` will fail the test case and permit the remainder of the test suite to be processed.  This allows us to better understand the state of the test suite coverage when porting.
=> Tests: use `XCTUnwrap` over forced unwrappng

Tests/SwiftDocCTests/Servers/DocumentationSchemeHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/DirectoryMonitorTests.swift
Treat Windows similarly to Linux as the functionality is near similar in completeness.  While it is possible to support the DirectoryMonitor on Windows, it is not yet implemented in DocC, so simply treat it as we do Linux.
=> Tests: treat Windows as Linux

Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandSourceRepositoryTests.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ErrorMessageTests.swift, Tests/SwiftDocCUtilitiesTests/C+Extensions.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
The strings need to be converted to UTF16 before being set into the environment control block.  Introduce helper wrappers for the functions to allow the conversion to be centralised.
=> SwiftDocCUtilitiesTests: add wrappers for `setenv` and `unsetenv`

Tests/SwiftDocCTests/Utility/SynchronizationTests.swift
`sleep` is not portable as it is not a standard C function.  Use the Foundation function to provide a single codepath across all the targets.
=> Tests: replace `sleep` with `Thread.sleep(forTimeInterval:)`

Sources/SwiftDocC/Model/Rendering/References/ExternalLocationReference.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift, Tests/SwiftDocCTests/Rendering/Rendering Fixtures/external-location-custom-url.json, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift
Bug/issue #, if applicable: rdar://110536969
When a DownloadReference or ExternalLocationReference are decoded from JSON, they both modify URL when re-encoded back to JSON. This can cause issues if the URL is different from what either of these types use as their default (`/downloads/file` and the identifier, respectively). This PR tweaks the Codable logic for both of these types to always use the decoded URL when re-encoding.
None
This bug manifests when the Render JSON is modified after rendering, and then re-encoded after the fact. As such, testing is restricted to the automated test added in this PR.
=> keep the original URL when decoding Download/ExternalLocationReference

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/RenderMetadata.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Article/Article.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Metadata/TitleHeading.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/TitleHeading.md, Tests/SwiftDocCTests/Infrastructure/TestExternalReferenceResolvers.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Semantics/MetadataTests.swift, Tests/SwiftDocCTests/Test Bundles/BookLikeContent.docc/MyArticle.md, Tests/SwiftDocCTests/Test Bundles/MixedManualAutomaticCuration.docc/TestBed.md
Bug/issue #: #408
Add support for an `@TitleHeading` directive that allows for customizing the text of a page-title heading (also known as an eyebrow or kick).
In a documentation catalog with symbol graph files and documentation extension files:
1. Preview the documentation for that docc catalog with `docc preview /path/to/Example.docc` 
2. In the documentation extension file for the module symbol: add a title heading directive. For example:
```
@Metadata {
@TitleHeading("Release Notes")
}
``` 
3. Navigate to that page in the preview. The custom title heading ("Release Notes") should appear as the title heading for that symbol.
=> Add authoring support for `@TitleHeading` directive

Sources/SwiftDocC/Model/Rendering/References/ExternalLocationReference.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift, Tests/SwiftDocCTests/Rendering/Rendering Fixtures/external-location-custom-url.json, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/621
- **Explanation**: This PR updates DownloadReference and ExternalLocationReference to always keep a decoded URL instead of using their default processing.
- **Scope**: Affects systems which post-process Render JSON to include URLs other than what DocC originally generated.
- **GitHub Issue**: rdar://110536969
- **Risk**: Low. This change does not affect normal documentation generation, and only changes the behavior when the Render JSON data types are used after the fact to load and re-encode Render JSON data.
- **Testing**: New tests have been added to verify the new behavior.
=> [5.9] keep the original URL when decoding Download/ExternalLocationReference

Sources/SwiftDocC/Model/Rendering/References/ExternalLocationReference.swift, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift
Bug/issue #, if applicable: rdar://110803672
Allows clients to access and modify the destination URL for an `ExternalLocationReference`.
None.
A unit test has been added to cover this functionality.
=> Make `ExternalLocationReference` url property public and mutable

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Semantics/Metadata/PageKind.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://110182993
When `@PageKind` is used to set an article's kind, it doesn't actually set the kind for the `DocumentationNode` created from that article, only the `RenderNode` role. This PR sets the node kind for the `DocumentationNode` when the article is loaded, so that it can be used e.g. in the `linkable-entities.json` file emitted from the node.
None
To test, use a documentation catalog that includes an article that uses `@PageKind(sampleCode)`. The bundle at `Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc` has two such articles, `MyExternalSample` and `MyLocalSample`, and is used in the following instructions.
Steps:
1. `swift run docc convert --output-path .build/output.docarchive --emit-digest 'Tests/SwiftDocCTests/Test …
=> `@PageKind` sets the kind for the documentation node

Tests/SwiftDocCTests/Utility/LMDBTests.swift
Ensure that we release the open handles before attempting to clean up the temporary directory.  This repairs the execution of 11 tests on Windows, bringing us to a 95% pass rate (excluding `LogHandleTests`).
=> Tests: adjust LMDB test harness for Windows

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Semantics/Metadata/PageKind.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Cherry-pick of #626
- **Explanation**: The `@PageKind` directive doesn't set the DocumentationNode's kind, which means that the kind rendered into `linkable-entities.json` is incorrect for these pages.
- **Scope**: Affects users of `@PageKind` who also use the digest files emitted by Swift-DocC.
- **Issue**: rdar://110182993
- **Risk**: Low. Documentation output should not be affected.
- **Testing**: An automated test has been added to ensure the correct behavior.
- **Reviewer**: @d-ronnqvist
=> [5.9] `@PageKind` sets the kind for the documentation node

Sources/SwiftDocC/Infrastructure/Symbol Graph/ExtendedTypeFormatTransformation.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Test Bundles/ModuleWithEmptyDeclarationFragments.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/ModuleWithEmptyDeclarationFragments.docc/ModuleWithEmptyDeclarationFragments.md, Tests/SwiftDocCTests/Test Bundles/ModuleWithEmptyDeclarationFragments.docc/ModuleWithEmptyDeclarationFragments.symbols.json, Tests/SwiftDocCTests/Test Bundles/ModuleWithEmptyDeclarationFragments.docc/ModuleWithEmptyDeclarationFragments@Swift.symbols.json
Bug/issue #, if applicable: rdar://110683602
In current development builds of the Swift compiler, some extension block symbols are emitted with an empty `declarationFragments` array. This causes the extension block symbol converter to crash with an out-of-bounds access when it tries to strip away the `extension SomeType` part of the declaration to find its where clause. This PR fixes this logic by guarding against the length of the array as well as its existence.
None
I haven't isolated how to properly reproduce this (other than "export-import Foundation in a project"), so the test is restricted to the sample data i added in this branch.
Steps:
1. `swift run docc convert 'Tests/SwiftDocCTests/Test Bundles/ModuleWithEmptyDeclarationFragments.docc'`
2. Ensure that docc does not crash when …
=> don't crash on an extension with an empty declaration

Tests/SwiftDocCUtilitiesTests/Utility/LogHandleTests.swift
`FileHandle` transacts in `HANDLE`s on Windows rather than file descriptors.  This makes it impossible to replace the end point of the pipe after it has been created as the conversion from a HANDLE to a file descriptor transfers ownership and as such the FileHandle does not work with file descriptors at all.  Replicating that behaviour here would detach the `FileHandle` associated with the `Pipe` and thus cannot be done inline.
=> Tests: disable the LogHandle tests on Windows

Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticEngine.swift, Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://110782381
If an error is thrown before the documentation converter completes successfully, the diagnostic engine is never finalized. This means that diagnostic consumers that gather and write diagnostic as two separate steps won't write any diagnostics.
This PR changes that so that the diagnostic engine is finalized before the documentation converter returns from `convert(...)`. It also makes the finalization synchronous so that callers can rely on any diagnostics having been written after `convert(...) ends—either successfully or with a thrown error.
None
- Run `docc convert` with a `--diagnostics-file /path/to/some-file.json` and some content that result in an unexpected error (for example a symbol graph file with relationships but no symbols).
- After …
=> Finalize the diagnostic engine if an error is thrown

Sources/SwiftDocC/Model/Rendering/References/ExternalLocationReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/CodableRenderReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertFileWritingConsumer.swift, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://111121386
This PR refactors `DownloadReference` and `ExternalLocationReference` to deprecate the latter by incorporating it into the former. Now that there is a property on `DownloadReference` to prevent rewriting the URL upon encoding, this refactor takes advantage of that to incorporate the original uses of `ExternalLocationReference` back into `DownloadReference`.
None
This is primarily an internal refactor, but there are two major changes in the output: `external-assets.json` will no longer be generated (its previous contents will now be folded into the `downloads` property of `assets.json`, and references that would have used the `externalLocation` reference type (i.e. `@CallToAction(url:_:)`) now instead use the `download` reference type.
Steps:
1. …
=> deprecate ExternalLocationReference in favor of DownloadReference

Sources/SwiftDocC/Model/Rendering/References/ExternalLocationReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/CodableRenderReference.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertFileWritingConsumer.swift, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/638
- **Explanation**: This PR refactors `DownloadReference` to perform the same behavior as `ExternalLocationReference`, and changes `@CallToAction` to emit the former.
- **Scope**: Affects users of `@CallToAction`.
- **Issue**: rdar://111121386
- **Risk**: Low. The two types were already tested to be Codable-compatible, so the only net change is that the references created by `@CallToAction` will use the `download` kind instead of `externalLocation`.
- **Testing**: Automated tests have been updated to ensure that behavior stays the same.
=> [5.9] deprecate ExternalLocationReference in favor of DownloadReference

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: https://github.com/apple/swift-docc/issues/640 (rdar://111227479)
This fixes a false positive warning when a symbol with characters that aren't allowed in a resolved reference URL is curated. The warning happened because 2nd pass curation visited the link again before it was added to the referenceIndex.
None
Build documentation for the MeshGenerator project, as described in this issue https://github.com/apple/swift-docc/issues/640
=> False positive warning when curating symbol with special character

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/642
- **Explanation**: This fixes a false-positive link resolution warning by moving the creation of the resolved reference lookup earlier in the content registration so that it's available if curation crawling takes two passes.
- **Scope**: Curated symbols with special characters (for example `<=(_:_:)`)
- **Issue**: rdar://111227479
- **Testing**: Added new automated test to verify that curating these symbols no longer cause false positive warnings. 
- **Reviewer**: @QuietMisdreavus
=> [5.9] False positive warning when curating symbol with special character

Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Tests/SwiftDocCTests/Rendering/RenderContentCompilerTests.swift
With the corresponding swift-docc-render PR, Close #477.
Make visitLineBreak return new line instead of space to align with [CommonMark spec](https://spec.commonmark.org/0.30/#hard-line-break)
> Issue is tracked at https://github.com/apple/swift-docc-render/issues/697
Update RenderContentCompilerTests.swift
=> Make visitLineBreak return new line instead of space

Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticEngine.swift, Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/637
- **Explanation**: Ensure that diagnostics are reported if an error is thrown before the documentation converter completes successfully.
- **Scope**: Unreported diagnostics.
- **Issue**: rdar://110782381
- **Testing**: Added new automated test to verify that DocC writes a diagnostic file when the converter throws an error.
- **Reviewer**: @daniel-grumberg
=> [5.9] Finalize the diagnostic engine if an error is thrown

Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Semantics/Snippets/Snippet.swift, Sources/SwiftDocC/Utility/MarkupExtensions/BlockDirectiveExtensions.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/Reference/TabNavigatorTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCTests/Test Bundles/BookLikeContent.docc/MyArticle.md, Tests/SwiftDocCTests/Test Bundles/Snippets.docc/Snippets.md
- Explanation: Allow some directives in doc comments.
- Scope: Small in scope. Completes a feature that was pitched already.
- GitHub Issue: rdar://111414385 and https://github.com/apple/swift-docc/issues/591
- Risk: Low risk: isolated change and well-tested.
- Testing: End to end testing with Swift-DocC-Render. Additional unit tests have been added.
- Original PR: https://github.com/apple/swift-docc/pull/641
- Reviewer: @ethan-kusters
=> [5.9] Allow certain directives in documentation comments

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: Closes #632
This pull request makes it so that articles can contain links to specific headings on the same page, using both `<doc:Heading>`, and `<doc:#Heading>` syntax.
None, once the PR is ready, itself — I think there are three failing test cases still.
I've added a test in `testArticleSelfAnchorLinks.swift`, and verified this behavior manually, too. To test that a `#heading` link works, you can add a subheading link to an existing document bundle, and rebuild the docs.
=> Allow anchor <doc:#heading> within same article

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
The unit tests will occasionally desire to clean up the generated index while retaining a reference to the NavigatorIndex instance.  This is prevented on Windows as the LMDB environment will preserve an open handle which results in the index not being removed.
Adding an internal API to support this use case as this is used for tests only AFAICT.
=> Indexing: add a workaround for clearing the index

Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystem.swift
When constructing a `URL` with a file path, we should always use `init(fileURLWithPath:)` as not all paths are represented as a URL and require additional encoding.  On Windows, this would result in us stripping the drive prefix (`C:`) which would corrupt the path and thus fail to lookup the item.  In the second instance, this allowed us to simply avoid an object copy entirely.
This helps improve the test pass rate significantly on Windows.
=> SwiftDocCUtilitiesTests: adjust `TestFileSystem`'s handling of paths

README.md
This pull request adds a paragraph in README describing how to invoke a locally built `docc` when using SwiftPM, setting `DOCC_EXEC` env variable. 
I was working on #652 and debugged my ideas that way, thought I'd add a doc entry for that.
None. 
To test whether it works:
1. Build `docc` as usual
2. run `DOCC_EXEC=./build/debug/docc swift generate-documentation --target=TARGET`
- [-] Added tests
- [-] Ran the `./bin/test` script and it succeeded
=> Document using DOCC_EXEC in SwiftPM

Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/656
- **Explanation**: For ease of processing, this PR changes DownloadReference to encode an explicit `null` when `checksum` is not present.
- **Scope**: Affects tools which process Render JSON after generation.
- **Issue**: rdar://111865266
- **Risk**: Very low. There is no behavior change in DocC itself, and the resulting Render JSON is equivalent in semantics.
- **Testing**: A test has been added to ensure the output JSON is as expected. Existing automated tests still pass.
=> encoded an explicit null for DownloadReference's checksum

Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Tests/SwiftDocCTests/Rendering/RenderContentCompilerTests.swift
- **Explanation**: Make visitLineBreak return new line instead of space
- **Scope**: Impacts lineBreak markdown output
- **GitHub Issue**: #477
- **Risk**: Low, only `visitLineBreak` logic is impacted
- **Testing**: See the corresponding test update
- **Reviewer**: @d-ronnqvist 
- Original PR: #633
=> [5.9] Make visitLineBreak return new line instead of space

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation**: Adds support for `<doc:#HeadingName>` when linking to a heading on the same page. Today, only `<doc:HeadingName>` or `<doc:ArticleName#HeadingName>` are supported.
- **Scope**: Parsing documentation links into components.
- **GitHub Issue**: #632 
- **Risk**: Low. Small and isolated changes to how the heading "fragment" is parsed in documentation links.
- **Testing**: New tests verify that links to headings within the same article can have a leading "#" character.
- **Reviewer**: @d-ronnqvist 
- Original PR: #652 (by [natikgadzhi](https://github.com/natikgadzhi))
=> [5.9] Allow anchor <doc:#heading> within same article

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift
Bug/issue #, if applicable: rdar://112664398
Swift CI has started failing on Swift-DocC's tests, because its workspace folder includes an `@` sign. This confuses the SymbolGraphLoader into thinking that there are no base-module symbol graphs, and thus refusing to use the `concurrentlyAllFiles` decoding strategy. This PR updates that logic to only inspect the last path component instead of the full file path, allowing these `@` sign directories to successfully detect base-module and extension symbol graphs.
None
Steps:
1. Generate symbol graphs for multiple modules (or copy out two symbol graphs from the "Test Resources" directory) into a directory whose name contains `@`.
2. Run `docc convert` in a debugger and ensure that `SymbolGraphLoader` correctly uses the `concurrentlyAllFiles …
=> only use the last file component when deciding decoding strategy

Tests/SwiftDocCTests/Rendering/RoundTripCoding.swift, Tests/SwiftDocCTests/Servers/FileServerTests.swift
Windows, similar to Linux, requires that we use the explicit encoding of `.utf8` rather than `.fastest`.  This fixes a roundtrip test failure on Windows.
=> Tests: enable the non-Darwin behaviour on Windows

Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
When testing with a rebound volume mount (i.e. using `subst` on Windows), the paths are compared without canonicalisation for the rebound path.  This causes a test failure as although the paths are logically equivalent, they are not physically equivalent.  The `standardizedPath` here ensures that we resolve the junction allowing the path comparison to succeed.
=> Tests: standardize both sides of the URL

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MyUncuratedSample.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/RelativeURLSample.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/SomeSample.md, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
Bug/issue #, if applicable: rdar://112223641
Fixes a regression where sample code pages stopped respecting manual curation. Sample code pages that were manually curated were also being automatically curated – meaning they would show up twice in the technology's topic structure.
This regression was introduced by:
- #626
The proposed solution is to revert the fix from #626 and instead introduce a targeted fix for ensuring that sample code pages use the correct kind in the link destination summary. This allows sample code pages to continue to pretend to be articles during the compilation process and receive correct autocuration behavior because of that – but still create correct link destination entries.
This is likely not the right long-term fix and we should consider how to handle …
=> Fix regression where sample code pages stopped respecting manual curation

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/MyUncuratedSample.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/RelativeURLSample.md, Tests/SwiftDocCTests/Test Bundles/SampleBundle.docc/SomeSample.md, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
- **Explanation**: Fixes a regression where sample code pages stopped respecting manual curation. This made it impossible to curate a sample code page without ending up with duplicate entries for that page.
- **Scope**: Small
- **Issue**: rdar://112223641
- **Risk**: Low. Replaces the original fix for #630 with a more targeted fix directly in link destination summary creation. 
- **Reward**: High. The curation regression doesn't have a workaround besides just not curating sample code pages at all.
- **Testing**: Added a regression test for sample code autocuration. Existing tests for link destination summary creation continue to pass.
- **Original PR:** #674 
- **Reviewers**: @d-ronnqvist
=> [5.9] Fix sample code curation regression

Sources/SwiftDocC/DocumentationService/Models/Services/Convert/ConvertRequest.swift, Sources/SwiftDocC/Model/Rendering/References/TopicColor.swift, Sources/SwiftDocC/Semantics/Metadata/PageImage.swift, Sources/SwiftDocC/Semantics/Metadata/TitleHeading.swift, Tests/SwiftDocCTests/Rendering/SampleDownloadTests.swift
This fixes 2 broken links in documentation comments and fixes a few documentation and code warnings.
None
None
=> Fix 2 links in documentation comments

Sources/docc/DocCDocumentation.docc/adding-structure-to-your-documentation-pages.md
Fixes one minor grammatical error (incorrect verb plurality) and one typographical error (symbols in descriptive sentence don't use code style, inconsistent with other such sentences in the same article) in the "Adding Structure to Your Documentation Pages" article.
=> Fix tiny grammatical typo

Sources/SwiftDocCUtilities/ArgumentParsing/Options/DirectoryPathOption.swift
It should either read as `No documentation directories exist` for plural or `No documentation directory exists` for singular. I've updated the text to use the latter.
=> Fix `ValidationError` text in `DirectoryPathOption.swift`

Sources/SwiftDocC/Servers/FileServer.swift
The file system representation of the URL is OS dependent.  Since we do not have an easy to get the file system representation of a relative path, perform the arc separator translation explicitly through string manipulation.  This helps fix a few errors on Windows.
=> SwiftDocC: handle arc separator on Windows

Sources/SwiftDocCUtilities/Action/Actions/PreviewAction.swift
NIO does not support Windows which prevents the availability of the PreviewServer.  However, the new extension to the `DocumentationContext` in the PreviewAction is used in the ConvertAction and does not rely on NIO.  Make it available without NIO.  This repairs the Windows build.
=> SwiftDocCUtilities: repair the Windows build

Sources/SwiftDocC/Model/TaskGroup.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationCuratorTests.swift
Bug/issue #, if applicable: #679 
rdar://115321138
This adds support for comments after task group list items. When extra content appears after a list item, there is a warning that:
> Extraneous content found after a link in task group list item
However, when a comment is added after a list item, this warning should not occur. This PR adds a check that the extra content is not a comment before creating the warning. 
N/A
Steps:
1. Add a comment in a task group after a link: 
```
- ``link`` 
```
2. Check there are no warnings
=> Adds support for comments in warning about extraneous content found after a link in task group item

Package.resolved, Package.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift, Tests/SwiftDocCTests/Rendering/RenderContentCompilerTests.swift
Update Package.swift to use release branch + Cherry-pick of #708
> Actually IMO the Package.swift update should be committed right after the release/5.10 is cut off. 😄
- **Explanation**: Fix swift toolchain CI test case failing due to the swift-markdown breaking change PR.
- **Scope**: Test case fix
- **Dependency**: https://github.com/apple/swift-markdown/pull/147
- **GitHub Issue**: None
- **Risk**: Low
- **Testing**: None
- **Reviewer**: @eeckstein
=> [5.10] Update swift-markdown and fix test case

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+PathComponent.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Test Bundles/ShadowExtendedModuleWithLocalSymbol.docc/Outer.symbols.json, Tests/SwiftDocCTests/Test Bundles/ShadowExtendedModuleWithLocalSymbol.docc/Outer@Inner.symbols.json
Bug/issue #, if applicable: rdar://109307328
This resolves the root cause of a crash that occurred when a module shadowed the name of a module that it extended two or more times. For example, and "Outer" target that extends an "Inner" target and also shadows the "Inner" name with a top-level symbol
```swift
//  Inner.swift
public struct InnerStruct {}
public class InnerClass {}
```
```swift
// Outer.swift
import Inner
// Shadow the Inner module with a local top-level symbol
public struct Inner {}
// extend two or more types in Inner.
public extension InnerStruct {
func something() {}
}
public extension InnerClass {
func something() {}
}
```
Because `extensionTo` and `declaredIn` relationships weren't used to build up the path hierarchy, the two extensions used a fallback code path that …
=> Use `extensionTo` and `declaredIn` relationships to add extensions to path hierarchy

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+PathComponent.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Test Bundles/ShadowExtendedModuleWithLocalSymbol.docc/Outer.symbols.json, Tests/SwiftDocCTests/Test Bundles/ShadowExtendedModuleWithLocalSymbol.docc/Outer@Inner.symbols.json
Cherry-pick of https://github.com/apple/swift-docc/pull/720
- **Explanation**: Fix a crash in projects that have a public symbol that shadows the name of a module that the project extends.
- **Scope**: Rare crash.
- **Issue**: rdar://116469449
- **Testing**: Added automated test with minimal reproducible example. Manually tested with projects from https://github.com/GetStream/stream-chat-swiftui/pull/369 and rdar://109307328
=> [5.10] Use `extensionTo` and `declaredIn` relationships to add extensions to path hierarchy 

Sources/SwiftDocC/Model/Rendering/RenderNode/RenderNode+Codable.swift, Tests/SwiftDocCTests/Converter/RenderNodeCodableTests.swift, Tests/SwiftDocCUtilitiesTests/IndexActionTests.swift, Tests/SwiftDocCUtilitiesTests/Test Bundles/SingleArticleTestBundle.docc/Info.plist, Tests/SwiftDocCUtilitiesTests/Test Bundles/SingleArticleTestBundle.docc/article.md
Cherry-pick of https://github.com/apple/swift-docc/pull/692
- **Explanation:** Fix bug where the Render Node decoder was failing in the absence of the references key.
- Scope: Single-article catalogs don't get displayed properly in the Xcode doc viewer and single-article archives don't get the index generated correctly.
- **Issue:** https://github.com/apple/swift-docc/issues/711 / rdar://111186939
- Risk: Low.
- **Testing:** Added test that verifies the expected render node decoder doesn't fail in the absence of the references key and that the index gets generated as expected. Manually tested.
- **Reviewer:** @d-ronnqvist
=> [5.10] Fix render node decoder for single-article documentation archives

Sources/SwiftDocC/Model/AvailabilityParser.swift, Tests/SwiftDocCTests/Model/AvailabilityParserTests.swift, Tests/SwiftDocCTests/Rendering/PlatformAvailabilityTests.swift, Tests/SwiftDocCTests/Test Bundles/AvailabilityOverrideBundle.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/AvailabilityOverrideBundle.docc/mykit-iOS.symbols.json
Cherry pick of #712 
- Explanation:  If a symbol is marked unavailable on all the platforms DocC has availability information about, DocC can mark the symbol unconditionally deprecated. This commit adds a check that the symbol is deprecated on at least one platform before the symbol can be displayed as unconditionally deprecated.
- Scope: When no default availability is given to DocC, some symbols can be displayed as deprecated incorrectly.
- Issue: rdar://116485743
- Risk: Low
- Testing: Added unit tests to confirm a symbol has the correct deprecation with an unavailable platform and with both unavailable and deprecated platforms.
- Reviewer: @QuietMisdreavus
=> [5.10] Check symbols are deprecated on at least one platform before marking unconditionally deprecated

build-script-helper.py
The latest trunk snapshot toolchain shows five executables built by SwiftPM that incorrectly have this runpath, including `docc` from this repo:
```
> readelf -d swift-DEVELOPMENT-SNAPSHOT-2023-10-10-a-ubuntu20.04/usr/bin/*|ag "File:|runpath"|ag "ORIGIN[^/]" -B1
File: swift-DEVELOPMENT-SNAPSHOT-2023-10-10-a-ubuntu20.04/usr/bin/docc
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib/swift/linux]
File: swift-DEVELOPMENT-SNAPSHOT-2023-10-10-a-ubuntu20.04/usr/bin/sourcekit-lsp
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib/swift/linux]
File: swift-DEVELOPMENT-SNAPSHOT-2023-10-10-a-ubuntu20.04/usr/bin/swift-build-sdk-interfaces
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../lib/swift/linux]
File: …
```
=> Use new SwiftPM flag to remove `$ORIGIN` from installed docc ELF executable runpath

Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift, Tests/SwiftDocCTests/Test Bundles/ExtensionArticleBundle.docc/Server.md, Tests/SwiftDocCTests/Test Bundles/ExtensionArticleBundle.docc/ServerKit.symbols.json
Close #729 and rdar://79991171
If the range’s source is not matched with the resolver’s source, we should not emit a problem
None
See `func testDuplicatedDiagnosticForExtensionFile()` in `MarkupReferenceResolverTests.swift`
=> Fix duplicated diagnostic issue

Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift, Tests/SwiftDocCTests/Test Bundles/ExtensionArticleBundle.docc/Server.md, Tests/SwiftDocCTests/Test Bundles/ExtensionArticleBundle.docc/ServerKit.symbols.json
Cherrypick of #733
- **Explanation**: Fix duplicated diagnostic issue
- **Scope**: Fix a potential index out of range crash in DefaultDiagnosticConsoleFormatter
- **GitHub Issue**: #729
- **Risk**: Low
- **Testing**: See `func testDuplicatedDiagnosticForExtensionFile()` in `MarkupReferenceResolverTests.swift`
- **Reviewer**: @d-ronnqvist
=> [5.10] Fix duplicated diagnostic issue

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+PathComponent.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Cherry-pick of https://github.com/apple/swift-docc/pull/739
- **Explanation**: A link parsing inconsistency led to subtraction operators (`-(_:_:)`) not being findable if link had hash disambiguation but findable if it redundantly specified both the kind (`-func.op`) and the hash `-abc123`.
- **Scope**: Parsing of authored DocC symbol links.
- **Issue**: rdar://118234516 
- **Testing**: Added tests that both verify the specific parsing behavior and that verifies that such links resolve to the expected symbol when encountered in content.
- **Reviewer**: @patshaughnessy
=> [5.10] Fix symbol link parsing bug for disambiguated subtraction operators

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://118892994
This fixes a crash in a non-standard setup when a multi source-language module is built together with its extending module and the extended modules has representations in multiple source languages.
For the crash to happen it takes 3 symbols in 3 symbol graphs:
- The extended symbol in the main module in one source language
- The extended symbol in the main module in the other source language with the same name as the first source languages' representation. 
- A symbol in the extended module being added as a member of the extended symbol.
When building up a link hierarchy from these symbol graph files, DocC would create separate nodes in the link hierarchy for both language representations of the extended symbol. Then, when processing the …
=> Fix crash where multi-language symbols could get parents not in the tree

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://119183922
Fix a bug where `optionalMemberOf` relationships weren't considered when building the path hierarchy, resulting in incorrect behavior if more than one symbol exist with the container's name.
None
applicable._
Steps:
=> Add `optionalMemberOf` symbol under the correct container symbol

Package.resolved, Package.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/DeclarationsSectionTranslator.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Tests/SwiftDocCTests/Rendering/DeclarationsRenderSectionTests.swift, Tests/SwiftDocCTests/Test Bundles/AlternateDeclarations.docc/AlternateDeclarations.md, Tests/SwiftDocCTests/Test Bundles/AlternateDeclarations.docc/AlternateDeclarations.symbols.json, Tests/SwiftDocCTests/Test Bundles/AlternateDeclarations.docc/Info.plist
Bug/issue #, if applicable: rdar://70594078
When the same symbol has multiple available declarations on the same platform (e.g. when an Objective-C method is imported into Swift and converted into an `async`/`await` version), only one of those declarations is kept. This PR uses in-progress work on SymbolKit to show these declarations in the symbols Declarations section, instead of discarding them.
For example, consider the following Objective-C code:
```objc
@interface MyClass : NSObject
/// Some function with a completion handler.
///
/// This is an Objective-C function where you pass in a completion handler, However, in Swift,
/// you also have the option to run it with `async` and `await`!
- (void)presentWithCompletion:(void (^)(BOOL success))completion;
@end
```
When imported into …
=> use SymbolKit's "alternate declarations" in declarations sections

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/TaskGroup.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Model/TaskGroupTests.swift
Bug/issue #, if applicable: rdar://119279890
Fix a crash when a topic section contained an unsupported directive. 
None
Add some directives other than `SupportedLanguage` to a topic section (before the links). See for example [this test content](https://github.com/apple/swift-docc/pull/763/files#diff-2f4773195a122c13ab57aa39efac9235a4c402cc5b0ab1037ee97a4515f88501R3361-R3371).
Building documentation for this content shouldn't crash.
=> Fix a crash when a topic section contained an unsupported directive

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Kind.swift, Sources/SwiftDocC/Model/SourceLanguage.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Test Bundles/CxxNamespaces.docc/CxxNamespaces.md, Tests/SwiftDocCTests/Test Bundles/CxxNamespaces.docc/CxxNamespaces.symbols.json, Tests/SwiftDocCTests/Test Bundles/CxxNamespaces.docc/Info.plist
Bug/issue #, if applicable: rdar://117904448
This PR starts adding support for C++ symbol graphs, based on Clang's initial support. For the moment, the `c++` symbol language is currently lumped into "Objective-C" alongside C itself; proper standalone support for a "C++" language kind should be coordinated with Swift-DocC-Render to ensure that there is full support.
In addition, this PR also introduces support for namespace symbols, as those are new in C++ compared to Objective-C.
https://github.com/apple/swift-docc-symbolkit/pull/65
As C++ symbol graphs are in a state of preliminary support in Clang (they are currently on the main branch of `llvm/llvm-project` and are [being integrated into `apple/llvm-project`](https://github.com/apple/llvm-project/pull/7856)), a basic symbol graph is …
=> add support for C++ symbol graphs and namespace symbols

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+PathComponent.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Test Bundles/InheritedOperators.docc/Operators.symbols.json
Cherrypick of #717 
**Explanation:** Fixes two bugs where operators with a "/" in the name couldn't be linked to and where their data files in the output archive could collide with other pages's data files.
**Scope:** Symbols with "/" in the name, for example `/(_:_:)` and `/=(_:_:)`.
**Issue:** rdar://112555102
**Risk:** Low.
**Testing:** Added test, ran the existing tests, and manually tested in different scenarios.
**Reviewer:** @patshaughnessy
=> [5.10] Fix bugs with symbol links to `/(_:_:)` operators (#717)

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable:  rdar://119603319
Regression was presumably introduced in da16aa9. When the node is an article we don’t want to check the offset because is not a source file.
Before the fix, the logic was removing all problems because it wouldn’t contain an offset, falling through the else condition.
N/A
Steps:
1. From an article inside a doc catalog link to an non-existing symbol or article
2. Preview the doc catalog
3. Check the console for `doesn't exist at` warnings 
=> Fix bug where DocC no longer emits warnings for unresolved links in article files.

Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Dump.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Serialization.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://119389007
Fix a crash where if a developer added a technology root with the same file name as a module, the technology root would _replace_ the module node and effectively drop all the symbols in the project.
None.
In any project with documentation for a module; add a manual `@TechnologyRoot` and name the file the same as the module name (with a ".md" extension). 
Build documentation for the project. DocC shouldn't crash but may still run into https://github.com/apple/swift-docc/issues/593
=> Prevent a manual technology root from overriding the module node with the same name

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContext+RootPageTests.swift, bin/check-source
This makes `@TechnologyRoot` optional in article-only documentation.
When building documentation for a catalog of only articles with no explicit root article, DocC will follow the following logic to find a root:
- If there's only a single article in the catalog, that becomes the root.
- Otherwise, if there's an article with the same file name as the catalog name, that's becomes the root.
- Otherwise, synthesize a minimal root with the same name as the catalog.
If this looks like a decent approach then we should document this behavior somewhere before merging.
None.
- Create a new documentation catalog: 
`mkdir MyCatalog.docc`
- Add a minimal article without a technology root: 
`echo "# One article\n\nArticle abstract" > MyCatalog.docc/MyArticle.md` 
- Preview …
=> Make `@TechnologyRoot` optional in article-only documentation

Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://120374614
This adds support for resolving links in a symbol's `@DeprecationSummary` content. 
Previously the `ReferenceResolver` didn't visit a symbol's `deprecatedSummaryVariants` so any link in that content didn't resolve but also didn't warn about the links being unresolved.
None
In a documentation catalog with any symbol, add documentation extension file with a `@DeprecationSummary` directive that has a link in its content.
Build and preview the documentation. The deprecation summary should link to the other page.
Replace the link with something that won't resolve—for example ` ``NotFound`` `—and rebuild the documentation. There should be a warning about the unresolved link.
Make sure you check off the following items. If they cannot be completed, …
=> Support resolving links in `@DeprecationSummary` content

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Semantics/Article/Article.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Tests/SwiftDocCTests/Infrastructure/TestExternalReferenceResolvers.swift, Tests/SwiftDocCTests/Semantics/ArticleTests.swift
Bug/issue #, if applicable: rdar://114654594
Fix a crash when configuring a `@DisplayName` for a non-symbol.
The crash happened because the article created a new `Metadata` value to remove the `DisplayName` but didn't properly initialize all the properties which was only possible because the `ChildDirective` property wrapper deferred the initialization through an implicitly unwrapped optional.
A directive that conforms to `AutomaticDirectiveConvertible` is really only intended to be created that way so this other `Metadata` initializer shouldn't exist. Unfortunately it _has_ to exist to support the workaround for <rdar://78718811> (#468) but we can hide it better to make sure that it's only used in that specific place.
None.
Create a documentation catalog with a root page that also has a …
=> Fix a crash when configuring a `@DisplayName` for a non-symbol

Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/documenting-a-swift-framework-or-package.md
Bug/issue #, if applicable: rdar://119959258 
This fixes a syntax issue that prevented a link from displaying in the Tip aside on https://www.swift.org/documentation/docc/documenting-a-swift-framework-or-package
None
1. `docc preview Sources/docc`
2. Go to documentation/docc/documenting-a-swift-framework-or-package in the local preview
The Tip aside should link to "[build a documentation archive for a Swift package](https://apple.github.io/swift-docc-plugin/documentation/swiftdoccplugin/generating-documentation-for-hosting-online/)."
=> Fix link syntax issue in public documentation page

bin/check-source
This updates the allowed years in `check-source` script to include 2024. 
Note that this _isn't_ a cherry-pick because this change was made in #778 which we didn't cherry-pick onto the 5.10 release.
None.
Run `check-source`, it shouldn't warn about the year in the check-source file itself.
=> [5.10] Update allowed years in check-source script

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Semantics/Article/Article.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Tests/SwiftDocCTests/Infrastructure/TestExternalReferenceResolvers.swift, Tests/SwiftDocCTests/Semantics/ArticleTests.swift
Cherrypick of #783
**Explanation:** Fix a crash when adding a `@DisplayName` metadata directive to an article.
**Scope:** Articles with an unsupported `@DisplayName` metadata directive.
**Issue:** rdar://114654594
**Risk:** Low.
**Testing:** Added tests and ran the existing automated tests.
**Reviewer:** @mayaepps
=> [5.10] Fix a crash when configuring a `@DisplayName` for a non-symbol (#783)

Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift
Cherrypick of #784 
**Explanation:** This adds support for resolving links in a symbol's `@DeprecationSummary` content.
**Scope:** Local and external links in content in inside symbol's optional `@DeprecationSummary` directive. 
**Issue:** rdar://120374614
**Risk:** Low.
**Testing:** Added tests and ran the existing automated tests.
**Reviewer:** @sofiaromorales
=> [5.10] Support resolving links in `@DeprecationSummary` content (#784)

Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/documenting-a-swift-framework-or-package.md
Cherrypick of #787
**Explanation:** Fix link syntax issue so that the link displays as expected in the Tip aside on https://www.swift.org/documentation/docc/documenting-a-swift-framework-or-package
**Scope:** Hosted documentation
**Issue:** rdar://119959258
**Risk:** Low.
**Testing:** Locally previewed the DocC documentation
**Reviewer:** @daniel-grumberg
=> [5.10] Fix link syntax issue in public documentation page (#787)

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Model/Identifier.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://119577248
Use dashes in the link component if an article file name contains whitespaces
None
In any project; create an article with whitespace in the filename.
Write a documentation link to that article where the sequences of whitespace is replaced with dashes.
=> Replace spaces with dashes in links to articles

Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://116540790
Fix a bug where only links to external _symbols_ were included in the generated See Also sections. 
None
This can be tested using `bin/test-data-external-resolver` as an external resolver:
1. Set `DOCC_LINK_RESOLVER_EXECUTABLE` to the `test-data-external-resolver` path
2. Set `DOCC_HTML_DIR` to swift-docc-render-artifact checkout path (`/path/to/swift-docc-render-artifact/dist`)
3. In a documentation catalog that curates some local page somewhere, also curate an external link `<doc://com.test.bundle/something>` 
For example, with an Article.md file in Something.docc:
```md
An article.
```
and a Root.md file:
```md
@Metadata {
@TechnologyRoot
}
Curate a local article and an external link
- <doc:Article>
- <doc://com.test.bundle/something>
```
5. …
=> Keep external links to non-symbols in generated See Also sections

Sources/SwiftDocC/Model/Identifier.swift, Tests/SwiftDocCTests/Converter/RenderNodeCodableTests.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/IdentifierTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
This implements a better key for the cache of `ResolvedTopicReference` storage. 
Using a concatenated `String` as a key in one of the examples from the [Understanding Swift Performance WWDC 16][1] video. The struct key in this PR still stores string values but it avoids creating a new string. The performance difference is only measurable in micro benchmarks but this has a small (~0.5%) measurable memory reduction when looking at a full `docc convert` call. 
[1]: https://developer.apple.com/videos/play/wwdc2016/416/
None
None. This change isn't user facing. 
=> Implement a better cache key for resolved references

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Model/Identifier.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Cherry pick of #773 
**Explanation:** Fix a bug where articles with whitespace in their filename couldn't be linked to by using "-" instead of sequences of whitespace characters in the written links.
**Scope:** Articles with whitespace in their filenames.
**Issue:** <rdar://119577248>
**Risk:** Low.
**Testing:** Added tests and ran the existing automated tests.
**Reviewer:** @sofiaromorales 
Note that I made one additional commit https://github.com/apple/swift-docc/commit/93b099de3ac101a6da02c0300aca3c719743f530 to update the added test to account for a feature that isn't cherry-picked into the 'release/5.10' branch but that exist on 'main' where #773 was originally merged.
=> [5.10] Replace spaces with dashes in links to articles

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift
Cherrypick of https://github.com/apple/swift-docc/pull/754
**Explanation:** Fix role heading for API Collections.
**Scope:** Articles that link to symbols in the Topics section now will show "API Collection" as the eyebrow title.
**Issue:** rdar://90789460
**Risk:** Low.
**Testing:** Locally previewed the DocC documentation and implemented the corresponding unit tests.
**Reviewer**: @d-ronnqvist @daniel-grumberg @patshaughnessy
=> [5.10] Fix problem where API Collections had no roleHeading assigned.

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://118477834 & rdar://118478212
This fixes an issue on Linux where documentation extensions didn't match symbols if the symbol has spaces in its name. 
None
Since neither Swift not C/Objective-C has whitespace in symbol names you'll need to hand craft a JSON file with a symbol with a space in its name to test this. Once you have such a symbol graph file, create a documentation catalog with an extension file for the symbol with the space in its name and build documentation for it on Linux. The content in the extension file should be added to the symbol.
(Note that the added test performs these same steps)
=> Support documentation extensions on Linux for symbols with spaces in their name 

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://122034140
This avoids the processing symbols that are potential "top level candidates" in the `PathHierarchy` if those symbols have already been processes for another platforms or source languages.
I also found that the existing tests were doing an unnecessary `XCTUwrap` so I removed that.
None.
- Create a Swift project with a public protocol with some requirement and provide a default implementation for that protocol requirement
- Extract symbol graphs for at least two platforms for that project. 
- Run `swift run docc convert --additional-symbol-graph-dir` and pass both platform's symbol graph files to DocC.
- The above performs a debug build but shouldn't hit any of the assertions that verify the internal path hierarchy in DocC.
Make sure you check …
=> Avoid debug assertions bout adding the same symbol to the path hierarchy twice

Sources/SwiftDocC/Infrastructure/Extensions/KindIdentifier+Overloads.swift
Bug/issue #, if applicable: None
This PR adds static/type subscripts as an overloadable symbol kind, per discussion in #740.
None
The following code demonstrates overloaded type subscripts:
```swift
public class MyClass {
public class subscript(_ idx: Int) -> Int {
get {
return idx
}
}
public class subscript(_ idx: String) -> String {
get {
return idx
}
}
}
```
A documentation catalog containing a symbol graph with these symbols is available here: [asdf.docc.zip](https://github.com/apple/swift-docc/files/14247680/asdf.docc.zip)
1. Ensure that a recent main-branch Swift-DocC-Render (or swift-docc-render-artifact) is available in `$DOCC_HTML_DIR`.
2. `swift run docc preview --enable-experimental-overloaded-symbol-presentation asdf.docc`
3. Navigate to either of `MyClass`'s type subscripts …
=> add type subscripts to overloadable symbol kinds

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/Diffing/AnyRenderSection.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/CodableContentSection.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSection.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/MentionsSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/Symbol/MentionsRenderSection.swift, Sources/SwiftDocC/Semantics/Article/ArticleSymbolMentions.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Sources/SwiftDocC/Utility/FeatureFlags.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCTests/Rendering/MentionsRenderSectionTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift, Tests/SwiftDocCTests/Semantics/ArticleSymbolMentionsTests.swift, Tests/SwiftDocCTests/Utility/XCTestCase+MentionedIn.swift
Adds an optional, new section to symbol documentation pages called "Mentioned In", containing up to five links to articles that mention the symbol in the abstract or discussion, scored by mention count (abstract mentions are worth more). The purpose of this section is to highlight explanatory and conceptual content in which the symbol plays an important or central role.
This functionality is currently hidden by the `--enable-experimental-mentioned-in` flag.
rdar://121899474
=> Record article mentions of symbols

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+PathComponent.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
This handpicks some of the changes from #643 to make it easier to support other types of link disambiguation without adding any new link disambiguation. 
Specifically, this wraps the path component disambiguation as its own type instead of storing the values directly on the path component. This means that in the future, if we added a new type of link disambiguation—like in #643—then all the places that process path component disambiguation would already be switching over the type of disambiguation.
A follow up PR will handpick some more changes from #643 to change how the path hierarchy internally stores its disambiguated elements.
None
Nothing in particular. 
- ~[ ] …
=> Make it easier to support other link disambiguation in the future

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocCTestUtilities/SymbolGraphCreation.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift
Bug/issue #, if applicable:  rdar://116399438
Fix a bug causing DocC to display repeated platforms due to variations in platform names between multiple SGFs and the Info.plist. This change unifies platform name variations into their canonical form during symbol graph loading.
N/A
Steps:
1. Preview the attached docs.
2. Assert that the symbol `A` only shows one tag for the platform 'Mac Catalyst'.
[116399438.docc.zip](https://github.com/apple/swift-docc/files/14330750/116399438.docc.zip)
=> Standardize platform name variances during Symbol Graph loading.

Sources/docc/DocCDocumentation.docc/footer.html
Bug/issue #, if applicable: rdar://123145742
This updates the year in the custom footer that DocC uses in its hosted documentation on Swift.org
None
Build DocC documentation with custom templates enabled
```sh
xcrun docc preview Sources/docc/DocCDocumentation.docc --experimental-enable-custom-templates
```
Inspect the year in the footer
=> Update year in footer for hosted documentation to 2024

Sources/SwiftDocC/Utility/FileManagerProtocol.swift, Sources/SwiftDocCTestUtilities/TestFileSystem.swift, Sources/SwiftDocCUtilities/Action/Actions/MergeAction.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: rdar://123281955
This avoids a Swift compiler crash in the latest 5.11 toolchain on Linux
```
1.	Swift version 5.11-dev (LLVM f74ee64f7c77089, Swift 53e268bf5bf88cb)
2.	Compiling with the current language version
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { PrepareOptimizationPasses, EarlyModulePasses, HighLevel,Function+EarlyLoopOpt, HighLevel,Module+StackPromote, MidLevel,Function, ClosureSpecialize, LowLevel,Function, LateLoopOpt, SIL Debug Info Generator } on SIL for SwiftDocCUtilitiesTests)
4.	While running pass #15197 SILModuleTransform "PerformanceSILLinker".
5.	While deserializing SIL function "$s10Foundation11FileManagerC9SwiftDocC0bC8ProtocolA2dEP18temporaryDirectoryAA3URLVvgTW"
6.	*** DESERIALIZATION FAILURE ***
*** If any …
```
=> Avoid ambiguous `FileManager.temporaryDirectory` definition in tests on Swift CI

Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
rdar://117158675
Today DocC normally encodes aside block content as JSON like this:
```json
{
"type": "aside",
"content": [
],
"style": "important"
}
```
...for a set of standard styles ("tip", "important", "experiment", etc.). These styles are defined in the [Swift Markdown package](https://github.com/apple/swift-markdown/blob/main/Sources/Markdown/Interpretive%20Nodes/Aside.swift#L25).
Aside blocks can also use a custom style that is not defined in Swift Markdown, in which case DocC will encode the aside as JSON by setting style="note" and then appending an optional name attribute:
```json
{
"type": "aside",
"content": [
],
"style": "note",
"name": "Some Custom Title"
}
```
When decoding asides, DocC uses the opposite logic: If both style="note" and a name …
=> Relax rules for decoding JSON for asides with custom styles 

Sources/SwiftDocC/Infrastructure/Diagnostics/ANSIAnnotation.swift, Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticConsoleWriterDefaultFormattingTest.swift
Bug/issue #, if applicable: rdar://122345738
This updates the default diagnostics formatter to skip highlighting the line if the diagnostic range is incorrect. 
Currently the default diagnostics formatter assumes that all the diagnostic ranges are correct and crashes—instead of printing any diagnostics—if they are not.
With these changes we'll also assert in debug builds if the diagnostic range is incorrect with extra information for us to investigate where the diagnostic with incorrect ranges originated from to help us fix the root cause of the incorrect diagnostic range. 
Because of this assertion we can't add a test that the diagnostic isn't highlighted when the range is incorrect. I feel that the assertion—helping us find and fix the root cause of these issues—is more valuable than …
=> Fix crash when emitted diagnostics have incorrect source ranges

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/ExternalPathHierarchyResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver.swift, Sources/SwiftDocC/Utility/FileManagerProtocol.swift, Sources/SwiftDocCTestUtilities/FilesAndFolders.swift, Sources/SwiftDocCTestUtilities/TestFileSystem.swift, Sources/SwiftDocCUtilities/Action/Actions/Action+MoveOutput.swift, Tests/SwiftDocCTests/Infrastructure/ExternalPathHierarchyResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
Bug/issue #, if applicable: rdar://116085974
This improves the support for external documentation dependencies by resolving symbol references found in declarations and relationships in the local symbol graph files.
> [!IMPORTANT]
> There is more work needed to support this end-to-end. If you run this now you'll notice that the external links are 404s in the browser unless you host both archives on the same server.
None
To test this you need a project with two documentable targets. 
- Build documentation for one of the targets and pass `--enable-experimental-external-link-support` to enable linking to this documentation.
- Check that the output directory contains a "linkable-entities.json" file and a "link-hierarchy.json" file. (This hasn't changed since #710 but can help verify that the …
=> Resolve dependency symbol reference in declarations and relationships

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/AttributesSectionTranslator.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeDictionaryDataTests.swift, Tests/SwiftDocCTests/Test Bundles/DictionaryData.docc/dictionary.symbols.json, Tests/SwiftDocCTests/XCTestCase+AssertingTestData.swift
Bug/issue #, if applicable: rdar://121475839&121224338
Important details recorded in symbol graphs about the allowed values of a data type, such as minimum and maximum values, default values, and enumerated values, were not getting used to generate an `AttributeRenderSection` on a symbol's page. That data now gets passed through to the render JSON.
None.
Add one of the value constraint fields to a data type in a symbol graph (eg, `"minimum": 12`) and compile the documentation. The render JSON for the data type should include an "attributes" primary content section with the attribute value.
=> Populate the "Attributes" section based on OAS data

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Dump.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Serialization.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift
This is a small refactor to change how the path hierarchy internally stores its disambiguated elements, changing the implementation from nested dictionaries per name collision per node to small lists per name collision per node. 
The benefit of a small list is that new disambiguating information can be added without increasing the depth of the nested dictionaries at each node.
None.
Nothing in particular.
=> Make it easier to store other types of link disambiguating information in the path hierarchy 

Sources/SwiftDocC/DocumentationService/Convert/Fallback Link Resolution/ConvertServiceFallbackResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://122964958
This fixes a regression where the convert service fallback resolver was asked to resolve _all_ unresolved links, not just the unresolved links to local content.
None
It's rather cumbersome to test this end-to-end since it requires another project to use `SwiftDocC` as a framework dependency and create a `ConvertService` and send requests for certain content. You'd more or less reimplement `testDoesNotResolveLinksUnlessBundleIDMatches()` but in a new project.
=> Don't resolve ConvertService fallback links unless bundle ID matches

Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/docc/DocCDocumentation.docc/linking-to-symbols-and-other-content.md, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCTests/Test Bundles/TestBundle.docc/documentation/myprotocol.md, Tests/SwiftDocCTests/Test Resources/TestBundle-RenderIndex.json, Tests/SwiftDocCTests/Test Resources/testNavigatorIndexGeneration.txt, Tests/SwiftDocCTests/Test Resources/testNavigatorIndexGenerationTechnologies.txt, Tests/SwiftDocCTests/Test Resources/testNavigatorIndexGenerationWithLanguageGrouping.txt, Tests/SwiftDocCTests/Test Resources/testNavigatorIndexPageTitleGeneration.txt, Tests/SwiftDocCUtilitiesTests/Test Bundles/TestBundle.docc/documentation/myprotocol.md
Bug/issue #, if applicable: rdar://78908451
This extends the existing, but undocumented, support for linking to headers to also include linking to task groups / topic sections.
I had initially thought that including all the task groups in the anchor sections would be too slow or increase memory usage too much but in my local benchmarking the difference is too small to measure. 
None.
Follow the added documentation to write links to headings or task groups, both on the current page and on other pages
=> Support linking to authored task groups / topic sections

Sources/docc/DocCDocumentation.docc/linking-to-symbols-and-other-content.md
Bug/issue #, if applicable: rdar://124124417
Clarify that links to tutorials don't _need_ a `/tutorials/` prefix. 
Also, document that it's possible to add a `/documentation/` prefix and give an example of when this could be useful.  
None.
None. This only changes documentation.
=> Clarify that links to tutorials don't need a /tutorials/ prefix

Sources/SwiftDocC/Semantics/Metadata/DocumentationExtension.swift, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/DocumentationExtension.md, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md, Sources/docc/DocCDocumentation.docc/adding-supplemental-content-to-a-documentation-catalog.md, Tests/SwiftDocCTests/Semantics/DocumentationExtensionTests.swift, Tests/SwiftDocCTests/Semantics/MetadataTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
Bug/issue #, if applicable: rdar://79096832
This updates a few different places in the DocC documentation that talk about the `DocumentationExtension` directive to explain what the default behavior is. 
It also removes examples that redundantly specifies the `append` behavior since readers could assume that it's required. To identify redundant configuration and help developer clean up their markup, specifying `DocumentationExtension(mergeBehavior: append)` not results in a warning informing the developer that the configuration is redundant and behaves the same as removing the `DocumentationExtension` configuration. 
> Note: this behavior hasn't changed. Explicitly specifying an `append` behavior has always behaved the same as not specifying a `DocumentationExtension` directive at all. …
=> Document the default behavior of the `DocumentationExtension` directive

Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
This removes two print-statements in test code.
None.
Run these two tests. They shouldn't print anything.
=> Remove two print statements in tests

Sources/SwiftDocC/Semantics/ExternalLinks/ExternalReferenceWalker.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://120374614
This fixes a bug where external links in a symbol's deprecation summary content didn't resolve unless that external link was also used anywhere else in the project's content.
None.
This can be tested using `bin/test-data-external-resolver` as an external resolver:
1. Set `DOCC_LINK_RESOLVER_EXECUTABLE` to the `test-data-external-resolver` path
2. Set `DOCC_HTML_DIR` to swift-docc-render-artifact checkout path (`/path/to/swift-docc-render-artifact/dist`)
3. In a documentation catalog with some some deprecated symbols, add a documentation extension file for the deprecated symbols and add an external link in a `@DeprecationSummary` directive. For example:
```md
@DeprecationSummary {
Use <doc://com.test.bundle/something> instead.
}
Link to external …
```
=> Collect external links from _symbol_ deprecation summary content

Sources/SwiftDocCTestUtilities/TestFileSystem.swift, Sources/SwiftDocCUtilities/Action/Actions/MergeAction.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/MergeActionTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystemTests.swift, bin/update-gh-pages-documentation-site
Bug/issue #, if applicable: rdar://124270602
This small follow up PR to #821 updates the script that DocC uses to build and host its contributor documentation to work the the latest changes to the merge command and moves some directory creation code out of a loop.
None
Nothing in particular
=> Update the DocC documentation script so that it works with the changes to the merge command

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://117174884
Currently, if any two articles have the same filename, DocC will warn for one of the files that it is a redeclaration and the file will be skipped. Article filenames need to be unique because those base names are used for the article's URL which need to be unique. However, documentation extensions' filenames have no impact on the URLs of any pages, so there's no need to enforce unique filenames for them. 
This change skips the enforcement of unique filenames for documentation extensions to allow doc extensions to have the same filenames and for a doc extension to have the same filename as an article.
Steps:
1. Create two documentation extensions with the same filename (in different directories in the catalog). Optionally, also add a regular …
=> Don't enforce unique filenames for documentation extensions

Tests/SwiftDocCTests/Utility/LMDBTests.swift
Bug/issue #, if applicable: rdar://125770540 
This fixes the Linux CI crashing due to unaligned read from buffer in a LMDB test. For example:
https://ci.swift.org/job/pr-swift-docc-linux/1243/
None
Verify that the Linux CI passes. 
- ~[ ] Updated documentation if necessary~ Not applicable
=> Explicitly load unaligned data in test

Sources/SwiftDocC/SwiftDocC.docc/Resources/ThemeSettings.spec.json
The `ThemeSettings.spec.json` file specifies that the key under `theme` for the dictionary of colors is `colors`. However, when used in practice, the correct key is `color`; `colors` does not work. This corrects the spec to match the implementation.
(In truth, it seems like `colors` would be both more accurate and more consistent, but changing the implementation to match the spec would be _considerably_ wider-ranging and have significant compatibility implications.)
N/A, documentation-only change
=> Fix incorrect key name in ThemeSettings spec JSON

Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift, Sources/SwiftDocC/Utility/FileManagerProtocol.swift, Sources/SwiftDocCTestUtilities/TestFileSystem.swift, Sources/SwiftDocCUtilities/Action/Actions/Action+MoveOutput.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertFileWritingConsumer.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/CoverageDataEntry+generateSummary.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/JSONEncodingRenderNodeWriter.swift, Sources/SwiftDocCUtilities/Action/Actions/CoverageAction.swift, Sources/SwiftDocCUtilities/Action/Actions/EmitGeneratedCurationAction.swift, Sources/SwiftDocCUtilities/Action/Actions/Init/InitAction.swift, Sources/SwiftDocCUtilities/Action/Actions/MergeAction.swift, Sources/SwiftDocCUtilities/Action/Actions/TransformForStaticHostingAction.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Merge.swift, Sources/SwiftDocCUtilities/Transformers/StaticHostableTransformer.swift, Sources/SwiftDocCUtilities/Utility/DirectoryMonitor.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticConsoleWriterDefaultFormattingTest.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/MergeSubcommandTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/EmitGeneratedCurationsActionTests.swift, Tests/SwiftDocCUtilitiesTests/FolderStructure.swift, Tests/SwiftDocCUtilitiesTests/Init/InitActionTests.swift, Tests/SwiftDocCUtilitiesTests/MergeActionTests.swift, Tests/SwiftDocCUtilitiesTests/StaticHostableTransformerTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystemTests.swift
Bug/issue #, if applicable: rdar://125785105
This follows up on #861 to add back the temporarily reverted commit to use package access level (SE-0386, available from Swift 5.9) instead of SPI for FileManagerProtocol.
None
Nothing in particular. This isn't a use facing change.
=> Use package access level (SE-0386) instead of SPI for FileManagerProtocol

Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift, Sources/SwiftDocC/Utility/FileManagerProtocol.swift, Sources/SwiftDocCTestUtilities/TestFileSystem.swift, Sources/SwiftDocCUtilities/Action/Actions/Action+MoveOutput.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertFileWritingConsumer.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/CoverageDataEntry+generateSummary.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/JSONEncodingRenderNodeWriter.swift, Sources/SwiftDocCUtilities/Action/Actions/CoverageAction.swift, Sources/SwiftDocCUtilities/Action/Actions/EmitGeneratedCurationAction.swift, Sources/SwiftDocCUtilities/Action/Actions/Init/InitAction.swift, Sources/SwiftDocCUtilities/Action/Actions/MergeAction.swift, Sources/SwiftDocCUtilities/Action/Actions/TransformForStaticHostingAction.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Merge.swift, Sources/SwiftDocCUtilities/Transformers/StaticHostableTransformer.swift, Sources/SwiftDocCUtilities/Utility/DirectoryMonitor.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticConsoleWriterDefaultFormattingTest.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/MergeSubcommandTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/EmitGeneratedCurationsActionTests.swift, Tests/SwiftDocCUtilitiesTests/FolderStructure.swift, Tests/SwiftDocCUtilitiesTests/Init/InitActionTests.swift, Tests/SwiftDocCUtilitiesTests/MergeActionTests.swift, Tests/SwiftDocCUtilitiesTests/StaticHostableTransformerTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystemTests.swift
- **Explanation:** This uses package access instead of instead of SPI for DocC's FileManagerProtocol. The reason for wanting this on the 6.0 release branch is so that other cherry-picks don't need to make syntax changes to make SPI imports.
- **Scope:** Developer experience. No functional changes.
- **Issue:** rdar://125785105
- **Testing:** Existing tests pass. 
- **Original PR:** https://github.com/apple/swift-docc/pull/878
=> [6.0] Use package access level (SE-0386, available from Swift 5.9) instead of SPI for FileManagerProtocol (#878)

Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json
The JSON schema for RenderNode is invalid, as it includes an extra comma at the final element of an array (that is only valid in JavaScript, and not JSON).
I also checked the other JSON Schemas to make sure there were no other invalid syntaxes.
None
Parse the JSON in any conforming implementation
=> Fix JSON typo

Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift
rdar://126504994
A unit test failed under certain circumstances because it tested for a precise line in an expected error message.
None
Run the unit test as follows:
```
% swift test --filter testDataCorruptedPlist
```
- ~~[ ] Added tests~~
- [x ] Ran the `./bin/test` script and it succeeded
- ~~[ ] Updated documentation if necessary~~
=> Ignore precise line number in unit test expectation

Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift
**Explanation:** A unit test failed under certain circumstances because it tested for a precise line in an expected error message.
**Scope:** One unit test change
**Issue:** rdar://126504994
**Risk:** Low.
**Testing:** Existing tests pass.
**Reviewer:** @QuietMisdreavus 
**Original PR:** https://github.com/apple/swift-docc/pull/887
=> [6.0] Ignore precise line number in unit test expectation

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Symbol/TaskGroupRenderSection.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/RenderNodeDiffingBundleTests.swift
Bug/issue #, if applicable: rdar://125967110
This adds an anchor to `TaskGroupRenderSection` so that links to task groups scroll to that section (after the corresponding DocC Render change (rdar://124536381) is implemented).
None.
- Build documentation for any project with manual or automatic curation. 
- Inspect the JSON files in the output. 
- The entries in the "topicSections" array should have an "anchor"
=> Add an anchor to TaskGroupRenderSection

Sources/SwiftDocC/Model/Rendering/Content/RenderBlockContent+Capitalization.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/DiscussionSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/ParametersSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/ReturnsSectionTranslator.swift, Sources/SwiftDocC/Utility/FoundationExtensions/String+Capitalization.swift, Tests/SwiftDocCTests/Infrastructure/AutoCapitalizationTests.swift, Tests/SwiftDocCTests/Model/RenderBlockContent+CapitalizationTests.swift, Tests/SwiftDocCTests/Utility/String+CapitalizationTests.swift
- **Explanation**: When writing a doc comment, it feels intuitive to not capitalise the first word of its description because of the nature of the doc comment.
- For example: adding a new parameter would be written as: /// - Parameter testParam: this parameter is just a test parameter to show what this looks like in lowercase.
- In this example, the sentence in doc comments is natural to write with a lowercase starting word, because the first word (Parameter) is already capitalized.
- This PR auto-capitalizes the first word of a new section or aside.
- Note that this auto-capitalization only occurs if the first word is all lowercase and contains only characters A-Z, or if the first word contains CharacterSet punctuation characters (e.g. a period, comma, hyphen, semi-colon, colon).
- …
=> [6.0] Auto-Capitalize first word

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/Rendering/Symbol/TaskGroupRenderSection.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/RenderNodeDiffingBundleTests.swift
- **Explanation:** This encodes an anchors for TaskGroupRenderSection so that links to topic sections scroll to that heading on the page.
- **Scope:** Links to topic sections
- **Issue:** rdar://124536381
- **Testing:** Added automated tests. Manually verified that DocC Render reads the anchors and that clicking on a DocC created link to a topic section scrolls to that heading on that page.
- **Reviewer:** @daniel-grumberg  
- **Original PR:** #883
=> [6.0] Add an anchor to TaskGroupRenderSection

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://125948615
This fixes two different bugs found in the same project:
- If two language variants of the same symbol, of the same symbol kind, have the same name with different capitalization, then that symbol would sometimes not be assigned a path (hitting an precondition later in the build) depending on which language variant was processed first.
- If an extension adds a member to a symbol with different kinds in different language representations, then DocC would sometimes hit an assertion about the symbol having an unexpected parent in the hierarchy depending on which language variant was processed first.
None
- Configure a project to build documentation for both Swift and Objective-C
- Define a class in either language with a member with different …
=> Fix inconsistent assertions with some language variant symbols

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** Fix two bugs that could cause symbols to sometimes not get assigned a path, which resulted in a precondition failure later in the documentation build.
- **Scope:** Inconsistent crashes for some mixed source-language projects. 
- **Issue:** rdar://125948615
- **Testing:** Added automated tests. Manually verified the fix in the project where these issues were first found.
- **Reviewer:** @daniel-grumberg  
- **Original PR:** #894
=> [6.0] Fix inconsistent assertions with some language variant symbols (#894)

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://125964139
This fixes a confusing diagnostic solution when a misspelled link matches the also misspelled bundle name (specified in an Info.plist)
None
In a any project with some module documentation:
- Add a documentation catalog with an Info.plist file that specifies a _misspelled_ version of the module name for "CFBundleDisplayName".
- In any content, for example a documentation comment or an article, write a _symbol link_ using the _misspelled_ version of the module name.
- Build documentation for the project.
- The diagnostic about the unresolved link should only suggest to replace the misspelled name with the correctly spelled module name.
=> Don't suggest bundle name as possible replacement for symbol links

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
Bug/issue #, if applicable: rdar://125855186
When building the navigator index, it first collects the nodes into a tree based on their topic group curation. Then, for any node that is not curated into another node, it inserts them all into the navigator root. However, this step can erroneously create a situation where symbols and articles can appear outside a rendered doc archive, depending on how the archive is being loaded. While this is useful and necessary for articles (if articles are not curated into a bundle and DocC is processing more than bundle, adding them outside the hierarchy is still useful), symbols should all already be curated into place via automatic curation. If automatic curation dropped a symbol (e.g. when an overloaded symbol is being condensed into an overload …
=> drop uncurated symbols from the navigator index

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationBundle+Info.swift, Sources/SwiftDocC/Infrastructure/Workspace/FeatureFlags+Info.swift, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC.md, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/AddingFeatureFlags.md, Sources/SwiftDocC/Utility/FeatureFlags.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://126305435
This PR adds a new field to the Info.plist to set feature flags without using the command line. Right now, this only adds support for the overloads feature, but this mechanism is in place to facilitate adopting experimental features that affect how a bundle is written.
None
To test this feature, make a copy of the `OverloadedSymbols.docc` test bundle and modify its Info.plist to look like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleName</key>
<string>ShapeKit</string>
<key>CFBundleDisplayName</key>
<string>ShapeKit</string>
<key>CFBundleIdentifier</key>
<string>com.shapes.ShapeKit</string> …
```
=> add the ability to set a subset of feature flags from Info.plist

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Tests/SwiftDocCTests/Infrastructure/ExternalPathHierarchyResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Add logic to look for overload groups when emitting warnings and suggestions about ambiguous symbols. If exactly one of the ambiguous symbols is an overload group, then suggest the author simply remove the incorrect disambiguation instead of selecting a different disambiguation hash.
rdar://126382989
Today when an author links to a page using an invalid disambiguation hash, DocC emits a warning similar to this listing all of the valid disambiguation hashes:
```
warning: '7w26t' isn't a disambiguation for 'init(content:)' at '/MyFramework/SomeStruct'
--> SomeStruct.md:7:19-7:25
5 | ### Some Interesting Topic
6 |
7 + - ``init(content:)-7w26t``
|                   ├─suggestion: Replace '7w26t' with '25rvu' for'something'
|                   ├─suggestion: Replace '7w26t' with '4tm5u' …
```
=> Add logic to look for overload groups when emitting warnings

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationBundle+Info.swift, Sources/SwiftDocC/Infrastructure/Workspace/FeatureFlags+Info.swift, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC.md, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/AddingFeatureFlags.md, Sources/SwiftDocC/Utility/FeatureFlags.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
* **Explanation**: Adds new fields to Info.plist to allow enabling the overloads feature without using the command-line flag.
* **Scope**: Enhancement for users of the overloads feature in a managed environment like Swift Package Index.
* **Issue**: rdar://126305435
* **Original PR**: https://github.com/apple/swift-docc/pull/891
* **Risk**: Low. Existing documentation catalogs will not be affected, as the feature flags mechanism will continue to fall back to command-line flags.
* **Testing**: Automated tests were added to support the new behavior.
* **Reviewer**: @d-ronnqvist @patshaughnessy @mayaepps
=> [6.0] add the ability to set a subset of feature flags from Info.plist

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
- **Explanation**: Remove symbols that were not curated by AutomaticCuration from the navigator index, to prevent them from appearing outside of any module.
- **Scope**: QOL fix for clients of the LMDB navigator index, e.g.  Xcode's documentation window.
- **Issue**: rdar://125855186
- **Original PR**: https://github.com/apple/swift-docc/pull/890
- **Risk**: Low. The symbols were already being dropped from the JSON representation of the navigator index (used by Swift-DocC-Render) without issue.
- **Testing**: Automated tests were updated to reflect the new behavior.
- **Reviewer**: @d-ronnqvist @patshaughnessy
=> [6.0] drop uncurated symbols from the navigator index

Sources/SwiftDocC/Catalog Processing/GeneratedCurationWriter.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorTree.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext+Breadcrumbs.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/DocumentationCurator.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/TopicGraph.swift, Sources/SwiftDocC/Model/Rendering/Navigation Tree/RenderHierarchyTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Utility/Graphs/DirectedGraph+Cycles.swift, Sources/SwiftDocC/Utility/Graphs/DirectedGraph+Paths.swift, Sources/SwiftDocC/Utility/Graphs/DirectedGraph+Traversal.swift, Sources/SwiftDocC/Utility/Graphs/DirectedGraph.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationCuratorTests.swift, Tests/SwiftDocCTests/Infrastructure/TopicGraphTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/DirectedGraphTests.swift
Bug/issue #, if applicable: rdar://126974763
This fixes a few different issues with infinite recursion, which ultimately surface as crashes, when the content contains cyclic curation. 
There were two main issues:
- Multi source-language projects can have the same symbol in different places in the different language representation which are all mixed in the topic graph. These multiple paths to and from symbol in the hierarchy makes it possible to create cycles through a mix of automatic and manual curation. 
- Even if the topic graph didn't contain curation, the navigator is based on the rendered topic sections which don't filter out any curation. 
The first issue surfaced as an infinite recursion in `DocumentationContext/pathsTo(...)` which incorrectly assumed that the topic graph was …
=> Fix a few issues with infinite recursions if the content contains cyclic curation

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Tests/SwiftDocCTests/Infrastructure/ExternalPathHierarchyResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** This updates the warning about unknown disambiguation suffixes to suggest dropping the suffix and to use simplified symbol title in the diagnostic message, for the suggestion to link to the parent overload group page.
- **Scope:** Misleading warnings
- **Issue:** rdar://119518818
- **Testing:** Added unit tests
- **Reviewer:** @d-ronnqvist 
- **Original PR:** #885
=> [6.0] Add logic to look for overload groups when emitting warnings (#885)

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** This fixes a confusing error message that can happen for misspelled links to the module (for example when creating a top-level documentation extension file) when the documentation catalogs Info.plist file specifies a slight misspelling of the module name for the project's "bundle name".
- **Scope:** Confusing error message.
- **Issue:** rdar://125964139
- **Testing:** Added unit test.
- **Reviewer:** @sofiaromorales  
- **Original PR:** #900
=> [6.0] Don't suggest bundle name as possible replacement for symbol links (#900)

Sources/SwiftDocC/Catalog Processing/GeneratedCurationWriter.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorTree.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext+Breadcrumbs.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/DocumentationCurator.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/TopicGraph.swift, Sources/SwiftDocC/Model/Rendering/Navigation Tree/RenderHierarchyTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Utility/Graphs/DirectedGraph+Cycles.swift, Sources/SwiftDocC/Utility/Graphs/DirectedGraph+Paths.swift, Sources/SwiftDocC/Utility/Graphs/DirectedGraph+Traversal.swift, Sources/SwiftDocC/Utility/Graphs/DirectedGraph.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationCuratorTests.swift, Tests/SwiftDocCTests/Infrastructure/TopicGraphTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/DirectedGraphTests.swift
- **Explanation:** This fixes two crashes and a few minor related issues that can happen in some cases when building documentation that has cyclic curation. 
- **Scope:** Crashes (infinitely recursing until the the process runs out of stack) when building documentation with some cases of cyclic curation.
- **Issue:** rdar://126974763
- **Testing:** Added automated tests for both crashes. Manually tested with the project where these issues were originally found.
- **Reviewer:** @mayaepps @patshaughnessy 
- **Original PR:** #898
=> [6.0] Fix a few issues with infinite recursions if the content contains cyclic curation

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://126580675
This fixes a bug where DocC would stop searching as soon as it found any match while resolving a link, even if that match wasn't valid for the search (for example a non-symbol match for a symbol link). This resulted in "Symbol links can only resolve symbols" errors for some symbol links if there was a closer non-symbol match to the page that contained the link.
Now, DocC will check that the match is valid for the search, and if it's not; DocC will remember the error message from the first match but continue searching to see if there's another _valid_ match.
None
In a project with some top-level symbol, 
- Add an article with a heading (or topic section) with the same name as the symbol and also link to that symbol with a symbol link. For …
=> Continues searching if a non-symbol matches a symbol link

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocCTestUtilities/SymbolGraphCreation.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://127130136
When symbol graphs reflect overload groups that are different across different platforms, Swift-DocC runs into a situation where it can load inconsistent information based on which platform's mixins are loaded for the initial `overloadsVariants`. In some situations (where a symbol is only overloaded on one platform), this can even create a crash in debug builds since Swift-DocC trips an assertion about missing overload data from SymbolKit.
This PR builds on https://github.com/apple/swift-docc-symbolkit/pull/72 to use unified overload groups when calculating overload information. This allows Swift-DocC to present a unified view of overloads across every platform.
https://github.com/apple/swift-docc-symbolkit/pull/72
Use the following …
=> use unified overload data for initial overload variants

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocCTestUtilities/SymbolGraphCreation.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
- **Explanation**: Uses a new SymbolKit implementation of overload grouping to fix some bugs about overload handling.
- **Scope**: Bug fixes for an experimental feature
- **Issue**: rdar://127130136
- **Original PR**: https://github.com/apple/swift-docc/pull/907
- **Risk**: Low. The major implementation happened in SymbolKit, and the resulting behavior change only happens for the experimental overloads feature.
- **Testing**: Automated testing has been added to ensure the expected behavior.
- **Reviewer**: @patshaughnessy @mayaepps @d-ronnqvist
=> [6.0] use unified overload data for initial overload variants

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
This fixes an issue where a heading with the same name as a symbol could cause symbol link to not find the heading. This issue is solved by moving the check that the found page is a symbol deeper into the implementation so that DocC can skip non-symbol pages and continue searching for symbol matches.
Note: The diff is significantly smaller than it looks. It's basically 6 lines that moved from one place to another but because the inner implementation is indented one level deeper than before, it look like ~100 lines changed.
- **Scope:** Confusing warning for some symbol links that should resolve without warnings.
- **Issue:** rdar://126580675
- **Testing:** 
- **Reviewer:** @mayaepps @patshaughnessy 
- **Original PR:** #901
=> [6.0] Continues searching if a non-symbol matches a symbol link (#901)

Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable:  127227456
Apply fallback availability logic to beta information.
For platforms that have a fallback platform, copy the availability information passed through the CLI, including the `isBeta` value.
The fallback platform logic works correctly for availability information passed through the SGFs but does not apply to availability information passed through the --platform CLI option. This inconsistency caused unexpected behavior. For instance, a symbol would copy the version from iOS, which is also marked as beta, and display it as available for both iOS and iPadOS, but only as beta for iOS.
This PR aims to fix this by also adding the same fallback mechanism to the information about the current release of a platform passed through the CLI.
N/A.
Steps:
1. Download …
=> Apply fallback availability logic to beta information

Sources/SwiftDocC/Infrastructure/DocumentationConverter.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
- **Explanation:** The fallback platform logic works correctly for availability information passed through the SGFs but does not apply to availability information passed through the --platform CLI option. This inconsistency caused unexpected behaviour. This PR copy the availability information passed through the CLI, including the isBeta value.
- **Scope:** Bug fix and enhancement.
- **Issue:** rdar://127227456
- **Original PR:** https://github.com/apple/swift-docc/pull/910
- **Testing:** Unit and manual testing
- **Reviewer:** @d-ronnqvist @patshaughnessy
=> [6.0] Apply fallback availability logic to the CLI platform version parameter.

Sources/SwiftDocC/Infrastructure/NodeURLGenerator.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Tests/SwiftDocCTests/Model/RenderContentMetadataTests.swift, Tests/SwiftDocCTests/Rendering/HeadingAnchorTests.swift
On behalf of @hironytic :
- **Explanation:**  This fixes a bug where links to headings written in Japanese or other text that need percent encoding (other than whitespace and punctuation which DocC replaces with dashes) doesn't work. Specifically, this fixes two issues:
- the heading element didn't percent encode its anchor text
- the reference URL double percent encoded the fragment portion of the URL
- **Scope:** Links to headings that require percent encoding don't work
- **Issue:** https://github.com/apple/swift-docc/issues/458 rdar://127870203
- **Testing:** A new test verifies that a heading and a link to that heading both percent encode the anchor/fragment correctly.
- **Reviewer:** @d-ronnqvist 
- **Original PR:** #867
=> [6.0] Fix a doc anchor is not encoded correctly (#867)

Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift
Bug/issue #, if applicable: rdar://126273913
To allow for a smoother transition when enabling the overloads feature for the first time, this PR avoids automatically curating an overload group if all its constituent overloads were manually curated. This way, if a documentation author had already tried to manually curate all the symbols in a package or framework, enabling the overloads feature doesn't spuriously add any new symbols that would disrupt that manual curation.
None
Use this doc bundle to test this feature: 
The symbol graph in the bundle was generated from the following code: [asdf.docc.zip](https://github.com/apple/swift-docc/files/15268536/asdf.docc.zip)
The symbol graph contained in this bundle was generated from the following code:
```swift
/// This is a cool class.
///
/// …
```
=> drop overload groups from curation if the overloads were manually curated

Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift
- **Explanation**: Drops overload groups from automatic curation if all the constituent overloads are manually curated, to avoid creating unnecessary new pages in a curation hierarchy.
- **Scope**: UX improvement for an experimental feature
- **Issue**: rdar://126273913
- **Original PR**: https://github.com/apple/swift-docc/pull/913
- **Risk**: Low. The code path only affects the optional overloads feature, and the modification is minor.
- **Testing**: Automated testing has been added to verify the desired behavior.
- **Reviewer**: @d-ronnqvist
=> [6.0] drop overload groups from curation if the overloads were manually curated

Sources/SwiftDocC/Checker/Checker.swift
The compiler should enforce `any` syntax here. The fix (https://github.com/apple/swift/pull/72659) depends on this change because compiler pull request testing builds Swift-DocC.
This is a purely syntactic change.
=> Mark existential with `any` to unblock compiler bug fix

Sources/SwiftDocC/Indexing/Navigator/AvailabilityIndex+Ext.swift, Sources/SwiftDocC/Infrastructure/Workspace/DefaultAvailability.swift, Sources/SwiftDocC/Semantics/Symbol/PlatformName.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Rendering/AvailabilityRenderOrderTests.swift, Tests/SwiftDocCTests/Test Resources/Availability.symbols.json
Bug/issue #, if applicable: 127384226
Added missing Apple supported platforms `iPadOS` and `visionOS` and added them into the list of sorted platforms for presentation.
N/A
[PlatformsOrder.docc.zip](https://github.com/apple/swift-docc/files/15401672/PlatformsOrder.docc.zip)
Steps:
1. Preview the provided documentation catalog
2.Assert that the platforms displayed in the availability section are sorted as expected.
=> Add missing Apple supported platforms

Sources/SwiftDocC/Indexing/RenderSection+TextIndexing.swift, Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/ExternalPathHierarchyResolver.swift, Sources/SwiftDocC/Model/Rendering/References/TopicRenderReference.swift, Sources/SwiftDocC/Model/Rendering/Symbol/PlistDetailsRenderSection.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/TestExternalReferenceResolvers.swift, Tests/SwiftDocCTests/Rendering/PlistSymbolTests.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://126292460
This renames the confusingly named `TitleStyle/title` and `TitleStyle/symbol` to `PropertyListTitleStyle/useDisplayName` and `PropertyListTitleStyle/useRawKey` to clarify what they are used for and fixes a fixes a call site that set the `titleStyle` of topic references because it wasn't clear that the API was only for property list keys. 
For the `TopicRenderReference` changes I started by renaming `titleStyle` to `propertyListTitleStyle`, `name` to `propertyListRawKey`, and `ideTitle` to `propertyListDisplayName`. Next, the common prefix led me to group these into a struct to make it even more clear that they are related.  
None.
In any documentation project
- Modify `/path/to/swift-docc-clone/bin/test-data-external-resolver` so that …
=> Rename `TitleStyle` to `PropertyListTitleStyle` to clarify its purpose

Sources/SwiftDocC/Indexing/RenderSection+TextIndexing.swift, Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/ExternalPathHierarchyResolver.swift, Sources/SwiftDocC/Model/Rendering/References/TopicRenderReference.swift, Sources/SwiftDocC/Model/Rendering/Symbol/PlistDetailsRenderSection.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/TestExternalReferenceResolvers.swift, Tests/SwiftDocCTests/Rendering/PlistSymbolTests.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
This fixes an issue where links to content from external sources displayed in a monospace font, even for non-symbols. The root cause of the issue was incorrect use of a misleadingly named API. To guard against similar issues in the future, this change also renamed the misleading API to clarify its purpose.
- **Scope:** Display of links to content from external sources.
- **Issue:** rdar://126292460
- **Testing:** A new automated test verifies that links to external documentation content doesn't set the `titleStyle` anymore. Manually tested that links to the external documentation content no longer displays in a monospace font.
- **Reviewer:** @daniel-grumberg 
- **Original PR:** #919
=> [6.0] Don't use monospace font for links to external non-symbols

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex+Ext.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/RenderNode+NavigatorIndex.swift, Sources/SwiftDocC/Indexing/RenderNode+Relationships.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Sources/SwiftDocC/Model/Rendering/References/TopicImage.swift, Sources/SwiftDocC/Model/Rendering/Variants/VariantPatchOperation.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Model/RenderNodeSerializationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Rendering/Variants/VariantPatchOperationTests.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://127759734
This fixes a major inefficiency in the navigator index creation for large (10k+ symbols) mixed Swift and Objective-C projects. 
With these changes impacted projects will build about 5 times faster total `docc convert` time. Even larger projects may see even faster builds (the biggest improvement that I've seen was ~30 times faster in one project).
Below are two benchmarks from two large mixed Swift and Objective-C projects that show a 6 times improvement and a 5 time improvement compared to current main:
```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Metric                                   │ Change          │ main                 │ current              │ …
```
=> Much faster navigator index creation for mixed Swift and Objective-C projects

Sources/SwiftDocC/Indexing/Navigator/AvailabilityIndex+Ext.swift, Sources/SwiftDocC/Infrastructure/Workspace/DefaultAvailability.swift, Sources/SwiftDocC/Semantics/Symbol/PlatformName.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Rendering/AvailabilityRenderOrderTests.swift, Tests/SwiftDocCTests/Test Resources/Availability.symbols.json
* **Explanation:** This pr adds missing Apple supported platforms `iPadOS` and `visionOS`, and adds them into the list of sorted platforms for a correct presentation in the desired order.
* **Scope:** Symbol availability badges sorting.
* **Issue:** rdar://127384226
* **Risk:** Low.
* **Testing:** Manual testing was made and unit tests were added.
* **Reviewer:** @d-ronnqvist 
* **Original PR:** https://github.com/apple/swift-docc/pull/920
=> [6.0] Add missing Apple supported platforms (#920)

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex+Ext.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/RenderNode+NavigatorIndex.swift, Sources/SwiftDocC/Indexing/RenderNode+Relationships.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Sources/SwiftDocC/Model/Rendering/References/TopicImage.swift, Sources/SwiftDocC/Model/Rendering/Variants/VariantPatchOperation.swift, Sources/SwiftDocC/Model/SourceLanguage.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Model/RenderNodeSerializationTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Rendering/Variants/VariantPatchOperationTests.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
This significantly improves the build time for large (10k+ symbols) mixed Swift and Objective-C projects; about 5 times faster total `docc convert` time. It does so by fixing a major bottleneck in the creation of the navigator index.
- **Scope:** Navigator index creation for mixed Swift and Objective-C projects
- **Issue:** rdar://127759734
- **Testing:** New tests verify that both the fast and slow code paths produce the same navigator index for mixed Swift and Objective-C projects with refined symbol hierarchies. All existing navigator index tests pass. 
- **Reviewer:** @mayaepps 
- **Original PR:** #917
Note:
Some new code depended on the ability to sort source languages which was an underlying change in #856 but which was never cherry-picked over to …
=> [6.0] Much faster navigator index creation for mixed Swift and Objective-C projects

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Indexing/RenderIndexTests.swift
This fixes a bug in the navigator index where pages with custom `@PageImage` icons would use the wrong relative path to refer to that image within the .doccarchive.
- **Scope:** Custom `@PageImage` icons in the navigator index.
- **Issue:** rdar://128397787
- **Testing:** New tests verify that the encoded navigator index uses the correct relative asset path.
- **Reviewer:** @emilyychenn 
- **Original PR:** #925
=> [6.0] Update navigator image references to the correct relative path (#925)

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
Bug/issue #, if applicable: 126713717
When a framework had a display name different to the top level symbol name both variations would appear as availability badges in the symbols that were declared in extensions of that same framework, resulting in  odd availability information.
Before the fix:
After the fix:
This was caused by the logic introduced here:
https://github.com/apple/swift-docc/pull/732/files#diff-68ec34e58e2102fa55684b18f310a856fd3220cf919e869bca4ad5f179ac1f14R1206
N/A
Steps:
1. Preview attached doc catalog.
2. Assert that the availabilities displayed in the `Foo` symbol does not show the framework name.
[AvailabilityBug.docc.zip](https://github.com/apple/swift-docc/files/15407242/Avai …
=> Fix bug where symbols would get the framework name show up twice in the availability badges.

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
* **Explanation:** When a framework had a display name different to the top-level symbol name, both variations would appear as availability badges in the symbols that were declared in extensions of that same framework, resulting in odd availability information.
* **Scope:** Symbol availability badges.
* **Issue:** rdar://126713717
* **Risk:** Low.
* **Testing:** Manual and unit tests.
* **Reviewer:** @d-ronnqvist @patshaughnessy 
* **Original PR:** https://github.com/apple/swift-docc/pull/922
=> [6.0] Fix bug where symbols with display names would get the framework name show up twice in the availability badges. 

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift
Bug/issue #, if applicable: rdar://61899214
Currently, when a developer writes a symbol extension markdown file, and creates a topic section which is named the same as one of the titles which are used for automatic curation ("Initializers", "Instance Properties", "Instance Methods", "Type Aliases", etc.), the result is duplicated sections:
This PR changes this behaviour so that automatically curated section contents are merged with existing sections, if they have the same title:
in `RenderNodeTranslator.visitSymbol(_:)`, after the list of automatically curated task groups has been created, we now check whether there is an existing manually curated section with the same title. 
If it exists, we extend this section in place with the symbol references from the automatically curated task …
=> Merge automatically curated task groups

Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
Bug/issue #, if applicable: None
This PR adds some setup and teardown for the tests in `SwiftDocCUtilitiesTests.ConvertSubcommandTests` to clean up the process environment and working directory before and after each test. This resolves some test flakiness that depended on specific environmental conditions. In particular, it resolves `testParameterValidationFeatureFlag` failing when tests are run sequentially, and resolves `testTreatWarningAsError` failing when a symlink is present in the Swift-DocC directory tree.
None
Steps:
1. `touch test && ln -s test test2`
2. `swift test` (Important: **not** `bin/test`, as the test only failed when run sequentially due to unclean environment)
3. Ensure that all tests pass.
4. `rm test test2` (to clean up your repo state)
Make sure you check off the …
=> Improve test hygiene in ConvertSubcommandTests

Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticConsoleWriterDefaultFormattingTest.swift
Bug/issue #, if applicable: #729
This improved the input validation of the default diagnostic formatter so that incorrectly created diagnostics with out-of-bounds range information won't cause a crash.
None.
Since this needs an incorrectly created diagnostic, it requires a bug that results in out-of-bounds diagnostics to test. 
[This comment](https://github.com/apple/swift-docc/issues/729#issuecomment-2119101213) includes a package that reproduces on such bug. Building it should no longer crash (although it will output a duplicate diagnostic, because _that_ issue is not fixed in this PR).
=> Handle various out-of-bounds diagnostic ranges in default diagnostics formatter

Sources/SwiftDocC/Model/Rendering/Content/Extensions/RenderTermLists.swift, Tests/SwiftDocCTests/Utility/String+WhitespaceTests.swift
This is a micro optimization to make `String/removingLeadingWhitespace()` and `String/removingTrailingWhitespace()` faster. This difference is only measurable in micro benchmarks.
---
I stumbled upon this code while reviewing something else and the repeated String copying irked me. 
Using micro benchmarks I could confirm that using `firstIndex(where:)`/ `lastIndex(where:)` is faster for all amounts of leading and trailing whitespace. In the graphs below, all measurements are divided by the string length.
```swift
" \(String(repeating: "A", count: n)) "
```
```swift
"\(String(repeating: " ", count: n))A\(String(repeating: " ", count: n))"
```
```swift
String(repeating: "A", count: n)
```
Note that green compares to red and yellow compares to blue.
None
None. …
=> Micro optimization for whitespace trimming of strings

Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticConsoleWriterDefaultFormattingTest.swift
- **Explanation:** This adds additional input validation in the default diagnostic formatter, instead of trusting that the diagnostic source range is correct. 
- **Scope:** Potential crashes for diagnostics that have out-of-bounds source ranges due to other bugs.
- **Issue:** rdar://129586253 #729 
- **Testing:** New tests verify that incorrectly created diagnostics with out-of-bounds source ranges are handled by the default diagnostic formatter.
- **Reviewer:** @Kyle-Ye  
- **Original PR:** #947
=> [6.0] Handle various out-of-bounds diagnostic ranges in default diagnostics formatter (#947)

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/ExternalPathHierarchyResolver.swift, Tests/SwiftDocCTests/Infrastructure/ExternalPathHierarchyResolverTests.swift, Tests/SwiftDocCTests/Test Bundles/AvailabilityBetaBundle.docc/mykit.symbols.json, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
- **Explanation**: Fixes a bug where beta status resolution was inconsistent across external and internal links. Unifies the behaviour so that a symbol is only in beta if all its platforms are in beta.
- **Scope**: Affects beta status resolution for all external links to symbols.
- **Issue**: rdar://128997995
- **Risk**: Low/Medium
- **Testing**: Validated by rendering example external symbols locally, and by unit testing (see original PR).
- **Reviewer**: @d-ronnqvist 
- **Original PR**: https://github.com/apple/swift-docc/pull/938
=> [6.0] [external-links] Display frameworks as beta only if all platforms are beta

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticTests.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift, Tests/SwiftDocCTests/Semantics/SnippetTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
Bug/issue #, if applicable: rdar://129677496
This implements a change that @patshaughnessy suggested to me a couple of weeks ago; leveraging the markup's source information to avoid visiting a symbol's markup twice if that symbol's documentation is a mix of in-source comments and documentation extension file content.
Before this change, when a symbol had documentation content from both an in-source documentation comment and a documentation extension file, the context would visit the symbol's full markup twice passing different source URLs to the reference resolver which would filter out any diagnostics that didn't match the markup's source information. 
Now, the reference resolver doesn't have a separate source property and instead relies solely on the source information from the markup. …
=> Avoid visiting symbol markup twice when there's a documentation extension file

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticTests.swift, Tests/SwiftDocCTests/Infrastructure/ReferenceResolverTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift, Tests/SwiftDocCTests/Semantics/SnippetTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
- **Explanation:** This addresses the source of duplicate diagnostics by not visiting a symbol's markup twice when a symbol has documentation from both an in-source doc comment and from a documentation extension file.
This was a source of crashes before https://github.com/apple/swift-docc/pull/948 
- **Scope:** Potential duplicated diagnostics.
- **Issue:** rdar://129677496 
- **Testing:** New tests verify a single pass updates and produces diagnostics for both sources of documentation (in-source doc comment and a documentation extension file). Existing tests and manual testing verifies that no expected diagnostics are missing.
- **Original PR:** #951
=> [6.0] Avoid visiting symbol markup twice when there's a documentation extension file (#951)

Sources/SwiftDocC/Infrastructure/DocumentationBundle.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Workspace/GeneratedDataProvider.swift, Sources/SwiftDocC/Model/Content/AttributedCodeListing.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Name.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCTests/Checker/Checkers/NonInclusiveLanguageCheckerTests.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationCuratorTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/AbsoluteSymbolLinkTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/DocCSymbolRepresentableTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/AvailabilityRenderOrderTests.swift, Tests/SwiftDocCTests/Rendering/ConstraintsRenderSectionTests.swift, Tests/SwiftDocCTests/Rendering/DefaultAvailabilityTests.swift, Tests/SwiftDocCTests/Rendering/DefaultCodeListingSyntaxTests.swift, Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift, Tests/SwiftDocCTests/Rendering/DocumentationContentRendererTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
This removes the AttributedCodeListing type that isn't used for anything. There's no way for developers to pass this form of code listings to DocC (unless they use some other tool that imports the SwiftDocC module). `AttributedCodeListing.Line` appears in public API `DocumentationNode.Name.symbol` but DocC only ever creates `symbol` name values with a single plain text token.
Note, AttributedCodeListing is a feature that was superseded by Snippets and has never been available via the `docc` command line tool.
None.
This is a non-functional change. Everything should continue to behave as before. There's nothing in particular to test.
=> Deprecate the unused AttributedCodeListing type

Sources/SwiftDocC/Model/Rendering/Symbol/AvailabilityRenderMetadataItem.swift, Sources/SwiftDocC/Semantics/Metadata/Availability.swift, Tests/SwiftDocCTests/Semantics/MetadataAvailabilityTests.swift
Adding `deprecated` argument to the directive `@Available`, this is done by adding a field `deprecated` to the `Metadata.Availability` and also addressing all the comments that are related to the issue within the codebase.
This PR also include the `.any` platform for `@Available`, which can be used as follows:
```
@Available(*, introduced: "1.0")
@Available(*, introduced: "1.0", deprecated: "10.0")
```
Closes #441 
Testing
Adding the following metadata into `SwiftDocC/Directives.md`
```
@Metadata {
@Available("Swift DocC", introduced: "1.0", deprecated: "2.0")
}
```
Using [swift-docc-render-artifact](https://github.com/apple/swift-docc-render-artifact)
Steps:
1. Add the above metadata to `Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/Directives.md`.
2. `./bin/preview-docs SwiftDocC`
3. …
=> Adding deprecated to @Available directive

Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/DeclarationsSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/Symbol/DeclarationRenderSection+SymbolGraph.swift, Sources/SwiftDocC/Model/Rendering/Symbol/DeclarationsRenderSection.swift, Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json, Tests/SwiftDocCTests/Rendering/DeclarationsRenderSectionTests.swift, Tests/SwiftDocCTests/Test Resources/FancyOverloads.symbols.json
Bug/issue #, if applicable: rdar://116409531
This PR introduces a new field to declaration tokens in Render JSON: `highlight`. This field indicates that the token is distinct among a set of overloads and should be indicated with a highlight or other style. It also performs a difference comparison of overloaded symbols' declarations so that the fields are populated for Swift-DocC-Render.
When combined with the related Swift-DocC-Render PR (linked below), the rendered page appears like this:
Because the differencing works directly on the declaration fragments received from the symbol graph, this PR also takes some care to break up `.text` tokens to prevent false-positive differences and create a cleaner output. For example, the below overloads correctly only highlight the `<S>` in the …
=> Highlight declaration differences in overloaded symbol groups

Sources/SwiftDocC/Model/Rendering/Symbol/AvailabilityRenderMetadataItem.swift, Sources/SwiftDocC/Semantics/Metadata/Availability.swift, Tests/SwiftDocCTests/Semantics/MetadataAvailabilityTests.swift
**Explanation:** This PR supports adding a deprecated argument to the directive @Available.
**Scope:** @Available directive.
**Issue:** rdar://130516145
**Risk:** Low
**Testing:** Unit tests.
**Reviewer:** @d-ronnqvist  @sofiaromorales 
**Original PR:** https://github.com/apple/swift-docc/pull/851
=> [6.0] Adding deprecated to @Available directive (#851)

Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Sources/SwiftDocC/Model/Rendering/Symbol/AvailabilityRenderMetadataItem.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/AutomaticDirectiveConvertible.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveArgumentValueConvertible.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveArgumentWrapper.swift, Sources/SwiftDocC/Semantics/DirectiveInfrastructure/DirectiveMirror.swift, Sources/SwiftDocC/Semantics/General Purpose Analyses/HasArgumentOfType.swift, Sources/SwiftDocC/Semantics/Metadata/Availability.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/PlatformAvailabilityTests.swift, Tests/SwiftDocCTests/Rendering/SemanticVersionStringRepresentationTests.swift, Tests/SwiftDocCTests/Semantics/MetadataAvailabilityTests.swift
**Explanation:** Fixes an issue where beta badges weren't rendering for non-symbol documentation.
**Scope:** `@Available` directive and any article availability derived from the directive.
**Issue:** rdar://129355087
**Risk:** Low/Medium. The type of a property has changed (see https://github.com/apple/swift-docc/pull/959#discussion_r1665705213), but this applies only to a directive and the rest of the changes are additive.
**Testing:** Validated by rendering a sample code article with availability information locally, plus unit testing (see PR for more info).
**Reviewer:** @d-ronnqvist 
**Original PR:** https://github.com/apple/swift-docc/pull/959
=> [6.0] Compute beta platform information for non-symbol documentation

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorTree.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
This removes some unused code in `NavigatorTree` that I stumbled upon while working on something else.
None
This is a non-functional change. Everything should continue to behave as before. There's nothing in particular to test.
=> Remove unused code in NavigatorTree

README.md
This moves the section about contributions to earlier in the README.md file. The moved content is unchanged.
None.
Not applicable.
Not applicable.
=> Move contributions section earlier in the README

CONTRIBUTING.md, README.md, Sources/SwiftDocC/Indexing/Navigator/RenderNode+NavigatorIndex.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolReference.swift, Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Model/SourceLanguage.swift, Sources/SwiftDocC/Semantics/Metadata/Availability.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Sources/SwiftDocC/Semantics/Symbol/PlatformName.swift, Sources/docc/DocCDocumentation.docc/customizing-the-appearance-of-your-documentation-pages.md, Sources/docc/DocCDocumentation.docc/distributing-documentation-to-other-developers.md, Sources/docc/DocCDocumentation.docc/documenting-a-swift-framework-or-package.md, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Semantics/MetadataAvailabilityTests.swift, bin/update-gh-pages-documentation-site
This makes 4 changes, each in their own commit to update various links from "apple.github.io" to "swiftlang.github.io" and from "github.com/apple" to "github.com/swiftlang". The former is more important since those links don't redirect.
Note that this doesn't update any github.com/apple/swift-nio links or apple.github.io/swift-argument-parser because those repos haven't moved yet.
This also doesn't update the any link in the Package.swift file.
None.
Not applicable
Not applicable
=> Update links for repos that have moved to the swiftlang organization so far

Sources/SwiftDocC/Model/ParametersAndReturnValidator.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/Test Bundles/GeometricalShapes.docc/clang/arm64-apple-macos14.4/GeometricalShapes.symbols.json, Tests/SwiftDocCTests/Test Bundles/GeometricalShapes.docc/swift/arm64-apple-macos/GeometricalShapes.symbols.json
Bug/issue #, if applicable: rdar://130750134
This fixes a bug where parameter and return value documentation wasn't hidden from language representations of a symbol without a function signature (for example properties). 
With these changes, if one of the symbol's language representation has a function signature, all property and return value documentation will be hidden from its language representations that don't have function signatures.
None
- In a mixed Swift and Objective-C project, add a symbol that's a function in C but refines to a property in Swift. For example
```objc
typedef struct {
CGPoint center;
CGFloat radius;
} TLACircle NS_SWIFT_NAME(Circle);
/// Returns whether a circle has zero radius.
/// - Parameter circle: The circle to examine.
/// - Returns: `YES` if the specified …
```
=> Hide parameter and return value documentation from properties.

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift
**Explanation:** This PR fixes the availability selection for Mac Catalyst platform.
**Scope:** API Availability.
**Issue:** rdar://129785705
**Risk:** Low
**Testing:** Unit and manual tests.
**Reviewer:** @d-ronnqvist @anferbui 
**Original PR:** https://github.com/swiftlang/swift-docc/pull/962
=> [6.0] Make MacCatalyst availability information mirror iOS. (#962)

Sources/SwiftDocC/Model/ParametersAndReturnValidator.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/Test Bundles/GeometricalShapes.docc/clang/arm64-apple-macos14.4/GeometricalShapes.symbols.json, Tests/SwiftDocCTests/Test Bundles/GeometricalShapes.docc/swift/arm64-apple-macos/GeometricalShapes.symbols.json
- **Explanation:** This fixes a special case for hiding parameter and return value documentation where a C function that is represented by a property in Swift would display the parameter and return value documentation on the Swift page because the property doesn't have any "function signature" data. 
- **Scope:** Parameter and return value documentation for C functions that are refined as properties in Swift.
- **Issue:** rdar://130750134 
- **Testing:** New tests verify that a Swift property representation of a C function hides the parameter and return value documentation. Manually tested with a few projects that reproduce this issue.
- **Reviewer:** @anferbui 
- **Original PR:** #968
=> [6.0] Hide parameter and return value documentation from properties. (#968)

Sources/SwiftDocC/Model/ParametersAndReturnValidator.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift
Bug/issue #, if applicable: rdar://130496794
This fixes a special case with the validation of parameter and return value documentation where different platforms have different signatures for the language representation of the same symbol.
None.
- Define a C function with different parameters for different platforms, for example:
```c
#if TARGET_OS_OSX
void doSomething(int first);
#else
int doSomething(int first, int second);
#endif
```
- Extract symbol graph files for both platforms
- Document the function in a documentation extension file:
```md
Some documentation for this function
- Parameters:
- first: Some description for the parameter that's available on all platforms.
- second: Some description for the parameter that's available on some platforms.
- Returns: Some description for the …
```
=> Support documenting platform specific properties and return values

Sources/SwiftDocC/Model/DocumentationMarkup.swift, Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift, Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift, Tests/SwiftDocCTests/Test Bundles/BundleWithLonelyDeprecationDirective.docc/CoolClass.coolFunc.md, Tests/SwiftDocCTests/Test Bundles/BundleWithLonelyDeprecationDirective.docc/CoolClass.initConfigCache.md
Bug/issue #, if applicable: Closes #932, rdar://70056350.
Fixes a bug where the `@DeprecationSummary` directive would have no effect if a symbol had multiple lines of documentation comments in its source, like so:
```swift
/// I am adding some amazing documentation for my new struct.
///
/// ## Overview
///
/// In fact it's so cool, that it even needs some markdown.
public struct ExampleDeprecated {}
```
The root cause of the issue was that the `@DeprecatedSummary` directive would only take effect when used in the "Abstract" section of the markup.
When using the default merging strategy for documentation extension files (`append`), documentation extension content is added after all the existing documentation comments, resulting in something like:
```md
I am adding some amazing …
```
=> `@DeprecationSummary` not having effect for some symbols

Sources/SwiftDocC/Model/DocumentationMarkup.swift, Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift, Tests/SwiftDocCTests/Rendering/DeprecationSummaryTests.swift, Tests/SwiftDocCTests/Test Bundles/BundleWithLonelyDeprecationDirective.docc/CoolClass.coolFunc.md, Tests/SwiftDocCTests/Test Bundles/BundleWithLonelyDeprecationDirective.docc/CoolClass.initConfigCache.md
- **Explanation:** Fixes an issue where `@DeprecationSummary` would have no effect if a symbol had multiple lines of documentation comments in its source.
- **Scope:** `@DeprecationSummary` directive.
- **Issue:** rdar://70056350 
- **Testing:** Validated by rendering a documentation extension article for a symbol which was triggering the issue, plus unit testing (see original PR for more info).
- **Reviewer:** @d-ronnqvist 
- **Original PR:** https://github.com/swiftlang/swift-docc/pull/982
=> [6.0] `@DeprecationSummary` not having effect for some symbols

Sources/SwiftDocC/Infrastructure/DocumentationCurator.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationCuratorTests.swift
Bug/issue #, if applicable: rdar://131477513
This improved the warnings about cyclic curation so that they:
- Explain that links in a Topics section contributes to the documentation hierarchy
- Displays all the elements that are involved in the would-be cycle.
None.
- In any documentation project with some articles and/or symbols. For a cyclic curation involving more than two pages.
- Build documentation for the project
- The diagnostic about the cyclic curation should look something like this:
```
warning: Organizing 'Something' under 'SomethingElse' forms a cyclic documentation hierarchy
Links in a "Topics section" are used to organize documentation into a hierarchy. The documentation hierarchy shouldn't contain cycles.
If this link contributed to the documentation hierarchy it would …
```
=> Improve the diagnostics about cyclic curation

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://129282701 rdar://127874910
This primarily fixes a bug where links were DocC didn't resolve any links in the content of a "synthesized" root page.
It also fixes an unrelated bug where an article that got promoted to a root page lost its existing metadata configuration. 
None.
- Create a documentation catalog with a single markup file _without_ a `@TechnologyRoot` directive but with some links that won't resolve. For example:
```md
The link below will fail to resolve:
- ``NotFoundSymbol``
```
- Build documentation for this article-only catalog.
- There should be a warning about the link that doesn't resolve
- Add a `@PageColor` metadata configuration to the page:
```diff
+ @Metadata {
+   @PageColor(red)
+ }
The link below will fail to resolve:
- …
```
=> Support writing links in synthesized technology root pages

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
- **Explanation:** This fixes a bug impacting article-only documentation where DocC wouldn't attempt to resolve any links in an article that was implicitly promoted to a root page. This only happens when one of the article file names match the catalog name (or when there's only a single article, but then it has nothing to link to).
- **Scope:** Links in article-only documentation without an explicit `@TechnologyRoot` page.
- **Issue:** rdar://129282701
- **Testing:** New tests verify that the articles links are resolved and that its authored metadata is preserved.
- **Original PR:** #980
=> [6.0] Support writing links in synthesized technology root pages

Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift
Bug/issue #, if applicable: None
This PR adds a couple `#if os(macOS)` wrappers to some tests that are currently failing on Linux. Some offline discussion pointed to https://github.com/apple/swift-corelibs-foundation/issues/5028 as a cause for these failures, so until that is fixed and available in a nightly toolchain, we need to keep these tests from running.
None
Test-only change
=> mask out tests that are failing on Linux

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://128624412
This PR uses a new overload grouping implementation in SymbolKit to create overload group symbols in the unified symbol graph, rather than unifying individual symbol graphs' overload groups after the fact. This fixes a bug where disjoint overload groups (whether between platforms or via extensions) were not being combined.
https://github.com/swiftlang/swift-docc-symbolkit/pull/81
[This example doc catalog](https://github.com/user-attachments/files/16199979/asdf.docc.zip) contains two symbol graphs, one for macOS and one for iOS, each with one symbol that technically overload. It was generated from the following source code:
```swift
@available(macOS, unavailable)
public func myFunc(param: String) {}
@available(iOS, unavailable)
public func …
```
=> use SymbolKit's unified graph overload grouping

Sources/SwiftDocC/Semantics/Metadata/Availability.swift, Sources/SwiftDocC/Semantics/Symbol/DeprecationSummary.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md
Bug/issue #, if applicable: rdar://131987745
This PR updates the documentation for the `@Available` directive to:
- lead with information about when to use it and when to use in-source annotation instead
- add documentation for the new "deprecated" parameter and mention which versions of DocC support it.
- rephrases several sentences to avoid passive voice, for preferring "when you introduced this API" over "when this API was introduced".
- Combine the 3 code examples into 1 and wraps it in a `@Metadata` directive so that it's clearer that `@Available` is used within `@Metadata`.
It also unhides and documents the `@DeprecationSummary` directive to:
- provide information about when to use `@DeprecationSummary` and when to use in-source annotation instead
- provide tips about using …
=> Available directive docs

Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/FileRequestHandlerTests.swift
- **Explanation**: Another test is impacted by changes to Foundation's URL handling, and should be masked out so that CI can continue to pass.
- **Scope**: Test-only change
- **Issue**: None
- **Original PR**: None
- **Risk**: Very low. This is a test-only change that restricts the platforms a single test can execute on.
- **Testing**: Automated tests continue to pass.
=> mask testMalformedURI to only run on macOS

Package.resolved, Package.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
- **Explanation**: Use a new implementation for grouping overloads, to address bugs in the existing implementation.
- **Scope**: Bug fix in an experimental feature
- **Issue**: rdar://128624412
- **Original PR**: https://github.com/swiftlang/swift-docc/pull/986
- **Risk**: Low. The change is isolated to the use of an experimental feature, and the behavior has been validated to be the same.
- **Testing**: Automated and manual testing
- **Reviewer**: @d-ronnqvist 
This PR also includes an update to Package.swift to point to the release branches of our dependencies.
=> [6.0] use SymbolKit's unified graph overload grouping

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift
This removes an un-actionable warning. We've already removed a similar warning in #966. However, this warning is different in that there are real scenarios where we don't expect to resolve all external symbols, in which case this warning would be noise for expected behavior. 
None.
None
=> Remove un-actionable warning about not finding an external symbol

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+PathComponent.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Test Bundles/CxxOperators.docc/CxxOperators.symbols.json
Bug/issue #, if applicable: rdar://119616317
This improves support for parsing links to C++ operators so that `operator/=` and `operator-=-hash` are treated as single components (the latter with hash disambiguation).
It also refractors the path parsing code to extract and reuse common logic to make the main implementation more readable.
This is a small change (~100 LOC) with mostly tests (~200 LOC) and a very large symbol graph test file (7k+ LOC).
None
Define a type with some C++ operators. For example:
```cpp
/// A class with some custom operators
///
/// Links to those operators:
/// - ``operator+-15qb6``
/// - ``operator+-8k1ef``
/// - ``operator/``
/// - ``operator/=``
/// - ``operator--``
/// - ``operator++``
/// - ``operator[]``
/// - ``operator()``
/// - ``operator,``
class …
```
=> Support parsing links to C++ operators with trailing anchors and disambiguation 

Sources/SwiftDocC/Indexing/RenderIndexJSON/RenderIndex.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/DeclarationsSectionTranslator.swift, Sources/SwiftDocC/Utility/FoundationExtensions/String+Whitespace.swift, Sources/SwiftDocCTestUtilities/FilesAndFolders.swift, Sources/SwiftDocCUtilities/Action/Actions/Merge/MergeAction+SynthesizedLandingPage.swift, Sources/SwiftDocCUtilities/Action/Actions/Merge/MergeAction.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Merge.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/MergeSubcommandTests.swift, Tests/SwiftDocCUtilitiesTests/MergeActionTests.swift, features.json
Bug/issue #, if applicable: rdar://79160385
This makes the `docc merge` command synthesize a minimal "landing page" for the combined documentation. 
It also adds two new flags `--synthesized-landing-page-name` and `--synthesized-landing-page-kind` to customize small details about this page. The existence of the pair of these flags is indicted by a new entry in "features.json"
None
- Build documentation for two targets with dependencies. For example: [Inner.doccarchive (zip)](https://github.com/user-attachments/files/16658116/Inner.doccarchive.zip) and 
[Outer.doccarchive (zip)](https://github.com/user-attachments/files/16658118/Outer.doccarchive.zip).
- Merge the two archives into a combined archive using
```
swift docc merge /path/to/Inner.doccarchive /path/to/Outer.doccarchive
```
- …
=> Synthesize a minimal landing page for combined archives

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
This fixes a bug where the `PathHierarchy` didn't correctly identify the root node for article-only documentation, which caused it to not raise a `.moduleNotFound` error, which caused `LinkResolver` to not attempt to resolve external links.
None.
- ~[ ] Updated documentation if necessary~ Not applicable.
=> Fix a bug where article-only catalogs couldn't resolve external links

Sources/SwiftDocC/Utility/MarkupExtensions/ListItemExtractor.swift, Tests/SwiftDocCTests/Utility/ListItemExtractorTests.swift
Bug/issue #, if applicable: rdar://134356001 rdar://134439521
This adds support for multiple paragraphs (and other block content) for all list item tags, for example:
```
- Parameter someValue:
```
```
- Parameters:
- someValue:
```
```
- Returns:
```
, and more.
The added tests also  verifies that links are resolved in all blocks of content for these tags and that those diagnostics have correct source range information.
None.
- In documentation for some API, add multiple blocks of content for one or more tags, for example:
<pre><code>- Returns: First paragraph describing this tag, with ``FirstNotFoundSymbol`` link
Second paragraph of description, with ``SecondNotFoundSymbol`` link
- First inner unordered list item
- Second inner unordered list item
1. First inner ordered list item
1. …
=> Support multiple paragraphs (and other block content) for all tags

Sources/SwiftDocC/Utility/MarkupExtensions/ListItemExtractor.swift, Tests/SwiftDocCTests/Utility/ListItemExtractorTests.swift
Bug/issue #, if applicable: rdar://134705941
This updates the parsing for "tagged" list (http responses, property list values, parameters, etc.) to support documenting responses/values/keys/parameters with spaces in the name.
For example:
```md
- DictionaryKey some key with spaces: Some description of this dictionary key.
```
now parses the entire "some key with spaces" as the name of the dictionary key that the documentation applies to.
None.
The hardest part of testing this is using a symbol graph file with list elements with spaces in the names. There is one such example among the test bundles.
- Add a new documentation extension file to `Tests/S` with the following content:
```md
A musical genre.
- PossibleValue Classic Rock: Some description of the classic rock genre.
- PossibleValue …
```
=> Support documenting http responses, property list values, parameters, etc. with spaces in the name

Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Sources/SwiftDocC/Model/Rendering/References/TopicRenderReference.swift, Tests/SwiftDocCTests/Rendering/RESTSymbolsTests.swift
Bug/issue #, if applicable:  129540266
Property list keys that define a human readable title (https://github.com/swiftlang/swift-docc/pull/987) should show the key name under the abstract when referenced form another symbol.
This pr adds the implementation to get this working by passing the property list key information to the topic render reference.
N/A
Steps:
1. Preview the attached docc archive.
2. Assert that in the top level page, the foo symbol displays the key name under the abstract section.
[plistkey.docc.zip](https://github.com/user-attachments/files/16849526/plistkey.docc.zip)
=> Display entitlement key in symbol reference

Sources/SwiftDocC/Indexing/RenderSection+TextIndexing.swift, Sources/SwiftDocC/Model/Rendering/Diffing/AnyRenderSection.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/CodableContentSection.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/HTTPParametersSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/HTTPResponsesSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/PlistDetailsSectionTranslator.swift, Sources/SwiftDocC/Model/Rendering/Symbol/PlistDetailsRenderSection.swift, Sources/SwiftDocC/Model/Rendering/Symbol/PropertyListDetailsRenderSection.swift, Sources/SwiftDocC/Model/Rendering/Symbol/RESTBodyRenderSection.swift, Sources/SwiftDocC/Model/Rendering/Symbol/RESTParametersRenderSection.swift, Sources/SwiftDocC/Model/Rendering/Symbol/RESTResponseRenderSection.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeHTTPRequestTests.swift, Tests/SwiftDocCTests/Rendering/PlistSymbolTests.swift, Tests/SwiftDocCTests/Rendering/PropertyListDetailsRenderSectionTests.swift, Tests/SwiftDocCTests/Rendering/RESTResponseRenderSectionTests.swift, Tests/SwiftDocCTests/Rendering/RESTSymbolsTests.swift, Tests/SwiftDocCTests/XCTestCase+AssertingTestData.swift
Bug/issue #, if applicable: rdar://103619334
The `PlistDetailsRenderSection`, `RESTParametersRenderSection`, `RESTBodyRenderSection`, and `RESTResponseRenderSection` structs are all internal. This appears to be an oversight as they mostly have public properties, and it limits the possibility for writing tools that use the RenderNode code for parsing render JSON.
In this PR I've made those symbols public along with any symbols referenced in their now-public APIs.
None.
No behavior changes, so I checked that the existing tests compile and run successfully.
=> rdar://103619334 make the REST and Plist render sections public.

Sources/SwiftDocC/Converter/Rewriter/RemoveAutomaticallyCuratedSeeAlsoSectionsTransformation.swift, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/PersistingDocumentation.md, Tests/SwiftDocCTests/Converter/RenderNodeTransformerTests.swift
This deprecates `RemoveAutomaticallyCuratedSeeAlsoSectionsTransformation` so that we can remove it after the next release.
I stumbled upon this unused public type while investigating a bug related to automatic See Also sections. 
None
None
=> Deprecate an unused public render node transformer

Sources/docc/DocCDocumentation.docc/DocC Documentation.md
Currently, there's a article (Documenting API with Different Language Representations) floating outside the curated structure of top level content at the high level Swift DocC documentation, visible at https://www.swift.org/documentation/docc/
This change updates the curation to move it inline with the other articles focused on documenting API.
none
visually reviewed the results in Xcode's documentation build of the content
Steps:
1. check out branch
2. build documentation for Swift-docc
3. visually review top-level documentation for Swift-docc
=> fixes curation of a floating article on API documentation

Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift, Sources/SwiftDocCUtilities/Action/Actions/PreviewAction.swift, Tests/SwiftDocCTests/Diagnostics/DiagnosticConsoleWriterDefaultFormattingTest.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/Utility/ListItemExtractorTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewActionIntegrationTests.swift
Bug/issue #, if applicable: rdar://125564508
This fixes a bug where preview-specific errors wasn't written to console.
None
The easiest preview-specific error to reproduce is an already used port.
With any documentation, open two terminal windows and start previewing the documentation on some port in the first window.
Now, preview the same documentation on the same port (using `--port`) in the other window. DocC should fail _with_ an error message that the port is already used. 
- ~[ ] Added tests~ There is no integration test setup that can verify this fix. 
=> Ensure that preview-specific errors are written to console

Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Model/Rendering/RenderNode/RenderNode+Codable.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift, Tests/SwiftDocCTests/Test Bundles/DeprecatedInOneLanguageOnly.docc/MyKit-objc.symbols.json, Tests/SwiftDocCTests/Test Bundles/DeprecatedInOneLanguageOnly.docc/MyKit-swift.symbols.json
Bug/issue #, if applicable: 131331606
Fixes a bug where DocC inherits platform availability information from the Swift variant of an API from its Objective-C variant. Specifically, it's possible for a symbol to be deprecated in Swift but not in Objective-C, in which case we should only show depreciation information for the Swift variant of the page.
The changes are split into two commits:
1. Fixes cross-language availability inheritance. This updates the symbol graph loader and render node translator to not inherit availability information from other language variants of the API.
2. Fixes `@DeprecationSummary` to only be shown on variants of the API that are actually deprecated. For backwards compatibility, if the API is not deprecated in any languages, we'll still show the deprecation …
=> Fix cross language availability inheritance

Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/ConvertSubcommandTests.swift
Bug/issue #, if applicable: rdar://136837581
This adds back the `--fallback-bundle-version` argument as a silently ignored option for backwards compatibility with tools that still pass it.
None
- Run `docc convert --help`
- The `--fallback-bundle-version` shouldn't be listed.
- Run `docc convert path/to/SomeCatalog.docc --fallback-bundle-version 1.2.3`
- The flag should be supported 
=> Add back `--fallback-bundle-version` argument for backwards compatibility 

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Catalog Processing/GeneratedCurationWriterTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalPathHierarchyResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://136864852
This selectively disables #643 without reverting all the changes
None.
=> Selectively disable type signature link disambiguation

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://136865335
This makes a small refinement to the ambiguous link diagnostic when the symbol name has a disambiguation-look-suffix.
Instead of suggesting to replace the disambiguation-look-suffix with each actual disambiguation, the updated diagnostic will suggest _adding_ the missing disambiguation (preserving the symbol name in the link).
None
=> Don't suggest replacing part of the symbol name in ambiguous link diagnostics

Sources/SwiftDocC/Infrastructure/DocumentationBundle.swift, Sources/SwiftDocC/Infrastructure/Workspace/DocumentationBundle+Info.swift, Sources/SwiftDocCTestUtilities/FilesAndFolders.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/ConvertAction+CommandInitialization.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/DocumentationService/DocumentationServer+DefaultTests.swift, Tests/SwiftDocCTests/Infrastructure/BundleDiscoveryTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationBundleInfoTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationWorkspaceTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift, Tests/SwiftDocCTests/Rendering/DefaultAvailabilityTests.swift, Tests/SwiftDocCTests/Rendering/DefaultCodeListingSyntaxTests.swift, Tests/SwiftDocCTests/Rendering/DocumentationContentRendererTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/FolderStructure.swift
This deprecates the version information on `DocumentationBundle.Info`. 
This information was never read and 6.0 was the last version that supported passing it on the command line.
None.
=> Deprecate `DocumentationBundle.Info.version`

Sources/SwiftDocC/Infrastructure/DocumentationBundleFileTypes.swift, Sources/SwiftDocC/Infrastructure/Input Discovery/DocumentationInputsProvider.swift, Sources/SwiftDocC/Infrastructure/Workspace/LocalFileSystemDataProvider+BundleDiscovery.swift, Sources/SwiftDocC/Utility/FileManagerProtocol.swift, Sources/SwiftDocCTestUtilities/TestFileSystem.swift, Tests/SwiftDocCTests/Infrastructure/Input Discovery/DocumentationInputsProviderTests.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystemTests.swift
Bug/issue #, if applicable: rdar://136208312
This is the _second_ of many changes to redefine how documentation contexts are created. 
This change specifically renames "documentation bundle" to "documentation inputs" and creates a new type that discovers documentation catalogs and creates documentation inputs. This is the same as `LocalFileSystemDataProvider` and `GeneratedDataProvider` except that it doesn't conform to `DocumentationWorkspaceDataProvider` (or any other protocol for that matter). 
This new code is't used anywhere (except in the tests that verify that it behaves the same as the previous code). It's going to be a large change to switch over to this implementation, so I've deferred that to a follow up PR because people have been saying that they prefer multiple smaller PRs …
=> Add simplified implementation of documentation input discovery 

Sources/SwiftDocC/Infrastructure/Topic Graph/AutomaticCuration.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeMultiLanguageTests.swift
Bug/issue #, if applicable: rdar://134376209
This limits the number of items in automatic See Also sections to 15 (chosen somewhat arbitrarily).
The reason for this limit is that the usefulness of a See Also section quickly diminishes as the number of items in it grows. Somewhere beyond 10-20 items, the reader is unlikely to find additional value in even more links. This is an indication that the "topic" is a bit too broad and would benefit from being broken down into smaller sub topics, perhaps on an API collection page.
None
- Organize 20 symbols into a topic section on any page
- Navigate to one of those pages
- At the bottom, in the See Also section, only the first 15 links will be displayed.
- …
=> Limit the number of items in automatic See Also sections

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift
Bug/issue #, if applicable: rdar://128609308.
Fixes a bug where disabling automatic role headings with directive `@AutomaticTitleHeading` would also result in the node's role being lost.
We always want to set the node's role as part of the node's metadata, regardless of any title settings. Some unit tests were added to ensure that the interaction between `AutomaticTitleHeading`, `.metadata.roleHeading` and `.metadata.role` is all working as expected.
For any API Collection render node, its metadata will look like:
```json
"metadata": {
"title": "API Collection",
"role": "collectionGroup",
"modules": [
{
"name": "AutomaticTitleHeading"
}
],
"roleHeading": "API Collection"
},
```
The role heading is used for rendering, and can be disabled via directive `@AutomaticTitleHeading`. In `main`, …
=> Always set role even if automatic role headings are disabled

Package.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionStaticHostableTests.swift
This stops surfacing the `SwiftDocCUtilities` library as a product meaning that consumers of the package no longer are able to import it.
After [this question in #1049](https://github.com/swiftlang/swift-docc/pull/1049#issuecomment-2399239291), a few of us talked offline and felt that we don't expect anyone to import this library and agreed that we should work to remove it. 
There was some discussion about how we can gradually phase it out, but we couldn't think of any good ways to deprecate an entire library but continue using it internally. Because of this, we settled on removing it immediately.
None
Nothing in particular. 
- ~[ ] Updated …
=> Remove SwiftDocCUtilities (the command line actions library) as a product

Sources/SwiftDocC/Indexing/Navigator/AvailabilityIndex+Ext.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorItem.swift, Sources/SwiftDocC/Infrastructure/Bundle Assets/DataAssetManager.swift, Sources/SwiftDocC/Model/Name.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift, Sources/SwiftDocC/Model/Rendering/Variants/VariantCollection+Variant.swift
This removes a few redundant `Hashable`, `Equatable`, and `Codable` conformance implementations where the synthesized implementation behaves the same. 
None
=> Remove a few redundant conformance implementations

Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
Bug/issue #, if applicable:  rdar://137762221
A node can only be declared as beta if it contains at least one availability item that includes all the defined characteristics. This code introduces a precondition requiring the node to have at least one availability item to be considered as potentially in beta.
Before this change, a node would be considered as beta when its availability set was empty.
N/A
Review unit tests.
=> Add a precondition for declaring a node as beta.

Package.resolved, Sources/SwiftDocC/Model/ParametersAndReturnValidator.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/Rendering/DeclarationsRenderSectionTests.swift
Bug/issue #, if applicable: rdar://137964801
This PR does two things:
- It fixes the alternate declaration behavior that broke with https://github.com/swiftlang/swift-docc-symbolkit/pull/85#event-14660183503
- It uses the new alternate signature data to support documenting parameters and return values that appear in a symbol's alternate declarations.
None
applicable._
Steps:
- ~[ ] Updated documentation if necessary~ Not applicable
=> Support documenting parameters and return from alternate declarations.

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Catalog Processing/GeneratedCurationWriterTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalPathHierarchyResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://137209299
This addresses a performance regression and re-enables type signature link disambiguation. 
I benchmarked these `PathHierarchy.functionSignatureTypeNames(for:)` changes using 60 long type signatures, repeated 20k times for a total of 120k signatures. With this input the new implementation is about 200 times faster.  
This improvement is partially due to:
- Leveraging the fragment's precise identifiers instead of string processing find the `Array<`, `Dictionary<`, and `Optional<` ranges to process
- Passing the already known `Array<`, `Dictionary<`, and `Optional<` locations instead of recomputing them using string processing
- Iterating over the string once to find which `>` balance each `<`
- Operating on UTF-8 code units instead of …
=> Re-enable type signature link disambiguation 

Sources/SwiftDocC/Utility/MarkupExtensions/BlockDirectiveExtensions.swift
This removes a repeated `TechnologyRoot.directiveName` line in list of known directives.
- [] Ran the `./bin/test` script and it succeeded
=> Remove repeated `TechnologyRoot.directiveName` in known directives list

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift
This fixed a few code warnings introduced by https://github.com/swiftlang/swift-docc/pull/1068
None
Nothing in particular. 
=> Fix a few recently introduced code warnings

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
Bug/issue #, if applicable:  rdar://138183564
Clients might want the Navigator Index to not preemptively add an entry for nodes that have a language variant trait. For example, a client might not have a renderer cable of applying language variants, in this instance it doesn't make sense to generate a navigator hierarchy for other languages.
Updated unit tests to validate the behavior
=> Make `NavigatorIndex.Builder` ignore language variants when requested

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift
Cherry-pick of https://github.com/swiftlang/swift-docc/pull/1077
=> 🍒 Make `NavigatorIndex.Builder` ignore language variants when requested

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocCTestUtilities/SymbolGraphCreation.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
- **Explanation:** This works around a Clang symbol graph bug where anonymous structs and anonymous unions and emitted differently from anonymous enumerations.
- **Scope:** Symbol graph files containing unnamed C structures emitted from recent versions of Clang fail to build documentation in DocC.
- **Issue:** rdar://139305015
- **Testing:** New tests verify that C structs without titles are given a fallback title on the page, in the navigation, in the URL, and in the path to the JSON file in the .doccarchive output.
- **Reviewer:** @anferbui  
- **Original PR:** #1100
=> [6.1] Workaround issues with empty titles for some unnamed C symbols (#1100)

Sources/SwiftDocC/Model/Rendering/Variants/JSONPointer.swift
This improves the performance of JSONPointer encoding which is a hot spot when building documentation for mixed Swift and Objective-C projects.
On an example mixed Swift and Objective-C project with 10k+ symbols, these changes improves the _total_ documentation convert time by almost 1%:
```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Metric                                   │ Change          │ main                 │ current              │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Duration for 'convert-total-time'        │ -0,9475 %¹      │ 14,88 sec            │ 14,739 sec           │
│ Duration for 'documentation-processing' …
```
=> Improve performance of JSONPointer encoding

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Utility/FoundationExtensions/String+Path.swift, Sources/SwiftDocCTestUtilities/TestFileSystem.swift, Sources/SwiftDocCUtilities/Action/Actions/Merge/MergeAction+SynthesizedLandingPage.swift
This resolves a few recently introduced warnings.
It also removes the need for `@testable import` in the testing utilities target.
None
Nothing in particular. This isn't used-facing.
=> Resolve a few recently introduced warnings

Sources/SwiftDocC/Converter/DocumentationNodeConverter.swift, Tests/SwiftDocCTests/Converter/DocumentationContextConverterTests.swift, Tests/SwiftDocCTests/Converter/TopicRenderReferenceEncoderTests.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Infrastructure/AnchorSectionTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationCuratorTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalPathHierarchyResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift, Tests/SwiftDocCTests/Model/PropertyListPossibleValuesSectionTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/PropertyListDetailsRenderSectionTests.swift, Tests/SwiftDocCTests/Rendering/RenderMetadataTests.swift, Tests/SwiftDocCTests/Rendering/TermListTests.swift, Tests/SwiftDocCTests/Utility/ListItemExtractorTests.swift
This removes a `throws` for a function that never raises any errors, removing the need to `try` at the call site.
AFAIK this is source compatible because existing call sites only get a warning that the `try` isn't necessary. 
None.
Nothing in particular. This isn't user-facing.
=> Remove `throws` for function that doesn't raise any errors.

Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/Action+performAndHandleResult.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Convert.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/EmitGeneratedCuration.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Index.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Init.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Merge.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Preview.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/TransformForStaticHosting.swift
This removes `mutating` for a function that never raises mutates anything, removing the need to use a `var` at the call site.
None.
Nothing in particular. This isn't user-facing.
=> Remove `mutating` from function that doesn't mutate anything

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex+Ext.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Infrastructure/Workspace/FileSystemProvider.swift, Sources/SwiftDocC/Infrastructure/Workspace/LocalFileSystemDataProvider+BundleDiscovery.swift, Sources/SwiftDocC/Infrastructure/Workspace/LocalFileSystemDataProvider.swift, Sources/SwiftDocC/Utility/FileManagerProtocol+FilesSequence.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/Indexer.swift, Sources/SwiftDocCUtilities/Action/Actions/IndexAction.swift, Sources/SwiftDocCUtilities/Action/Actions/TransformForStaticHostingAction.swift, Sources/SwiftDocCUtilities/ArgumentParsing/ActionExtensions/IndexAction+CommandInitialization.swift, Sources/SwiftDocCUtilities/ArgumentParsing/Subcommands/Index.swift, Sources/SwiftDocCUtilities/Transformers/StaticHostableTransformer.swift, Tests/SwiftDocCUtilitiesTests/ConvertActionTests.swift, Tests/SwiftDocCUtilitiesTests/IndexActionTests.swift, Tests/SwiftDocCUtilitiesTests/StaticHostableTransformerTests.swift, Tests/SwiftDocCUtilitiesTests/Utility/TestFileSystemTests.swift
This deprecates `FileSystemProvider` and `RenderNodeProvider`. They each had their issues. 
The clearest sign that `FileSystemProvider` was a poor API is that both call sites had to reimplement tree traversal to use it:
- `FileSystemRenderNodeProvider` implemented its own breadth first traversal to iterate over the files.
- `StaticHostableTransformer` had ~80 LOC of private recursive functions to iterate over the files and determine what their relative paths are.
The issues with `RenderNodeProvider` are more subtle. Ignoring the issues with the API naming; 
- `getProblems()` was never called, so conforming types created diagnostics that was never presented to the user.
- The issues represented by `getProblems()` was unexpected errors rather that user-facing …
=> Deprecate `FileSystemProvider` and `RenderNodeProvider`

Package.resolved, Package.swift, Sources/SwiftDocC/Benchmark/Metrics/PeakMemory.swift
This PR cherry-picks two recent PRs that landed in main just after the `release/6.1` branch was created.
cc @icanzilb @Kyome22 
- **Explanation**: Refactors some code in the benchmark runner for performance and clarity.
- **Scope**: Small refactor; no change to behavior.
- **Issues**: https://github.com/swiftlang/swift-docc/issues/1066
- **Original PRs**: https://github.com/swiftlang/swift-docc/pull/1067
- **Risk**: Very low. The changed code is minor and has equivalent semantics.
- **Testing**: Automated and manual testing has passed.
- **Reviewers**: @d-ronnqvist 
- **Explanation**: Updates Package.swift to use URLs ending in `.git`, for consistency with other first-party Swift packages.
- **Scope**: Minor update to package specification.
- **Issues**: None
- **Original PRs**: …
=> [6.1] Cherry-pick two last-minute PRs

Package.swift, Sources/SwiftDocC/Infrastructure/ConvertActionConverter.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Servers/FileServer.swift, Sources/SwiftDocC/Utility/FoundationExtensions/NoOpSignposterShim.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCTests/Utility/NoOpSignposterShimTests.swift
This adds macOS signpost intervals around various major convert tasks. This information can be helpful to cross reference other information against when working on performance, memory usage, etc.
To make it easier to add signpost intervals without repeating `#if canImport(os)` throughout the implementation, I made a no-op shim for the signposter type so that the call site doesn't need to check if it can emit an interval.
I made a similar shim for logging although nothing uses it to log yet.
None.
This isn't a user-facing change but you can verify the low-level developer output on macOS by running `log stream --predicate 'subsystem=="org.swift.docc"' --signpost` in one Terminal window and then running any `docc convert` command in another Terminal window.
Make …
=> Wrap various convert subtasks in signpost intervals

Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
Bug/issue #, if applicable:  140415995
Symbols that are unconditionally unavailable in all the platforms should not be tagged as beta.Before this fix the `isBeta` logic was returning true for symbols that were unavailable in all the platforms. Now is filtering out these platforms before assesing if it's beta or not.
_Describe any dependencies this PR might have, such as an associated branch in another repository._
See unit tests.
=> Remove beta tag from unavailable symbols.

Sources/SwiftDocC/Model/Rendering/Variants/JSONPointer.swift
- **Explanation:** This is a small isolated performance improvement that lowers the _total_ documentation convert time by almost 1% for mixed Swift and Objective-C projects.
- **Scope:** Small performance improvement for mixed Swift and Objective-C projects.
- **Issue:** rdar://141047138 
- **Testing:** Existing tests pass. Used DocC's benchmark script to measure the performance difference for a few different projects. 
- **Original PR:** #1099
=> [6.1] Improve performance of JSONPointer encoding

Sources/docc/DocCDocumentation.docc/other-formatting-options.md
Make it easier to pick which aside to use by showing the types of asides inline in the doc page visually.
None.
Build the DocC documentation catalog and preview it.
- Added tests (N/A)
- Ran the `./bin/test` script and it succeeded (tests not working on my machine but this should be NFC)
=> Display concrete examples of the different types of asides

bin/benchmark/Package.swift
Bug/issue #, if applicable: rdar://141185270
_Provide a description of what your PR addresses, explaining the expected user experience. 
Also, provide an overview of your implementation._
This updates the benchmark tool to require the same macOS version as DocC.
Run any command with the benchmark tool, as described in Benchmarking.md
=> Update benchmark tool to same macOS version as DocC

Package.swift, Sources/SwiftDocC/Infrastructure/ConvertActionConverter.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Servers/FileServer.swift, Sources/SwiftDocC/Utility/FoundationExtensions/NoOpSignposterShim.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCTests/Utility/NoOpSignposterShimTests.swift, bin/benchmark/Package.swift
This cherry pick contains two commits:
- **Explanation:** This adds no-op shims for signposting and logging, making it easier for us to add low-overhead logging or performance metrics in the code. The main reason for cherry-picking this is that it could reduce future risk if another cherry-pick does any logging. The alternative would be to cherry-pick this later or to modify later cherry-picks to remove any logging of signposting in them.
- **Scope:** Other cherry-picks that utilize signposting or logging will fail to build on the 6.1 branch. Higher chance of merge conflicts when cherry-picking from "main" to "release/6.1".
- **Issue:** rdar://141210010 
- **Testing:** Existing automated tests pass. Manually tested signpost output using `log stream --predicate …
=> [6.1] Wrap various convert subtasks in signpost intervals

Sources/SwiftDocC/Infrastructure/Diagnostics/Diagnostic.swift, Sources/SwiftDocC/Infrastructure/Diagnostics/Problem.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Semantics/Article/Article.swift, Sources/SwiftDocC/Semantics/DirectiveParser.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Semantics/Symbol/DeprecationSummary.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md, Tests/SwiftDocCTests/Semantics/MetadataTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
Bug/issue #, if applicable: rdar://138395778
This PR adds the following behavior changes:
1. (First commit) Support for authoring `@Metadata` directives in documentation comments. Some notes:
- Only the `@Available` and `@CustomMetadata` are supported as child directives of `@Metadata` in documentation comments. DocC ignores other directives and emits a warnings for their uses:
- If you author a `@Metadata` directive both in the symbol's documentation comment and documentation extension file, DocC will pick the one in the documentation extension, and ignore the one in the documentation comment and emit a warning.
2. (Second commit) Support `@DeprecationSummary` in doc comments. Adds support for authoring `@DeprecationSummary` messages in documentation comments. This is useful when you …
=> Support `@Metadata` and `@DeprecationSummary` in documentation comments

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+PathComponent.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
This fixes a very rare and unlikely bug where a Swift operator that contains both a symbol with a diacritic and a forward slash wouldn't parse as a symbol link correctly.
None.
Define a custom `☜⃩/` infix operator and link to it using `☜⃩/(_:_:)`. The link should resolve.
```swift
infix operator ☜⃩/ : DefaultPrecedence
/// This link should resolve ``☜⃩/(_:_:)``
public struct Something {
public static func ☜⃩/ (lhs: Self, rhs: Self) -> Bool { 
false
}
}
```
=> Parse Swift operators as link components for operators with symbol diacritics

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Metadata/AlternateRepresentation.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Utility/MarkupExtensions/BlockDirectiveExtensions.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Semantics/MetadataAlternateRepresentationTests.swift
Bug/issue #, if applicable: rdar://109417745
Adds a directive which is meant to be used in markdown extension files for a specific symbol:
```swift
@Metadata {
@AlternateRepresentation(``MyApp/MyClass/property``)
}
```
Where all variants of ``MyApp/MyClass/property`` will be added as variants of the current symbol.
Its purpose is to be able to define an alternative language representation for a symbol, where the alternative symbol is an unrelated symbol as far as the compiler is aware (i.e. they have different USRs in the symbol graph).
This makes it possible to switch between both symbols through the language switcher:
Whenever possible, the alternative language representations should be defined in-source, by using in-source annotations such as the `@objc` and `@_objcImplementation` …
=> Add directive for linking symbols as alternate representations

Sources/SwiftDocC/Semantics/Metadata/AlternateRepresentation.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md
The `Metadata` article curates a list of its child directives, with relevant topic titles.
This adds `AlternateRepresentation` to that list, in the same section as `SupportedLanguage` as they both deal with language representations.
N/A
Tested by previewing the `DocCDocumentation.docc` catalog locally.
Steps:
1. `docc preview Sources/docc/DocCDocumentation.docc`
2. Verify http://localhost:8080/documentation/docc/metadata shows `AlternateRepresentation` in the topic list as expected.
- ~~[ ] Added tests~~ -> Not applicable
=> Update Metadata article to include AlternateRepresentation

Sources/SwiftDocC/DocumentationService/Convert/Symbol Link Resolution/AbsoluteSymbolLink.swift, Sources/SwiftDocC/DocumentationService/Convert/Symbol Link Resolution/DocCSymbolRepresentable.swift, Sources/SwiftDocC/DocumentationService/Convert/Symbol Link Resolution/LinkCompletionTools.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/ExtendedTypeFormatTransformation.swift, Sources/generate-symbol-graph/main.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/AbsoluteSymbolLinkTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/DocCSymbolRepresentableTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/LinkCompletionToolsTests.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/ExtendedTypesFormatTransformationTests.swift
Bug/issue #, if applicable: rdar://141689095
This adds new functions for working with link completion in editor integrations. It also deprecates the old types and API.
The implementation for the new API calls the same code that DocC uses to parse links, compute disambiguation, and match symbols against written link strings, so its behavior will be much closer to how DocC behaves when building documentation than the old, now deprecated API, was.
None.
Call the new API. It should behave like the examples in the added tests.
=> Add new functions for working with link completion in editor integrations

Sources/SwiftDocC/Model/ParametersAndReturnValidator.swift, Sources/SwiftDocCTestUtilities/SymbolGraphCreation.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
- **Explanation:** Improve detection of inherited documentation comments for parameter and return validation.
- **Scope:** Unactionable warnings when passing `--enable-inherited-docs` and inherited documentation comment contains warnings.
- **Issue:** rdar://134534169 
- **Testing:** New tests verify that warnings aren't emitted for inherited documentation comments. Manually tested with a small 2 target project and with the original project where that issue was reported for. Existing automated tests pass. 
- **Reviewer:** @patshaughnessy   
- **Original PR:** #1130
=> [6.1] Improve detection of inherited documentation comments for parameter and return validation

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver+Breadcrumbs.swift, Sources/SwiftDocC/Model/Rendering/Navigation Tree/RenderHierarchyTranslator.swift, Tests/SwiftDocCTests/Infrastructure/SymbolBreadcrumbTests.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/Model/RenderHierarchyTranslatorTests.swift
Bug/issue #, if applicable: rdar://141365081
This fixes an issue where breadcrumbs would sometimes be missing in either language for some symbols with multiple language representations.
None.
This issue reproduces very inconsistently. You may need to repeat these steps tens of times (or more) to reproduce it.
For any project with a handful of symbols available in both Swift and ObjectiveC:
- Build and preview documentation 
- For a few different pages with multiple language representations:
- Verify that the Swift representation has breadcrumbs on the rendered page.
- Verify that the Objective-C representation has breadcrumbs on the rendered page.
- Repeat
=> Fix occasional missing breadcrumbs for some multi-language symbols

Sources/SwiftDocC/Model/ParametersAndReturnValidator.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift
Bug/issue #, if applicable: rdar://138771690
This updates the warnings about undocumented parameters to support unnamed parameters. 
Unnamed parameters can occur in C/C++ where the header doesn't name the function parameters or in Swift when a method explicitly names a parameter "_" to indicate that its unused.
Before this, DocC would warn about any parameter documentation that the developer wrote because that documentation didn't match any of the function parameter's names.
Now, DocC verifies named and unnamed parameters differently, allowing the developer to chose what name they use in the parameter documentation for unnamed function parameters. This allows the developer to pick a meaningful name for the documentation while still having warnings about too many or too few documented …
=> Support validating documentation for unnamed parameters

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver+Breadcrumbs.swift, Sources/SwiftDocC/Model/Rendering/Navigation Tree/RenderHierarchyTranslator.swift, Tests/SwiftDocCTests/Infrastructure/SymbolBreadcrumbTests.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/Model/RenderHierarchyTranslatorTests.swift
- **Explanation:** This fixes an issue where breadcrumbs would sometimes be missing in either language for some symbols with multiple language representations.
- **Scope:** Occasional missing breadcrumbs for some multi-language symbols.
- **Issue:** rdar://141365081 
- **Testing:** New tests verify that multi-language symbols have the expected render hierarchy values.. Manually tested with the original project where that issue was reported for by repeatedly building and previewing documentation. Existing automated tests pass. 
- **Reviewer:** @mayaepps 
- **Original PR:** #1135
=> [6.1] Fix occasional missing breadcrumbs for some multi-language symbols

Sources/SwiftDocC/Model/Identifier.swift, Tests/SwiftDocCTests/Infrastructure/ResolvedTopicReferenceTests.swift
Bug/issue #, if applicable: rdar://130698358
This fixes an incorrect equality (and hashing) implementation for `ResolvedTopicReference` which caused `/some/path#fragment` and `/some/pathfragment` to be considered "equal". This could for example result in reference collisions when a project contained both `SomethingViewController#Delegate` and `SomethingViewControllerDelegate`.
None
The user facing effects of this bug are a bit hard to test because you have to try and observe the secondary effect caused by the reference collision. It's very easy to verify in a [unit test](https://github.com/swiftlang/swift-docc/pull/1140/files#diff-31e03aa9b5cebdb6504d49b45638f5fe090cb2dd9a4d5b93b6fa7b6a87f41535R88-R91) though. 
Make sure you check off the following items. If they cannot be completed, …
=> Fix incorrect equality implementation for ResolvedTopicReference

Sources/SwiftDocC/Model/Identifier.swift, Tests/SwiftDocCTests/Infrastructure/ResolvedTopicReferenceTests.swift
- **Explanation:** Fix a bug in ResolvedTopicReference equality where `SomePage#Fragment` and `SomePageFragment` would be "equal" and collide.
- **Scope:** Possible topic reference collisions
- **Issue:** rdar://130698358 
- **Testing:** New tests verify topic reference equality. Existing automated tests pass. 
- **Reviewer:** @sofiaromorales @anferbui    
- **Original PR:** #1140
=> [6.1] Fix an incorrect equality implementation for ResolvedTopicReference

Package.resolved, Package.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorTree.swift, Sources/SwiftDocCTestUtilities/XCTestCase+TemporaryDirectory.swift, Sources/SwiftDocCUtilities/PreviewServer/PreviewHTTPHandler.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/PreviewHTTPHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/ServerTestUtils.swift, bin/check-source
This resolves or works around all current warnings.
None.
- Run `bin/test`
- There shouldn't be any warnings from building the source or the tests.
=> Resolve all current code warnings

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://142822416
This omits Swift tuple labels in DocC's type signature disambiguation so that a `(one: Int, two: Bool)` return value is disambiguated using `->(Int,Bool)` instead of `->(one:Int,two:Bool)`.
**Note:** Swift _does_ support overloading based on tuple labels, so there is an argument to be made for including it in the disambiguation. 
```swift
func something() -> (first: Int, second: Bool)
func something() -> (one:   Int, two:    Bool)
```
However, I believe that it's a much more common—but still fairly uncommon—to have overloads with different _types_ (including tuple element types) rather than different _tuple labels_ and that it's better to optimize the experience for that. For example; 
The Swift standard library has two `insert(_:)`overloads …
=> Omit Swift tuple labels in type signature disambiguation

Package.resolved, Package.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorTree.swift, Sources/SwiftDocCTestUtilities/XCTestCase+TemporaryDirectory.swift, Sources/SwiftDocCUtilities/PreviewServer/PreviewHTTPHandler.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/PreviewHTTPHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/ServerTestUtils.swift, bin/check-source
The changes from https://github.com/swiftlang/swift-docc/pull/1143 are blocking PRs from being merged in the Swift compiler repo because the NIO dependency is not new enough ([example](https://ci.swift.org/job/swift-PR-Linux-smoke-test/16990/console)). Updating the version of NIO that this project depends on will need to be done in conjunction with an update to update-checkout.sh in the https://github.com/swiftlang/swift repo.
=> Revert "Resolve all current code warnings (#1143)"

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://142971761
This updated the processing of return type declaration fragments so that tuple elements are split into individual type disambiguation values. This makes it possible to disambiguate a disambiguate a `(Int, Bool, String)` return type using only one of those tuple elements, in other words; `->(Int,_,_)` , `->(_,Bool,_)`, `->(_,_,String)`, or `->(_,_,_)` (depending on the other overloads.)
This matches [the documented behavior](https://www.swift.org/documentation/docc/linking-to-symbols-and-other-content#Ambiguous-Symbol-Links) for type signature disambiguation. 
None
Make a few overloads that return different tuples and write a link to the overloaded function name. 
```swift
public func something() -> (Int, String)         { fatalError("Not …
```
=> Split tuple return types into smaller type disambiguation elements

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** This splits tuple return values into into individual type disambiguation values so that it's possible to disambiguate links using only a some of those tuple elements which is the intended and [documented](https://www.swift.org/documentation/docc/linking-to-symbols-and-other-content#Ambiguous-Symbol-Links) behavior for type signature disambiguation.
- **Scope:** Return type disambiguation needs to specify all tuple elements, rather than only the uniquely disambiguating elements. 
- **Issue:** rdar://142971761 
- **Testing:** New tests verify that tuple return values are split into individual disambiguation values. Manually verified that this surfaces in ambiguous link warnings. Existing automated tests pass. 
- **Reviewer:** @patshaughnessy     
- …
=> [6.1] Split tuple return types into smaller type disambiguation elements

bin/check-source
Update the `check-source` script to allow 2025 in the license header.
=> Add `2025` to allowed years in license header.

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://143817712
This fixes a bug with parsing of link strings that contain _both_ parameter type disambiguation and return type disambiguation where the return type is a tuple.
None.
applicable._
Steps:
=> Fix parsing bug for disambiguation with both parameter and return types

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/Semantics/Metadata/AlternateRepresentation.swift, Sources/SwiftDocC/Semantics/Metadata/Metadata.swift, Sources/SwiftDocC/Utility/MarkupExtensions/BlockDirectiveExtensions.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/Reference Syntax/API Reference Syntax/Metadata.md, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveIndexTests.swift, Tests/SwiftDocCTests/Semantics/DirectiveInfrastructure/DirectiveMirrorTests.swift, Tests/SwiftDocCTests/Semantics/MetadataAlternateRepresentationTests.swift
- **Explanation:** Adds a new directive `@AlternateRepresentation` which allows defining alternative language representations for a symbol using markdown.
- **Scope:** Adds a new directive which has link resolution functionality.
- **Issue:** rdar://109417745
- **Testing:** New tests verify that this new directive behaves correctly. Existing automated tests pass. 
- **Reviewer:** @d-ronnqvist 
- **Original PR:** https://github.com/swiftlang/swift-docc/pull/1097 and https://github.com/swiftlang/swift-docc/pull/1128
=> [6.1] Add `@AlternateRepresentation` directive

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** This fixes a parsing bug for symbol links where one path component has both parameter type disambiguation and return types disambiguation. If the return type disambiguation is a tuple, that information won't be parsed.
- **Scope:** Currently typed symbol links that require both parameter type and return type disambiguation won't resolve with nonsensical warnings about adding the disambiguation that's already written.
- **Issue:** rdar://143817712 
- **Testing:** New tests verify that these symbol links parse correctly.. Existing automated tests pass. 
- **Reviewer:** @sofiaromorales 
- **Original PR:** #1152
=> [6.1] Fix parsing bug for disambiguation with both parameter and return types

Sources/SwiftDocC/DocumentationService/Convert/Symbol Link Resolution/LinkCompletionTools.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/LinkCompletionToolsTests.swift
Bug/issue #, if applicable: rdar://143897549
This fixes a bug where DocC wouldn't suggest (but would accept) a combination of both parameter types and return types as link disambiguation if the symbol returned `Void`.
None.
Define 3 overloads; 2 with the same parameter type and two that return void. For example:
```swift
public func doSomething(with value: Int)    {   }
public func doSomething(with value: Bool)   {   }
public func doSomething(with value: Int) -> { 0 }
```
Write an ambiguous link to these overloads: ` ``doSomething(with:)`` `
DocC's warning about the ambiguous link should suggest `-(Int)->()` for the first overload.
- ~[ ] Updated documentation if necessary~ Not applicable
=> Support suggesting a combination of parameter types and return types as disambiguation when the function returns 'void'

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, bin/check-source
- **Explanation:** This fixes a bug where DocC wouldn't suggest (but would accept) a combination of both parameter types and return types as link disambiguation if the symbol returned `Void`.
- **Scope:** DocC suggests hash disambiguation in some cases where a more readable type signature disambiguation would be possible.
- **Issue:** <rdar://143897549>
- **Testing:** New tests verify that DocC suggests a combination of parameters and Void return as disambiguation, where applicable. Existing automated tests pass. 
- **Reviewer:** @sofiaromorales 
- **Original PR:** #1156 
Note: I also had to cherry-pick https://github.com/swiftlang/swift-docc/commit/b497975bcefaeb3bd012e6c3fda59405c70d8dca for the `bin/check-source` script to recognize the 2025 year in the license …
=> [6.1] Support suggesting a combination of parameter types and return types as disambiguation when the function returns 'void'

Sources/SwiftDocC/Benchmark/Benchmark.swift, Sources/SwiftDocC/Benchmark/Metrics/PeakMemory.swift, Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Model/Rendering/RenderContext.swift, Sources/SwiftDocC/Utility/FoundationExtensions/AutoreleasepoolShim.swift, Sources/SwiftDocC/Utility/Synchronization.swift, Sources/SwiftDocCUtilities/Utility/DirectoryMonitor.swift, Sources/SwiftDocCUtilities/Utility/Signal.swift, Sources/docc/main.swift, Tests/SwiftDocCTests/Servers/DocumentationSchemeHandlerTests.swift, Tests/SwiftDocCTests/Servers/FileServerTests.swift, Tests/SwiftDocCTests/Utility/LMDBTests.swift, Tests/SwiftDocCUtilitiesTests/C+Extensions.swift, Tests/SwiftDocCUtilitiesTests/DirectoryMonitorTests.swift
This PR fixes building swift-docc on x86_64 FreeBSD
All test passes! 
```
Build complete! (10.02s)
[1772/1772] Testing SwiftDocCTests.SwiftLMDBTests/testMultipleCustomObjects
➜  swift-docc git:(freebsd-wip) uname -msr
FreeBSD 14.1-RELEASE-p6 amd64
```
=> Fix FreeBSD build and test

Sources/SwiftDocC/Utility/ValidatedURL.swift, Tests/SwiftDocCTests/Utility/ValidatedURLTests.swift
- **Explanation:** This updates the implementation of `ValidatedURL(parsingAuthoredLink:)` to not parse query items since documentation links don't include query items (but "?" can appear in the link's path).
- **Scope:** DocC symbol links that include "?" may parse incorrectly, ending before the "?" character.
- **Issue:** <rdar://144230958>
- **Testing:** New tests verify the parsing of symbol links that include "?" in the disambiguation text. Existing automated tests pass. 
- **Reviewer:** @patshaughnessy @franklinsch 
- **Original PR:** #1159
=> [6.1] Don't parse query items for authored documentation links

Sources/SwiftDocCUtilities/Utility/Signal.swift
Bug/issue #, if applicable: rdar://145456460
This adds a dedicated `#if canImport(Musl)` implementation to DocC's `Signal` utility to allow building DocC with the Swift Static Linux SDK.
None.
- Follow the [Getting Started with the Static Linux SDK instructions on Swift.org][1] to set up a toolchain with the Swift Static Linux SDK.
- Build `docc` with the static Linux SDK
```
swift build --product docc --swift-sdk aarch64-swift-linux-musl
```
- The build should succeed.
[1]:https://www.swift.org/documentation/articles/static-linux-getting-started.html
=> Add "Musl" support for the `Signal` utility

Tests/SwiftDocCTests/Test Bundles/Snippets.docc/Test.symbols.json
Supports fixing an issue confusing snippets as both "main" and "extension" symbolgraphs for a particular module. The fix in swift-docc-symbolkit fails this specific fixture since it doesn't currently have a "main" graph, even empty as this one, to extend from. With this in place, the tests fully pass for properly resolving snippets symbolgraphs reliably.
related to fix for [swift-docc-symbolkit#88](https://github.com/swiftlang/swift-docc-symbolkit/issues/88)
none - this is a dependency for a fix in swift-docc-symbolkit
Ran unit tests with existing main branch as well as branch for fix in symbol kit.
=> adds a base symbolgraph for Snippets test fixture

Sources/SwiftDocCTestUtilities/TestFileSystem.swift
This removed the unused `TestFileSystem.Errors` type.
None 
=> Remove unused `TestFileSystem.Errors` type

Sources/SwiftDocC/Model/Rendering/References/ImageReference.swift, Sources/SwiftDocC/Model/Rendering/References/RenderReference.swift, Sources/SwiftDocC/Model/Rendering/References/VideoReference.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/References/DownloadReference.swift, Tests/SwiftDocCTests/Rendering/URLReferenceTests.swift
Bug/issue #, if applicable: rdar://146108301
Fixes an issue where roundtripping a `URLReference` would yield different results depending on the bundle identifier of the catalog processing the reference.
Paths to images and other downloadable content were always getting rendered into JSON with the bundle identifier of the current bundle, discarding the original path, regardless of whether the path already contained a reference to a different bundle. This caused issues when the resolved information from an out of process resolver contains a relative path.
For example, if the out of process reference resolver returns the following:
```json
"references": [{
"type": "image",
"identifier": "article-card.png",
"alt": null,
"variants": [
{
"traits": ["2x", "light"],
"url": …
```
=> Allow relative references to images across bundle identifiers

Sources/SwiftDocC/Infrastructure/CoverageDataEntry.swift, Tests/SwiftDocCTests/Coverage/CoverageDetailedOutputTests.swift, Tests/SwiftDocCTests/Coverage/CoverageSummaryTests.swift
Bug/issue #, if applicable: #205 
Updates the "USR" title from the detailed documentation coverage to "Reference Path".
None.
1. Run the `docc preview` command adding the `--experimental-documentation coverage` and `--coverage-summary-level detailed` flags. 
2. Once the detailed documentation coverage overview appears on your console, check the column titles for "Reference Path". 
- ~[] Added tests~
- ~[] Updated documentation if necessary~
=> Rename the documentation coverage header 'usr' to 'Reference Path'

Sources/SwiftDocC/Model/DocumentationNode.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
Bug/issue #, if applicable: 147354452
This works around a Clang compiler issue with parsing Objective-C or C comments like this example that are missing the leading asterisk on each line:
```
/**
Foo's brief description.
Foo's discussion.
*/
```
...as opposed to this which Clang does parse properly:
```
/**
* Foo's brief description. *
*
* Foo's discussion. */
```
With the first example, Clang passes a doc comment to DocC that contains leading whitespace at the beginning of all the  lines. This, in turn, causes DocC to parse the comment (via Swift Markdown) as a code listing that includes both the abstract and discussion:
This change to `DocumentationNode` removes the leading whitespace, allowing Swift Markdown to parse the comment as simple text, separating the abstract and discussion: …
=> Strip Leading Whitespace From Symbol Graph Doc Comments

Package.resolved
https://github.com/swiftlang/swift-docc/pull/1196 was landed before Swift-Markdown was properly set up for 6.2. Now that https://github.com/swiftlang/swift-markdown/pull/219 is landed, this PR updates the Package.resolved file in Swift-DocC to correctly use the `release/6.2` branch for swift-cmark.
=> update swift-markdown and swift-cmark for 6.2

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Serialization.swift
Bug/issue #, if applicable: rdar://148504975
This avoids a crash by accessing the identifier that the path hierarchy internally uses as a key rather than the identifier that's saved on the node. These should always be equal but some unexpected input can cause the node to have a different identifier than what the path hierarchy uses to find that node. The root cause of that issue still remains. This only avoids a crash that arises as a symptoms of the real issue.
None.
Because the root cause of this issue is still unknown, I can't provide better testing instructions than:
- Run `docc convert --enable-experimental-external-link-support` with some project that currently reproduces this crash.
It's not possible to write an automated test for this change because any inputs necessary to create …
=> Avoid a crash when using external link support with certain unexpected inputs.

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://148522712
This adds support for including Swift's `Any` in type signature disambiguation. `Any` is a keyword but it does represent type information. 
None
- Define two overloads that require `Any` as type disambiguation. For example
```swift
public func doSomething(with something: Any) {}
public func doSomething(with something: Int) {}
```
or 
```swift
public func doSomething() -> Any { 0 }
public func doSomething() -> Int { 0 }
```
- Write an ambiguous link to these overloads
```swift
/// Link to ``doSomething(with:)``
public enum Something {}
```
or
```swift
/// Link to ``doSomething()``
public enum Something {}
```
- Build documentation
- The warning about an ambiguous link should include `-(Any)` or `->Any` (depending on which of the above examples …
=> Support `Any` Swift keyword in type signature disambiguation

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: https://github.com/swiftlang/swift-docc/issues/1198 https://github.com/swiftlang/swift-docc/issues/1182
This fixes a crash when building documentation for a project that both extends a nested symbol of a dependency and shadows the name of the dependency with a local symbol.
None
- Define a public nested type in one module (the extend<b><I>ed</i></b> module) 
```swift
// in ExtendedModule
public struct SomeStruct {
public struct SomeNestedStruct {}
}
```
- Create another module (the extend<b><i>ing</i></b> module) that depends on the first module (the extend<b><I>ed</i></b> module) 
- In the second (extend<b><i>ing</i></b>) module, shadow the extended module with a public type
```swift
// Shadow the ExtendedModule module with a local type
public enum …
```
=> Fix crash when a nested symbol is extended and the a local symbol shadow extended module name

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+DisambiguatedPaths.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** This fixes a crash when building documentation for a project that both extends a nested symbol of a dependency and shadows the name of the dependency with a local symbol. Previously this only worked when top-level symbols were extended and the extended  module name was shadows by a local symbol.
- **Scope:** Crash for certain projects.
- **Issue:** <rdar://149838723> https://github.com/swiftlang/swift-docc/issues/1198 https://github.com/swiftlang/swift-docc/issues/1182
- **Testing:** Added tests verify that DocC handles extensions of _nested_ types when the extended module name is shadowed by a local symbol. Existing automated tests pass.
- **Reviewer:** @QuietMisdreavus 
- **Original PR:** #1202
=> [6.2] Fix crash when a nested symbol is extended and a local symbol shadow the extended module name

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** This fixes a bug where DocC would suggest incorrect type signature disambiguation for Swift symbols that include Swift's `Any` as a parameter or return value.
- **Scope:** Incorrect (unusable) link disambiguation for certain overloads.
- **Issue:** <rdar://148522712>
- **Testing:** Added tests verify that type signatures with Swift's `Any` keyword are processed correctly in parameters and return values including when `Any` is nested in tuples types, closures types, dictionary types, generics, etc. Existing automated tests pass.
- **Reviewer:** @QuietMisdreavus 
- **Original PR:** #1201
=> [6.2] Support `Any` Swift keyword in type signature disambiguation

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Serialization.swift
- **Explanation:** This avoids a crash by accessing the identifier that the path hierarchy internally uses as a key rather than the identifier that's saved on the node. These should always be equal but some unexpected input can cause the node to have a different identifier than what the path hierarchy uses to find that node. 
- **Scope:** Crash for certain unexpected inputs.
- **Issue:** <rdar://148504975>
- **Testing:** Manually tested with the impacted projects. Existing automated tests pass. It's not possible to write an automated test for this change because any inputs necessary to create a path hierarchy where a node has a different identifier than the key in the lookup would fail to construct due to [this assertion](https://github.com/swiftlang/swift-docc/blob/main/ …
=> [6.2] Avoid a crash when using external link support with certain unexpected inputs.

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/AutomaticCurationTests.swift
I'm nominating #1095 for the 6.2 on behalf of @ramcav 
- **Explanation:** This changes the order of articles in automatic curation to be based on the articles' titles rather than their URLs. 
- **Scope:** Order of articles in automatic curation. 
- **Issue:** https://github.com/swiftlang/swift-docc/issues/1192 <rdar://148534834>
- **Testing:** Added tests verify that automatically curated articles are sorted by their case insensitive title. Existing automated tests pass.
- **Original PR:** #1195
=> [6.2] Implemented alphabetic sorting by titles when automatically curating articles

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://144862231
When C unions are imported into Swift, they are converted into structs with computed properties to preserve union semantics. That means that the same symbol has different symbol kinds depending on the source language. This causes problems for the path hierarchy when associating those fields/properties with their parent, since there are now two separate hierarchy nodes that they could be associated with. This causes Swift-DocC to trigger a number of assertions due to the inconsistent state. (In release builds when debug assertions are compiled out, the issue is papered over with backup code, but the issue can still cause problems as evidenced with the need for workarounds like https://github.com/swiftlang/swift-docc/pull/1200.)
This PR updates …
=> clone path hierarchy nodes when their parent has a language-specific counterpart

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation**: Creates cloned PathHierarchy nodes when symbols have different symbol representations between interface languages.
- **Scope**: Fixes an inconsistency in the hierarchy tree that led to assertions and crashes.
- **Issues**: rdar://144862231
- **Original PRs**: https://github.com/swiftlang/swift-docc/pull/1203
- **Risk**: Low. This is new behavior for PathHierarchy, but the addition of new tests ensures that it works as expected.
- **Testing**: Automated tests have been added.
- **Reviewers**: @d-ronnqvist
=> [6.2] clone path hierarchy nodes when their parent has a language-specific counterpart

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Tests/SwiftDocCTests/Rendering/SymbolAvailabilityTests.swift
Bug/issue #, if applicable: rdar://146774862
This PR makes a small tweak to the default availability logic so it uses the symbol availability item platform name instead of the symbol graph platform name to calculate the corresponding default introduced version from the default availability.
N/A
[Availability.docc.zip](https://github.com/user-attachments/files/19893483/Availability.docc.zip)
Steps:
1. Preview the attached catalog.
2. Assert that the symbol Foo shows the visionOS platform as deprecated without version information.
=> Use availability item platform name to compute default availability information.

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Tests/SwiftDocCTests/Rendering/SymbolAvailabilityTests.swift
**Explanation:** Fixes an issue where platforms will inherit availability from other platforms when they shouldn't.
**Scope:** Fixes availability information in edge cases where a SGF contains availability information for all the platforms, and one of the symbols is deprecated without introduced version for a single platform.
**Issues**: rdar://146774862
**Original PRs:** https://github.com/swiftlang/swift-docc/pull/1208
**Risk:** Low.
Testing: Automated tests have been added and manual test has been made.
**Reviewers:** @anferbui
=> [6.2] Invalid introduced version

Sources/SwiftDocC/Model/DocumentationNode.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift
- **Explanation**: Work around a Clang compiler issue with parsing Objective-C or C comments that are missing the leading asterisk on each line.
- **Scope**: Changes the way DocC  processes doc comments from symbol graphs.
- **Issues**: rdar://147354452
- **Original PRs**: https://github.com/swiftlang/swift-docc/pull/1190
- **Risk**: Medium. This adds code to inspect and possibly mutate all doc comments from all symbol graphs. However, the PR adds some detailed tests, and we performed performance benchmarking while reviewing the original PR.
- **Testing**: Unit tests covering the important uses cases
- **Reviewers**: @d-ronnqvist
=> [6.2] Strip Leading Whitespace From Symbol Graph Doc Comments

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://150207195
The link resolver emits diagnostics for symbol links that require a disambiguation suffix (or a more precise suffix) to resolve to a single symbol. The diagnostic also includes fix-it solutions suggesting the available suffixes for the conflicting symbols. However, the logic for reporting the ranges of these possible replacements has a flaw when reporting on a curated symbol link: it always uses the full name of the symbol as the base instead of the written symbol or just the suffix.
This PR updates the diagnostic logic to handle the case of a found disambiguation suffix separately when reporting the diagnostic solutions.
None
The functionality is difficult to test outside of a unit test environment, as it requires non-overloadable symbols to …
=> use found disambiguation to calculate diagnostic range if present

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Semantics/ReferenceResolver.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
- **Explanation**: Updates diagnostic solution ranges when a given disambiguation is insufficient to point to a single symbol.
- **Scope**: Prevents diagnostics from being given with wrong/invalid ranges, including negative column indices.
- **Issues**: rdar://150207195
- **Original PRs**: https://github.com/swiftlang/swift-docc/pull/1213
- **Risk**: Low. The change is limited to diagnostic reporting code and shouldn't cause new errors in documentation processing. A new assertion is added but toolchain distributions of Swift-DocC turn assertions off so it shouldn't cause a problem for production uses.
- **Testing**: An automated test was added, and manual testing proved the change works with a larger set of triggering cases.
- **Reviewers**: @d-ronnqvist
=> [6.2] use found disambiguation to calculate diagnostic range if present

Sources/SwiftDocC/Utility/ValidatedURL.swift, Tests/SwiftDocCTests/Utility/ValidatedURLTests.swift
**Explanation:** This change prevents a potential DocC crash by making sure that it does not access an array element using an index that is outside of the bonds of the array.
**Scope:** Fixes crash of some documentation when building with Linux and Swift 5.9
**Issues:** rdar://150760264
**Original PRs**: https://github.com/swiftlang/swift-docc/pull/1214
**Risk:** Low.
**Testing:** Automated tests have been added and manual test has been made.
**Reviewers**: @anferbui @d-ronnqvist @QuietMisdreavus @patshaughnessy
=> [6.2] Prevent accessing unicode scalar element with incorrect index. (#1214)

Sources/SwiftDocC/Semantics/Article/ArticleSymbolMentions.swift, Tests/SwiftDocCTests/Semantics/ArticleSymbolMentionsTests.swift
Bug/issue #, if applicable: 150870055
This improves the stability of the sorting for the "Mentioned In" list of articles in the case where any pair of articles have mentioned a given symbol the same number of times.
This list is already sorted by weight where an article that mentions a symbol more times will appear closer to the top of the list. However in the scenario where two articles have the same given weight, the order is not deterministic due to the fact that the backing data structure is a Swift Dictionary where the items are not enumerated in a deterministic order. This addresses that by falling back to alphabetical order for articles with the same number of mentions for a given symbol.
Steps:
1. Configure a DocC catalog with a single symbol and 2 articles which both have one …
=> Sort equal weighted "Mentioned In" articles alphabetically

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://150706871&148247074 
This primarily fixes a crash caused by repeatedly cloning the same path hierarchy node. (https://github.com/swiftlang/swift-docc/commit/e161b2ab775a67a1ff065a6ffd6661b9261eb278)
Then if fixes additional crashes that were made more common due to cloned nodes (https://github.com/swiftlang/swift-docc/commit/4187f62992ae1673dbfc44c73882ce372b590ec0 and https://github.com/swiftlang/swift-docc/commit/c12c7d1e1563800e4d12fdeb2addd9f8b010226b)
Seeing these changes in aggregate I would like to take some time to reorganize the path hierarchy initializer to better distinguish the expected code paths from the code paths that try to gracefully handle incomplete symbol graph files. However, I would want to cherry-pick these crash fixes into the …
=> Fix crash caused by repeatedly cloning the same path hierarchy node

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** This fixes a few different indeterministic crashes that happen because of various degrees of incomplete symbol graph files.
- **Scope:** Crashes for certain inputs
- **Issue:** <rdar://150706871>
- **Testing:**  Added tests that build a symbol hierarchy for various incomplete symbol graph files. Manually verified with all projects that reported these crashes. Existing automated tests pass.
- **Reviewer:** @anferbui @binamaniar @QuietMisdreavus 
- **Original PR:** #1220
=> [6.2] Fix crash caused by repeatedly cloning the same path hierarchy node

Sources/SwiftDocC/Semantics/Article/ArticleSymbolMentions.swift, Tests/SwiftDocCTests/Semantics/ArticleSymbolMentionsTests.swift
- **Explanation**: Fixes an issue where "Mentioned In" list sorting may be deterministic when articles mention a given symbol the same number of times.
- **Scope**: Small additional logic added to sorting to specific "Mentioned In" feature
- **GitHub Issue**: NA
- **Risk**: Low: small, focused change that only impacts sorting of "Mentioned In" list
- **Testing**: Added unit tests. Can verify manually by mentioning a symbol on two articles and compiling the content. After this change, the order of the articles in "Mentioned In" for the symbol page should always be the same (sorted alphabetically). This is not always the case without this change.
- **Reviewer**: @bitjammer, @d-ronnqvist 
Original PR: #1221
=> [6.2] Sort equal weighted "Mentioned In" articles alphabetically

Package.resolved, Package.swift, Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift, Tests/SwiftDocCTests/Semantics/DoxygenTests.swift
Bug/issue #, if applicable:  rdar://147920933
This note adds support for Doxygen @abstract tag. Abstract tags are turned into normal paragraphs.
Swift-markdown dependency https://github.com/swiftlang/swift-markdown/pull/227
Create a documentation comment containing @abstract
This is an overview.
@abstract this is the content for abstract tag
- [ yes] Added tests
- [yes ] Ran the `./bin/test` script and it succeeded
- [ na] Updated documentation if necessary
=> Add support for abstract Headerdoc tag

build-script-helper.py
The docc rpath on FreeBSD included the OS version number, but the runtimes are not installed to that location resulting in the binary failing to launch. This fixes it to search in the correct place for the Swift runtime libraries.
=> FreeBSD: Fix docc rpath

Package.resolved
This only updates the resolved version of the swift-docc-plugin dependency to 1.4+ so that both DocC and the plugin depend on the "github.com/**swiftlang**/swift-docc-symbolkit" link to SymbolKit rather than the "github.com/**apple**/swift-docc-symbolkit" link. 
This fixes a warning when building DocC:
> Conflicting identity for swift-docc-symbolkit: dependency 'github.com/apple/swift-docc-symbolkit' and dependency 'github.com/swiftlang/swift-docc-symbolkit' both point to the same package identity 'swift-docc-symbolkit'.
Because the 1.3 dependency was previously specified in the Package.resolved file. Anyone who cloned DocC and built it would encounter this warning.
Update to a newer version of the swift-docc-plugin dependency.
Nothing in particular. This …
=> Update to a newer version of the Swift-DocC Plugin

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Topic Graph/TopicGraph.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationCuratorTests.swift
- **Explanation:** This ensures that curation inside of auto-curated API Collections (articles) are also visited.
- **Scope:** Redundant automatic curation of pages curated in an API Collection (article) that itself is auto-curated.
- **Issue:** <rdar://151731131>
- **Testing:**  Added a test that there's no duplicate curation in this setup. Manually verified with the project that originally reported this bug. Existing automated tests pass.
- **Original PR:** #1236
=> [6.2] Crawl the curation of auto-curated articles

Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderIndex.spec.json
Bug/issue #, if applicable: #1223
I grabbed the SlothCreator sample project and rendered it using swift-docc, reviewing the JSON it generated to see what might be correct for issue #1223 - and it seems that the correct propertyName is `schemaVersion`. This makes that change directly, but there's no existing tests to validate that I spotted, including even validating the the provided OpenAPI spec files  are able to be validated.
none
Manual - I ran OpenAPI generator externally to create models for the JSON data structures, and verified the warnings are resolved.
=> corrects schema version property name in RenderIndex.spec.json

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://152496046
This makes a small bug fix to type signature disambiguation for parameters or return values that are Swift metatypes (`Something.Type`). 
None.
- Define some overloads where one of the parameters or return values necessary for disambiguation is a metatype. For example:
```
public func doSomething(with value: Int) {}
public func doSomething(with type: BinaryInteger.Type) {}
```
- Write an ambiguous link to these overloads:
```
/// ``doSomething(with:)``
public enum Something {}
```
- The suggestions for what disambiguation to add to should use `BinaryInteger.Type` instead of just `BinaryInteger.` (with the trailing `.`)
- ~[ ] Updated documentation if …
=> Don't omit "Type" suffix from disambiguation for Swift metatypes

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://151311221
This fixes an issue where DocC would remove leading and trailing parentheses from certain closure types that return an empty tuple in Swift (as opposed to `Void`). This resulted in unexpected disambiguation suggestions that didn't actually work when applied to the ambiguous link.
None.
- Define some overloads where one of the parameters is a closure that returns `()`. For example:
```
public func doSomething(with closure: (Int) -> Int) -> Int { 0 }
public func doSomething(with closure: (Bool) -> ()) -> Int { 0 }
```
- Write an ambiguous link to these overloads:
```
/// ``doSomething(with:)``
public enum Something {}
```
- The suggestions for what disambiguation to add to should suggest `-((Bool)->())` instead of `-(Bool)->()` to indicate that …
=> Don't remove leading and trailing parentheses for closure types in type signature disambiguation

Sources/SwiftDocC/DocumentationService/Convert/Symbol Link Resolution/LinkCompletionTools.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/LinkCompletionToolsTests.swift
- **Explanation:** Avoid suggesting incorrect disambiguation in LinkCompletionTools when the caller passes symbol information with whitespace in the type signature.
- **Scope:** Incorrect suggested disambiguations in some cases.
- **Issue:** rdar://152496072
- **Testing:**  Added test that the LinkCompletionTools omit whitespace from its suggested disambiguations. Existing automated tests pass.
- **Original PR:** #1232
=> [6.2] Omit whitespace from suggested link completion disambiguations

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
- **Explanation:** This fixes an issue where DocC would remove leading and trailing parentheses from certain closure parameter types in the suggested disambiguation.
- **Scope:** Incorrect suggested disambiguations in some cases.
- **Issue:** rdar://151311221
- **Testing:**  Added tests that verify the suggested disambiguations for more and additional test validation that the suggested disambiguation work. Manually verified with the project where this issue was originally reported. Existing automated tests pass.
- **Original PR:** #1231
=> [6.2] Don't remove leading and trailing parentheses for closure types in type signature disambiguation

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphRelationshipsBuilder.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphRelationshipsBuilderTests.swift
Bug/issue #, if applicable: rdar://155967920
Prior to Swift 6.1 (specifically https://github.com/swiftlang/swift/pull/76983), Swift symbol graphs would contain both `requirementOf` and `optionalRequirementOf` relationships for imported optional Objective-C protocol methods. This can confuse Swift-DocC into nondeterministically displaying a "Required" marker for optional requirements based on which relationship it reads last. This PR addresses this nondeterminism by making `optionalRequirementOf` relationships take precedence over `requirementOf` ones in the `SymbolGraphRelationshipsBuilder`.
None
Steps:
1. Render documentation for a module with an imported Objective-C optional protocol requirement, as mentioned above.
2. Ensure that the "Required" indicator is not rendered for the …
=> optionalRequirementOf relationships take precedence over non-optional ones

Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Tests/SwiftDocCTests/Rendering/AvailabilityRenderOrderTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift
rdar://155978646 (Order of platforms is non-deterministic)
rdar://155977121 (Empty platform in availability section)
Swift developers can add global availability messages with no specific platform information, for example like this:
```swift
@available(*, deprecated, message:
"""
Don't use this function; call some other function instead.
"""
)
```
In this scenario, the Swift compiler adds an availability item with the message but no domain (platform name) to the symbol graph file, like this:
```json
{
"domain": "*",
"isUnconditionallyDeprecated": true,
"message": "Don't use this function; call some other function instead."
}
```
To avoid displaying an empty/null platform in the DocC Render user interface, `RenderNodeTranslator` needs to filter out these records. Additionally, …
=> RenderNodeTranslator.visitSymbol filters out availability items which have a missing domain

Sources/SwiftDocC/DocumentationService/Convert/Symbol Link Resolution/LinkCompletionTools.swift
Adds a new public initializer to `LinkCompletionTools.SymbolInformation` that will extract the function signature (if any) from a `SymbolGraph.Symbol`. This will primarily be used by SourceKit-LSP so that it doesn't have to re-implement the logic for constructing parameter and return type disambiguations.
- ~~[ ] Added tests~~
- ~~[ ] Updated documentation if necessary~~
No new tests needed: this only exposes existing functionality to SourceKit-LSP.
=> Add initializer to `LinkCompletionTools.SymbolInformation` that accepts a `SymbolGraph.Symbol`

Sources/SwiftDocC/Semantics/Symbol/UnifiedSymbol+Extensions.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
Bug/issue #, if applicable: rdar://156595902
When a symbol's information is loaded from multiple symbol graphs, Swift-DocC selects the documentation content from "the first Swift symbol with a doc comment, or the first symbol of any kind with a doc comment if no documented Swift symbol exists", where"first" here depends on the ordering of a Dictionary's keys. Because the ordering of those keys is not guaranteed, this can lead to a symbol's prose content being completely different between runs of DocC, despite no changes in the tool or the content, if there is a different comment between different platform's symbol graphs.
This PR addresses this by changing the way that commented symbols are selected. There is now a priority list of various sortings that decide which comment is selected …
=> prefer longer doc comments when selecting commented symbols

Sources/SwiftDocC/Model/Section/Sections/DefaultImplementations.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphRelationshipsBuilderTests.swift
Bug/issue #, if applicable: rdar://156311548
If there are multiple default implementations for a protocol method (currently happening in Swift symbol graphs due a bug when such methods are overloaded), the listed methods are unordered on the final rendered page. This can result in rendered content differing between builds, even when using the same build of DocC and the same content.
This PR enforces an order by sorting symbols via their topic reference URL before rendering.
None
As this is a nondeterminism bug, testing can be difficult and requires repeated executions for comparison. The unit test included in this PR only erratically would pass or fail, and required repeated attempts to ensure resolution.
Make sure you check off the following items. If they cannot be completed, provide a …
=> sort Default Implementations section contents when rendering

Sources/SwiftDocC/Semantics/Metadata/AlternateRepresentation.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json
Bug/issue #, if applicable: rdar://154206938
This fixes a single "Objective C" → "Objective-C" typo in the developer facing documentation for the `@AlternateRepresentation` directive.
None
- Build and preview the documentation
- Visit the local documentation for the `@AlternateRepresentation` directive
- The 2nd paragraph of the discussion should end with 
> [...], or the `NS_SWIFT_NAME` macro in Objective-C.
- ~[ ] Added tests~ n/a
=> Fix single "Objective-C" typo in developer facing documentation

Tests/SwiftDocCTests/Infrastructure/DocumentationBundleTests.swift, Tests/SwiftDocCTests/Infrastructure/InheritIntroducedAvailabilityTests.swift, Tests/SwiftDocCTests/Infrastructure/NodeURLGeneratorTests.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift, Tests/SwiftDocCTests/Model/TaskGroupTests.swift, Tests/SwiftDocCTests/Rendering/SymbolAvailabilityTests.swift, Tests/SwiftDocCTests/Utility/LMDBTests.swift, Tests/SwiftDocCTests/Utility/SemanticVersion+ComparableTests.swift, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/MergeSubcommandTests.swift, Tests/SwiftDocCUtilitiesTests/DirectoryMonitorTests.swift, Tests/SwiftDocCUtilitiesTests/FolderStructureTests.swift, Tests/SwiftDocCUtilitiesTests/HTMLTemplateDirectory.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/PreviewHTTPHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/DefaultRequestHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/ErrorRequestHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/FileRequestHandlerTests.swift, Tests/SwiftDocCUtilitiesTests/SignalTests.swift, Tests/SwiftDocCUtilitiesTests/StaticHostingBaseTest.swift, Tests/SwiftDocCUtilitiesTests/Utility/FileTests.swift
This removes various unused code in tests.
None.
- ~[ ] Updated documentation if necessary~ n/a
=> Remove miscellaneous unused test code

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift
This removes a little bit of unused private code in the symbol graph loader.
It's not clear to me if there's some place that's expected to call this code that doesn't.
None.
- ~[ ] Updated documentation if necessary~ n/a
=> Remove unused private code from the symbol graph loader

Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver+NavigatorIndex.swift
This removes two unused properties in the type that represents an external reference in the navigator.
None.
- ~[ ] Updated documentation if necessary~ n/a
=> Remove unused internal properties

Sources/SwiftDocC/Infrastructure/Symbol Graph/GeneratedDocumentationTopics.swift
This removes an unused property and an unused parameter from the GeneratedDocumentationTopic code.
It's not clear to me if there's some place that's expected to access this information that doesn't.
None.
- ~[ ] Updated documentation if necessary~ n/a
=> Remove unused property and parameter from GeneratedDocumentationTopic code

Sources/SwiftDocC/DocumentationService/Convert/Symbol Link Resolution/LinkCompletionTools.swift, Tests/SwiftDocCTests/Infrastructure/Symbol Link Resolution/LinkCompletionToolsTests.swift
This formally changes the `LinkCompletionTools` from SPI to public API.
None.
=> Formalize LinkCompletionTools as public API

Sources/generate-symbol-graph/main.swift
This fixes two new warnings about retroactive conformance to protocols in 'generate-symbol-graph' tool.
None
=> Fix warnings about retroactive conformance to protocols in 'generate-symbol-graph' tool

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorItem.swift, Sources/SwiftDocC/Indexing/Navigator/RenderNode+NavigatorIndex.swift, Sources/SwiftDocC/Indexing/RenderIndexJSON/RenderIndex.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver+NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/ExternalRenderNodeTests.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexableRenderMetadataTests.swift, Tests/SwiftDocCTests/Infrastructure/TestExternalReferenceResolvers.swift
Bug/issue #, if applicable: rdar://155521394
Currently DocC has some code in `RenderIndex` to be able to store whether a navigation item is beta or not, but the feature isn't supported yet:
https://github.com/swiftlang/swift-docc/blob/65aaf926ec079ddbd40f29540d4180a70af99e5e/Sources/SwiftDocC/Indexing/RenderIndexJSON/RenderIndex.swift#L257-L259
This PR propagates beta information for both render nodes and external render nodes to the navigation index such that we can ultimately encode the information as part of the navigator (i.e. `index.json` file):
```json
{
"beta": true,
"path": "/documentation/mykit/myclass",
"title": "MyClass",
"type": "class"
},
```
Same as in other parts of the codebase, an item is considered to be in beta if all of its platforms are in beta.
Navigator comparison …
=> Support beta status in navigator

Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/ExternalPathHierarchyResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver+NavigatorIndex.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Tests/SwiftDocCTests/Benchmark/ExternalTopicsHashTests.swift, Tests/SwiftDocCTests/Indexing/ExternalRenderNodeTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/TestExternalReferenceResolvers.swift, Tests/SwiftDocCTests/Model/DocumentationNodeTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Bug/issue #, if applicable: rdar://156487928
Fixes the navigator page type for external render nodes such that it takes into account the kind of symbol of the node.
In order to properly determine the navigator page type for a symbol, we need to know its symbol kind:
https://github.com/swiftlang/swift-docc/blob/65aaf926ec079ddbd40f29540d4180a70af99e5e/Sources/SwiftDocC/Indexing/Navigator/RenderNode%2BNavigatorIndex.swift#L148-L168
However, the symbol kind was not available for external nodes and all items were showing as their generic role, e.g. "article" or "symbol". 
This PR adds logic to derive an external render node's symbol kind:
1. Propagating the [`OutOfProcessReferenceResolver.ResolvedInformation`](https://github.com/swiftlang/swift-docc/blob/65aaf926ec079ddbd40f29540d4180a70af99e5 …
=> Populate symbol kind in external render nodes

bin/check-source
The `bin/check-source` script performs checks to ensure that headers are correctly updated in the modified files in a commit. This script ignored certain build directories since they contain generated Swift files. Some build directories were missing in this list (particularly the build directory emitted by `make-test-bundle`). The script has been modified to indiscrimanately ignore all `.build` directories.
=> Ignore all build dirs in `bin/check-source`

Sources/SwiftDocC/Checker/Checkers/AbstractContainsFormattedTextOnly.swift, Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver+Communication.swift, Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver+DeprecatedCommunication.swift, Sources/SwiftDocC/Infrastructure/External Data/OutOfProcessReferenceResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/ExternalPathHierarchyResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver+NavigatorIndex.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver.swift, Sources/SwiftDocC/LinkTargets/LinkDestinationSummary.swift, Sources/SwiftDocC/Model/Rendering/DocumentationContentRenderer.swift, Sources/SwiftDocC/Model/Rendering/RenderContext.swift, Sources/SwiftDocC/Model/Rendering/RenderNodeTranslator.swift, Sources/SwiftDocC/SwiftDocC.docc/SwiftDocC/StaticAnalysis.md, Tests/SwiftDocCTests/Benchmark/ExternalTopicsHashTests.swift, Tests/SwiftDocCTests/Checker/Checkers/AbstractContainsFormattedTextOnlyTests.swift, Tests/SwiftDocCTests/DocumentationService/ConvertService/ConvertServiceTests.swift, Tests/SwiftDocCTests/DocumentationService/DocumentationServer+DefaultTests.swift, Tests/SwiftDocCTests/Indexing/ExternalRenderNodeTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalPathHierarchyResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/ExternalReferenceResolverTests.swift, Tests/SwiftDocCTests/Infrastructure/TestExternalReferenceResolvers.swift, Tests/SwiftDocCTests/LinkTargets/LinkDestinationSummaryTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/OutOfProcessReferenceResolverV1Tests.swift, Tests/SwiftDocCTests/OutOfProcessReferenceResolverV2Tests.swift, bin/test-data-external-resolver
This reverts #1299 after fixing the Windows build in https://github.com/swiftlang/swift-docc/pull/1300/commits/764d363c8a313c1d1dca961c4eae9e51242d6bc4.
=> Revert #1299

bin/benchmark/Package.swift, bin/benchmark/Sources/benchmark/BenchmarkResultSeries.swift, bin/benchmark/Sources/benchmark/Commands.swift, bin/benchmark/Sources/benchmark/Diff/DiffAnalysis.swift, bin/benchmark/Sources/benchmark/Diff/DiffResultsTable.swift, bin/benchmark/Sources/benchmark/Subcommands/CommitCommands.swift, bin/benchmark/Sources/benchmark/Subcommands/Diff.swift, bin/benchmark/Sources/benchmark/Subcommands/Measure.swift, bin/benchmark/Sources/benchmark/Subcommands/RenderTrend.swift
With https://github.com/swiftlang/swift-docc/pull/1268 updating the minimum macOS version from 12 to 13, the benchmark scripts could no longer use the local DocC. 
This update the benchmark scripts to use Swift 6 and to also require macOS 13.
None.
Run the benchmark scripts. There shouldn't be any compiler errors.
=> Update the bin/benchmark script to Swift 6

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+PathComponent.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignatureDisambiguation.swift, Sources/SwiftDocC/Model/Rendering/Tutorial/LineHighlighter.swift, Sources/SwiftDocC/Utility/CollectionChanges.swift
This PR adds ownership and non-copyable annotations to some low level implementation details to avoid a few possible unnecessaries copies of data (and to get warnings about changes that may introduce unwanted copies in this code).
On the scale of a full documentation build of a large multi-language framework, these changes have no measurable impact:
``` 
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Metric                                   │ Change          │ main                 │ current              │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Duration for 'convert-total-time'        │ no change¹      │ 9,067 sec            │ …
```
=> Avoid a few possible unnecessary copies in low level implementation details

Package.resolved, Package.swift
Update the dependant packages to match 6.2.1, so parent dependencies like sourcekit-lsp will not have version errors.
=> Update dependant packages to match 6.2.1 branch

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/SnippetResolver.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Semantics/Snippets/Snippet.swift, Sources/docc/DocCDocumentation.docc/DocC.symbols.json, Sources/docc/DocCDocumentation.docc/adding-code-snippets-to-your-content.md, Tests/SwiftDocCTests/Checker/Checkers/NonInclusiveLanguageCheckerTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Infrastructure/SnippetResolverTests.swift, Tests/SwiftDocCTests/Semantics/Reference/TabNavigatorTests.swift, Tests/SwiftDocCTests/Semantics/SnippetTests.swift, Tests/SwiftDocCTests/Semantics/SymbolTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
Bug/issue #, if applicable: rdar://147926589&161164434 #1280
This improves the handling of snippet symbol graph files by no longer relying on main module / bystander logic and instead detecting snippets based on their symbol kind and handling them in a dedicated code path. 
By avoiding the main bystander symbol graph logic, this avoid issues with DocC miscategorizing the snippets symbol graph file as a separate module, resulting in their being two different "roots" of the documentation hierarchy (which is undefined behavior, with known nondeterminism, in DocC). The effect of this is that:
- Snippets are no longer added to the `PathHierarchy`
- Snippets no longer have `ResolvedTopicReference` identifiers
- Snippets no longer have `DocumentationNode` or `TopicGraph/Node` values that need to …
=> Improve handling of snippet symbol graph files

Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
This fixes a test that became flaky after https://github.com/swiftlang/swift-docc/pull/1302.
The logic in https://github.com/swiftlang/swift-docc/pull/1302 isn't the problem. The problem is that this test was unrealistically mixing snippet symbols with real symbols in the same symbol graph file. 
Depending on which symbol appears _first_ in the dictionary of symbols, the entire symbol graph was categorized as either a snippet symbol graph or a regular symbol graph. This works for real symbol graph files because snippets symbol graphs files are created by a different tool than the module symbol graph files.
None.
Run this test (`testContextDoesNotRecognizeNonOverloadableSymbolKinds`) repeatedly _with_ relaunching the test for each repetition so that the symbols …
=> Fix test that became flaky after recent snippets change

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Error.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/SnippetResolver.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Model/DocumentationNode.swift, Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift, Sources/SwiftDocC/Semantics/Snippets/Snippet.swift, Tests/SwiftDocCTests/Checker/Checkers/NonInclusiveLanguageCheckerTests.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift, Tests/SwiftDocCTests/Infrastructure/SnippetResolverTests.swift, Tests/SwiftDocCTests/Semantics/Reference/TabNavigatorTests.swift, Tests/SwiftDocCTests/Semantics/SnippetTests.swift, Tests/SwiftDocCTests/XCTestCase+LoadingTestData.swift
- **Explanation:** This improves the handling of snippet symbol graph files by no longer relying on main module / bystander logic and instead detecting snippets based on their symbol kind and handling them in a dedicated code path.
- **Scope:** Snippets non-deterministically aren't recognized.
- **Issue:** rdar://147926589 rdar://161164434 #1280
- **Risk:** Low. (Isolated to Snippets and the projects that use them).
- **Testing:**  Added tests that verify that snippets are recognized, that they're not processed as "regular" symbols/modules, and that verifies the user-facing diagnostics when they _correctly_ can't be found (for example because of misspellings). Existing automated tests pass.
- **Reviewer:** @QuietMisdreavus @heckj 
- **Original PR:** #1302 
---- 
This also cherry-picks …
=> [6.2.1] Improve handling of snippet symbol graph files (#1302)

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/ExternalPathHierarchyResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/LinkResolver.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+Find.swift, Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchyBasedLinkResolver.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/ExtendedTypeFormatTransformation.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Sources/SwiftDocC/Utility/FoundationExtensions/RangeReplaceableCollection+Group.swift, Sources/SwiftDocC/Utility/FoundationExtensions/Sequence+FirstMap.swift, Sources/SwiftDocC/Utility/Synchronization.swift
This PR adopts [SE-0413](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0413-typed-throws.md) where possible to provide callers with more information about possible raised errors.
- https://github.com/swiftlang/swift-docc/commit/ac7eeaeff51394ad351270ff665ab325e6778f76 updates code where the caller _knew_ the only possible errors were raised but needed a redundant catch block to satisfy the compiler:
```swift
do {
try doSomething()
} catch let error as KnownError {
// ...
} catch {
fatalError("`doSomething()` only throws `KnownError`")
}
```
By providing the compiler with information about the errors that `doSomething()` can raise, the compiler can verify that the implementation doesn't unintentionally raise any other errors and the default …
=> Adopt typed throws to provide callers with more information about possible raised errors

Sources/SwiftDocC/Model/Rendering/RenderSectionTranslator/DeclarationsSectionTranslator.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/DeclarationsRenderSectionTests.swift, Tests/SwiftDocCTests/Rendering/RenderNodeTranslatorSymbolVariantsTests.swift
Bug/issue: rdar://158142013
This PR addresses an inconsistency in platform representation within declaration fragments. Previously, when iOS was present in a symbol's platform availability, declaration fragments would only show iOS, while other parts of the system correctly included fallback platforms (iPadOS and Mac Catalyst). 
The implementation adds automatic platform expansion using the existing `DefaultAvailability.fallbackPlatforms` mapping to ensure consistent platform representation across all documentation outputs.
None.
The functionality can be tested using the provided `Availability.docc` sample bundle.
[Availability.docc.zip](https://github.com/user-attachments/files/22750799/Availability.docc.zip)
Steps:
1. Run `swift run docc convert Availability.docc --output-dir …
=> Fix missing platforms in declaration fragments
