Sources/SwiftDocC/Servers/DocumentationSchemeHandler.swift, Tests/SwiftDocCTests/Servers/DocumentationSchemeHandlerTests.swift
Originated from #50
- Remove unnessary available check
- Rename test file
=> Clean up code

Tests/SwiftDocCUtilitiesTests/OutOfProcessReferenceResolverTests.swift
Cherry-pick #79 to `release/5.6`
rdar://88498898
=> [Test] Disable a flaky test

Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/FirstCurationRoot.md, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/Info.plist, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/MultiCuratedSubtree.md, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/MultiCuratedSubtree.symbols.json, Tests/SwiftDocCTests/Test Bundles/MultiCuratedSubtree.docc/SecondCurationRoot.md
Cherry pick of https://github.com/apple/swift-docc/pull/292 for release.
rdar://94798570
=> [5.7] Ensure that children of multicurated pages get properly multicurated as well

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphRelationshipsBuilder.swift, Sources/SwiftDocC/Semantics/Symbol/Relationship.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphRelationshipsBuilderTests.swift
Close #182 
```swift
@objc public protocol MyProtocol {    
func hello1()
@objc func hello2()
@objc optional func hello3()
}
```
=> Add optionalRequirementOf builder

Tests/SwiftDocCTests/Semantics/ChoiceTests.swift, Tests/SwiftDocCTests/Semantics/MetadataTests.swift, Tests/SwiftDocCTests/Semantics/MultipleChoiceTests.swift, Tests/SwiftDocCTests/Semantics/TutorialArticleTests.swift, Tests/SwiftDocCTests/Semantics/TutorialTests.swift
See more info on apple/swift-markdown#49
Split the unlated change on #278 about swift-markdown
apple/swift-markdown#50
=> Update test data to fit the swift-markdown

Sources/SwiftDocC/SwiftDocC.docc/Resources/ThemeSettings.spec.json, Sources/docc/DocCDocumentation.docc/customizing-the-appearance-of-your-documentation-pages.md
Bug/issue #, if applicable: 101345143
The OnThisPageNav changes to be optional. This PR documents the change in the spec.
NA
NA
=> Add onThisPageNav flag to the ThemeSettings.spec.json

Sources/SwiftDocCUtilities/Docc.swift
A follow-up PR to fix the issue introduced by #604 - Unable to use `PreviewAction` on all platforms.
_Describe any dependencies this PR might have, such as an associated branch in another repository._
applicable._
Steps:
=> Fix preview issue on macOS and Linux

Sources/SwiftDocC/Servers/FileServer.swift
Windows can support the mime type sniffing via URL Monikers (similar to how Darwin can use UTI).  This requires a newer toolchain as it requires a modified WinSDK module.
=> SwiftDocC: implement mime type sniffing for Windows

Package.resolved, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift, Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift, Tests/SwiftDocCTests/Rendering/RenderContentCompilerTests.swift
Fix swift toolchain CI test case failing due to the swift-markdown breaking change PR.
=> Update swift-markdown and fix test case

Sources/docc/DocCDocumentation.docc/footer.html
Update the year in DocC's documentation footer
None
N/A
=> Update year in DocC documentation footer

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Cherrypick of #759
**Explanation**: Fix a crash in a non-standard setup when a multi source-language module is built together with its extending module. See #759 for detailed description.
**Scope**: Uncommon crash in non-standard setup.
**Issue**: <rdar://117499236>
**Risk**: Low. 
**Testing**: Added tests and a handful of new debug assertions and ran the existing test, built the project where this was originally found and a few other multi source-language projects.
**Reviewer**: @patshaughnessy @QuietMisdreavus
=> [5.10] Fix crash where multi-language symbols could get parents not in the tree

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
Bug/issue #, if applicable: rdar://119300362
This makes additional fixes to not hit the debug assertions added in #759 when building documentation in the same non-standard setup. 
The debug assertion happens when a symbol from an _extending_ module (which doesn't normally build together with the extended module) is added to the wrong language representation of its multi-language container symbol. 
Note: in release builds, this isn't an issue since the code after the assertion fixes the inconsistency. 
This is fixes by using checking the different names of the container symbol's different language representations. See code comment for more details.
None.
Because this is a non-standard setup, testing it is a bit cumbersome. The easiest would be to 
- Create a project with two Swift targets: …
=> Avoid hitting a debug assertion when building documentation in a non-standard setup

Sources/SwiftDocC/Infrastructure/Bundle Assets/DataAssetManager.swift, Sources/SwiftDocC/Infrastructure/Workspace/LocalFileSystemDataProvider+BundleDiscovery.swift, Sources/SwiftDocC/Model/Rendering/Variants/RenderNodeVariantOverridesApplier.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/JSONEncodingRenderNodeWriter.swift, Sources/SwiftDocCUtilities/Action/Actions/IndexAction.swift, Sources/SwiftDocCUtilities/Action/Actions/PreviewAction.swift
This removes defined error types that are never used anywhere. None of these were public API so removing them won't cause any breaking changes.
None.
Build DocC. There shouldn't be any compiler errors.
=> Remove errors that are never raised anywhere.

Tests/SwiftDocCTests/Rendering/TermListTests.swift
Bug/issue #, if applicable: rdar://124123172
This adds a test to verify an existing behavior; that term definition lists support various forms of local and external links (and code voice) as the term.
This behavior is already documented:
> A list item's text, including terms and their definitions, can use the same style attributes as other text, and include links to other content, including symbols.
None
None.
=> Add a test to verify that term lists support links and code

Sources/SwiftDocC/Infrastructure/DocumentationContext.swift, Tests/SwiftDocCTests/Infrastructure/DocumentationContext/DocumentationContextTests.swift
- **Explanation:** Excludes documentation extension files from DocC's check that all documents in a catalog must have unique filenames. Previously, one of the doc extensions' content would be dropped (and a diagnostic would be emitted about a redeclared file), which can be confusing when the extensions are for separate symbols with the same name. However, since documentation extensions' filenames have no impact on the URL of those pages, there's no need to enforce unique filenames for them.
- **Scope:** Only impacts documentation extension files with the same filename.
- **Issue:** rdar://117174884
- **Risk:** Low. Excludes documentation extension files (defined as articles starting with an H1 containing link) from DocC's check that all documents in a catalog must have unique filenames.
- …
=> [6.0] Don't enforce unique filenames for documentation extensions

Sources/docc/DocCDocumentation.docc/adding-tables-of-data.md
Bug/issue #, if applicable: rdar://122293614
This makes a handful of minor edits to the article about tables to 
- Avoid passive voice
- More explicitly address the reader
- Fix grammar and wording mistakes
None.
=> Make minor phrasing changes to table article

Sources/SwiftDocC/Coverage/DocumentationCoverageOptions.swift, Sources/SwiftDocC/Indexing/Navigator/AvailabilityIndex.swift, Sources/SwiftDocC/Indexing/Navigator/NavigatorIndex.swift, Sources/SwiftDocC/Infrastructure/Workspace/DefaultAvailability.swift, Sources/docc/DocCDocumentation.docc/Reference Syntax/Tutorials Syntax/tutorial-syntax.md, Tests/SwiftDocCUtilitiesTests/ArgumentParsing/DocumentationCoverageKindFilterOptionsTests.swift
Fix some typos.
1. subcript -> sub `s` cript
2. interfaceLangauge -> interfaceLang `ua` ge
3. missingBundleI `n` dentifier -> missingBundleIdentifier
4. diferent -> dif `f` erent
5. comlete -> com `p` lete
=> Fix some typos

Package.resolved
Bug/issue #, if applicable: None
This PR updates Package.swift to the latest commit of SymbolKit, which includes bug fixes that allow more symbol graphs to be processed by Swift-DocC.
None
Ensure all functionality remains the same.
=> update SymbolKit to latest main

Sources/SwiftDocC/Model/ParametersAndReturnValidator.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift
- **Explanation:** This fixes a special case with the validation of parameter and return value documentation where a symbol that has different parameters on different platforms (defined using `#if os(...)`) non-deterministically can't document the parameters that are only available on some platforms.
- **Scope:** Parameter and return value documentation for functions that have different parameters on different platforms.
- **Issue:** rdar://130496794 
- **Testing:** New tests verify that a symbol with different parameters and return values on different platforms can consistently document all of them. Manually tested with a project that reproduce this issue. 
- **Reviewer:** @anferbui 
- **Original PR:** #979
=> [6.0] Support documenting platform specific properties and return values

Sources/SwiftDocC/Model/ParametersAndReturnValidator.swift, Tests/SwiftDocCTests/Model/ParametersAndReturnValidatorTests.swift
Bug/issue #, if applicable: rdar://134552183
This fixes a false positive validation about the return value documentation for Swift initializers. 
The function signature information in the symbol graph specifies that these initializers don't have a return value. However, from the caller's perspective they have a "conceptual" return value that there's sometimes a reason to document (for example to describe the situations when a failable initializer returns `nil`).
None
Document the return value of a Swift initializer. For example:
```swift
public struct Something {
/// - Returns: Some description.
public init() {}
}
```
=> Fix false-positive validation for Swift initializer returns value documentation 

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocCTestUtilities/SymbolGraphCreation.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift
Bug/issue #, if applicable: rdar://139305015
This works around issues with some unnamed C symbols having empty titles. 
None
applicable._
Steps:
=> Workaround issues with empty titles for some unnamed C symbols

Sources/SwiftDocC/Infrastructure/Link Resolution/PathHierarchy+TypeSignature.swift, Tests/SwiftDocCTests/Infrastructure/PathHierarchyTests.swift
On the one hand this is a very minor refinement. On the other hand it would strictly speaking be breaking links to include the fix in a later release.
This makes two small refinements to type signature disambiguation to:
- twork around the `any` keyword being emitted as a "text" token (rdar://142814138) 
- omit tuple labels from type signature disambiguation.
My main reason for suggesting that we cherry-pick these changes is that it _changes_ what's the expected disambiguation spelling is which would break existing links (even if the change is for the better). However, because type signature disambiguation is introduced in Swift DocC 6.1 we can avoid the issue with breaking existing links because there are no prior links with this syntax.
I should note that overloads …
=> [6.1] Omit Swift tuple labels in type signature disambiguation

Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift, Sources/SwiftDocC/Infrastructure/Workspace/DefaultAvailability.swift, Sources/SwiftDocC/Semantics/Symbol/Symbol.swift, Sources/SwiftDocCTestUtilities/FilesAndFolders.swift, Sources/SwiftDocCUtilities/Action/Actions/Convert/ConvertAction.swift, Tests/SwiftDocCTests/Infrastructure/SymbolGraph/SymbolGraphLoaderTests.swift, Tests/SwiftDocCTests/Model/SemaToRenderNodeTests.swift, Tests/SwiftDocCTests/Rendering/DefaultAvailabilityTests.swift, Tests/SwiftDocCTests/Rendering/SymbolAvailabilityTests.swift
This reverts commit 1ad9b6af874243135bb63a9ede1bd1808526206b.
Due to failing tests, the commit `1ad9b6af874243135bb63a9ede1bd1808526206b` is being reverted while I do investigations on the cause of the failures.
=> Revert "Fix availability logic refactor (#1065)"
